- app/routes/app/components/components/Nav.js
- app/utils/usd.js
- test/utils/usd.spec.js
This adds a utility for formatting a USD price so that it includes the dollar symbol and two decimal places. It uses this utility to format the ticker USD price.
Note: This was primarily an exercise in familiarizing. It may be worthwhile to leverage something like [accounting](https://github.com/openexchangerates/accounting.js) to do this sort of thing. This would [also handle](https://github.com/openexchangerates/accounting.js/commit/9d65e654a7cd4db0248bbeb99388642b3517f8fb) the native [toFixed rounding issue](https://stackoverflow.com/questions/10015027/javascript-tofixed-not-rounding).
Before:
After:
> Format ticker USD price with dollar symbol and two decimal places

- README.md
This makes a small change to the README to escape the space in the path to `Lnd/`. It also parallels the Linux path and leverages the tilde to reference the home directory.
> Escape space in Mac Lnd/ path in README

- README.md
Applies the link at the top of the Readme to the todos section as well. #90
Replaces #93, while attempting to follow the contribution guidelines
> Update the slack invite link in the Readme Todos section

- app/components/Wallet/ReceiveModal.js
- app/routes/app/components/App.js
lnd requires inputs to funding transactions to spend from pay-to-witness outputs.
> Generate witness addresses instead of p2pkh.

- app/components/Channels/Channels.js
This prop is required, so this fixes a warning and potential bad behavior if "Close Channel" is clicked while the prop is null.
Note channel closing may already be possible via ChannelModal closeChannel.
> Fix that Channels was not passing down closeChannel to Channel

- app/components/Network/CanvasNetworkGraph.js
Drop unused width/height state variables.
> Make the network graph fill the available window space

- app/routes/activity/components/components/Modal/Invoice/Invoice.js
- app/routes/activity/components/components/Modal/Invoice/Invoice.scss
This provides better UX and other dialogs have a copy button except for invoices. So, this provides uniformity across the platform.
> added button to copy invoice

- app/components/GlobalError/GlobalError.js
- app/components/GlobalError/GlobalError.scss
Solves #138 and #136 
`clearError` is automatically called after 10 seconds.
Styles were adjusted so that close icon is more visible and error message does not overflow over it.
> Error message enhancements

- .babelrc
- package.json
- yarn.lock
Was not installed and was configured for electron 1.6.
With this fix, babel builds for electron 1.7 / chrome 58, rather than just node 7.
> Fix browserslist to provide the proper dependencies for electron 1.7

- .babelrc
- .travis.yml
- README.md
- package.json
Node 7 was a dev release and is defunct now that 8 is LTS and 9 is the
current dev release. If we wanted to support earlier versions, we should
go all the way back to the prior LTS release series, 6, but I don't see
a reason to do that for new software.
Bump to npm 5 because that is the version that was released with node 8:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.0.0
This was prompted by the fact that current versions of yarn have dropped node 7
support.
https://yarnpkg.com/en/
> Drop node 7 support, declare minimum versions in package.json

- app/main.dev.js
The actual nodeintegration setting is nested under webPreferences:
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions
If you set it there, Zap doesn't run, because process is no longer available in
app.html. Use of process in app.html is a barrier to other security settings -
sandbox and contextIsolation.
https://github.com/electron/electron/blob/master/docs/tutorial/security.md#checklist
> Drop ineffectual nodeintegration electron setting

- app/components/Form/PayForm.js
Because the "." of "0." is not propagated via the JS, so not in the size of
the amount string.
> Size the PayForm amount input to hold at least 2 chars

- app/components/Form/PayForm.js
- app/components/Form/PayForm.scss
This is consistent with the other field and avoids overlap formatting issues.
Fixes #174
> Move PayForm amount error message below the field

- app/components/Form/Form.scss
Fix for Issue [#180](https://github.com/LN-Zap/zap-desktop/issues/180).
When the Network tab is first opened the loader appears and has a z-index of 10. If the Pay or Request button is clicked, the form modal opens and the loader from the Network tab is still somewhat visible. This is because the form modal also has a z-index of 10.
This minor fix ups the z-index of the form modal from 10 to 20.
Generally I've done increments of 10 (0-100) or 100 (0-1000) for z-index, to keep the scale manageable. I noticed there were a few other 10s so I keep the increase to a 10 increment.
Awesome project, hope I can help out along the way!
> fix(network-loading-css): Increase z-index on Form modal

- app/components/Contacts/ClosingContact.js
- app/components/Contacts/PendingContact.js
- app/components/ModalRoot/SuccessfulSendCoins.js
- app/components/Network/ChannelsList.js
- app/reducers/info.js
- app/routes/activity/components/components/Modal/Transaction/Transaction.js
- app/utils/blockExplorer.js
- app/utils/index.js
To handle shelling out to the transaction display
This was previously done inline via electron.shell.openExternal. Consolidating
it in the utility DRYs up the code both in terms of the base url and the path
building.
Note there is also code in reducers/info.js relating to:
infoSelectors.explorerLinkBase, but it seems to be unused currently.
> Extract blockExplorer util

- .eslintignore
- .eslintrc
- app/lnd/lib/lightning.js
- app/lnd/methods/channelController.js
- app/lnd/methods/index.js
- app/notifications/index.js
- app/routes.js
- app/routes/contacts/components/Contacts.js
- app/store/configureStore.dev.js
- app/utils/index.js
- test/.eslintrc
This enables the following extensions:
"plugin:react/recommended",
"plugin:flowtype/recommended",
"plugin:import/errors",
"plugin:import/warnings",
"plugin:jsx-a11y/strict",
"plugin:promise/recommended"
And rules:
"compat/compat": "error",
"flowtype-errors/show-errors": "error",
"flowtype-errors/enforce-min-coverage": ["error", 20]
> Enable our eslint plugins, which are currently inactive

- app/app.global.scss
This is related to Issue #193.
I was looking at a better way to track z-indexes as was mentioned in [this comment](https://github.com/LN-Zap/zap-desktop/pull/183#issuecomment-357128547), and came across the bug.
After checking the react-modal issues, their accepted fix was manually adding a z-index to the modal overlay class, see [this react issue](https://github.com/reactjs/react-modal/issues/390). 
Increasing the z-index keeps the modal at the forefront and blocks clicking on the filter dropdown until the modal is closed. I added the update to app.global.scss so that the z-index would be applied to the modal across the app. Doing so seems to fix the issue in all locations where <ReactModal> is used.
Separately, I found some better ways of documenting/tracking the z-index usage via …
> fix(filter-over-modal): Add z-index to open ReactModal Overlay

- app/package.json
- package.json
- yarn.lock
To fix protocol handler vulnerability
https://electronjs.org/blog/protocol-handler-fix
> fix(electron security): Bump electron to 1.6.16

- app/reducers/transaction.js
LND’s SubscribeTransactions will announce transactions multiple times.
I haven’t looked into which circumstances this occur, but an easy fix
is to filter out the incoming transactions that we already have on record.
Fixes #317
> Only ADD_TRANSACTION if we are not already tracking the transaction

- app/lnd/lib/lightning.js
Update the list of supported cipher suites to use with openssl to
include those supported by lnd, which are defined as:
tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
See https://github.com/lightningnetwork/lnd/blob/master/lnd.go#L80-L85
Fix #324
> Update list of supported cipher suites for compatibility with lnd 0.4.0

- app/package.json
- app/yarn.lock
The impetus is to improve error reporting for GRPC connection errors,
which was introduced in 1.8.4. Security and other fixes are included
as well.
https://github.com/grpc/grpc-node/releases/tag/v1.8.4
Here's an example of the new `emitStatusIfDone` error reporting:
This error is commonly reported so additional info could be helpful: #236 #141 #234 #254 #207 #247 #324
> Bump to grpc 1.10.0

- app/package.json
- package.json
- yarn.lock
Electron 1.8 is based on Node 8.2.1. I moved the engines /
devEngines limits for node and npm to the associated versions.
https://github.com/electron/electron/releases/tag/v1.8.1
> enhance(electron): Bump to Electron 1.8.4

- app/reducers/contactsform.js
Private peers can't be acted on, so show them below the contactable peers.
> Sort the contacts form relative to peer's contactability

- app/reducers/activity.js
Because they're not pending. They're still present in the Requested view.
> Exclude expired invoices from the pending activity view

- app/package.json
- app/yarn.lock
Update grpc to v1.12.1 in order to fix issues with builds that are failing on Node 10.3.0.
Fix #404
> fix(grpc): update grpc to v1.12.1

- app/lnd/methods/walletController.js
The wallet password is defined as `bytes` in the rpc.proto spec and we are
passing it as a string, resulting in an incorrect password being set on a
new wallet and an inability to unlock an existing wallet.
Convert the wallet password to a Buffer before passing to `initWallet` and
`unlockWallet`, which is the default data type used to represent bytes in
the node grpc client. This is sures that the password is passed correctly
to lnd.
Fix #400
> fix(passwords): convert password to Buffer

- app/main.dev.js
This fixes the "LND ALREADY RUNNING" case to have the same handling as the custom LND case.
Absent this fix, Zap is stuck at the loading page on startup with local LND running.
>  Fix the local lnd already running usecase

- app/components/Form/Form.scss
- app/routes/app/components/App.js
This fixes an issue where the payment form - initiated from an external request payment link - would display under the connect dialog if that was already open. This change ensures that the payment form always displays on the top most layer.
Fix #284
> fix(pay-form): ensure payment form shows on top

- app/main.dev.js
This ensures the user can see the error, and that Zap will not be running if LND quits.
> Make LND errors visible to users via a message box

- app/package.json
- app/yarn.lock
- package.json
Update grpc to v1.12.3 in order to fix issues build issues due to the fact
that 1.12.1 doesn't contain node-pre-gyp as a bundled dependency.
See https://github.com/grpc/grpc-node/issues/365
This may be linked to the issue reported in #420 whose build logs (https://bpaste.net/show/d9de030db9ca) show the warning
> warning "grpc@1.12.1" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.
> fix(grpc): update grpc to v1.12.3

- package.json
There is an unneeded call to `concurrently` in the `npm run dev` script.
This causes things that should be output in colour (eg debug messages
when running with DEBUG=*) to not be output in colour which makes
debugging things harder than it should be.
This was in place because previously lnd was being started up externally
in the `npm run dev` script at the same time as starting up the app. But
we now use spawn from within the app to start up lnd.
The call to `concurrently` is no longer needed.
See https://github.com/LN-Zap/zap-desktop/commit/d8c5623e0131d89e1fb889eb5356fd1752bcbf12
> Remove unneeded call to concurrently

- app/main.dev.js
- package.json
- yarn.lock
Pipe lnd stdout tream through `split2` in order to ensure that each data
event contains a single line of log output.
Fix #432
> More reliable lnd log parsing

- ADVANCED.md
- app/package.json
- package.json
Remove the `install-grpc` installation step as it is redundant.
See #420
> Remove redundant install steps

- app/main.dev.js
- app/utils/log.js
- package.json
- yarn.lock
Currently, the log output is messy and hard to follow.
This PR aims to improve the application logging with a more comprehensive and flexible logging
solution. We leverage https://github.com/appscot/debug-logger for this.
We use two separate log handlers to provide separation between electron logs (namespace=`zap:main`) and and lnd logs (namespace=`zap:lnd`). This provides a good level of control over what log out put you want to see. Some examples:
Only show log messages in the `zap:main` namespace
```
DEBUG=zap:main npm run dev
```
Only show log messages of level `warn` and above
```
DEBUG_LEVEL=warn npm run dev
```
The default configuration will show `debug` and above for all messages in the `zap:*` namespace.
**BEFORE:**
**AFTER:**
> Improve log readability and allow control over what is logged

- app/components/Contacts/Network.js
Do not show the suggested nodes text block when a channel search does not return any results. Instead, in this case retain the search query input filter on the screen so that the user can go back and edit their search query.
Fix #394
> fix(channels): do not show suggested nodes on empty search

- app/utils/log.js
In some cases, multi-line log output was output at its value for the first line,
but in the trace log in following lines. For example, in this output:
```
zap:lnd  [DBG]  2018-06-17 18:30:35.051 [DBG] CRTR: New channel update applied: (*channeldb.ChannelEdgePolicy)(0xc420e74310)({ +0ms
zap:lnd  [DBG]   SigBytes: ([]uint8) (len=71 cap=71) { +0ms
zap:lnd  [DBG]   }, +0ms
zap:lnd  [DBG]   sig: (*btcec.Signature)(<nil>), +0ms
zap:lnd  [DBG]   ChannelID: (uint64) 1423834572626526208, +0ms
zap:lnd  [DBG]   LastUpdate: (time.Time) 2018-06-17 18:30:26 -0500 CDT, +0ms
zap:lnd  [DBG]   Flags: (lnwire.ChanUpdateFlag) 1, +0ms
zap:lnd  [DBG]   TimeLockDelta: (uint16) 6, +0ms
zap:lnd  [DBG]   MinHTLC: (lnwire.MilliSatoshi) 1000 mSAT, +0ms
zap:lnd  [DBG]   FeeBaseMSat: (lnwire.MilliSatoshi) 1 mSAT, +0ms …
```
> Fix lndLogGetLevel to apply the most-recent log level when none is detected

- .eslintrc
- app/lnd/index.js
- app/lnd/methods/index.js
- app/lnd/methods/paymentsController.js
- app/lnd/subscribe/index.js
- app/lnd/subscribe/invoices.js
- app/lnd/subscribe/transactions.js
- app/lnd/walletUnlockerMethods/index.js
- internals/scripts/CheckNodeEnv.js
- test/e2e/e2e.spec.js
- webpack.config.renderer.dev.js
This follow up on #436 by converting remaining `console.log` statements to use the log or throw, and enabling the `no-console` linter to prevent addition in the future.
As a bonus, this allows us to enable the full `eslint:recommended` set, which is a good baseline.
https://eslint.org/docs/rules/
> Convert remaining console statements to log or throw, enable no-console linter

- appveyor.yml
Builds are failing on on AppVeyor. This is due to the fact that those builds are targeting node v7, which is not supported (as per package.json `engines`).
This PR updates the AppVeyor config to get the builds passing again by specifying node v8 and v10 as our build targets.
Additionally, I have updated the travis.yml file to also specify node v8 and v10 for consistency (was previously specifying node v8 and latest - which could result in broken builds when node decide to release a new version of node)
Eg passing tests visible at https://ci.appveyor.com/project/mrfelton/zap-desktop
> Fix build issues on AppVeyor

- app/package.json
grpc-node provides node bindings that are specifically targeted towards
electrum. Make use of these rather than force compiling grpc on install.
See https://github.com/LN-Zap/zap-desktop/issues/420
> build: do not build grpc-node from source

- package.json
pass the `--raw` flag to concurrently so that we see the raw output of our processes, rather than a version which has been mangled by concurrently. This ensures that the webpack build output is in colour more legible.
To test: run `npm run build`:
**before:**
**after:**
> Ensure webpack build output is in colour

- .eslintrc
- package.json
Indentified via eslint-config-prettier's check script. Prettier applies standards that directly enforce these.
> lint: Remove redundant eslint rules

- CONTRIBUTING.md
Compare: https://github.com/LN-Zap/zap-desktop/blob/master/CONTRIBUTING.md
With: https://github.com/Empact/zap-desktop/blob/docs/convention-link/CONTRIBUTING.md
Note I link to: https://conventionalcommits.org/
An alternative target is: https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional
I find them both pretty difficult to parse, so if you guys have another link in mind, lmk.
> docs: add missing convention link to CONTRIBUTING page

- app/lnd/subscribe/transactions.js
Subscribe transaction on `data` was throwing a `Uncaught Exception error` because our `log.info` was being called on the `LND` object
> fix(log): fix the uncaught exception by calling info on log not lnd

- CONTRIBUTING.md
Add some additional documentation on our git hooks to describe how to enable them and what they do.
> Improve documentation on git commit hooks

- app/api/index.js
If we catch these errors and resolve to the error itself, then `await` for that
function resolves to the error value rather than throws. Because no api currently
handles the associated errors, it is better to be noisy about these errors, by
throwing rather than returning the error object.
> fix: Don't catch api/index errors

- app/components/Activity/InvoiceModal.js
- app/components/Activity/PaymentModal.js
- app/components/Activity/TransactionModal.js
- app/routes/activity/components/components/Invoice/Invoice.js
- app/routes/activity/components/components/Payment/Payment.js
- app/routes/activity/components/components/Transaction/Transaction.js
- package.json
- yarn.lock
We don't use `moment-timezone` at all. This can be replaced with `moment` for a smaller memory footprint.
This PR removes `moment-timezone`
Shaves another 176.88k of final renderer.prod.js bundle size.
**before:**
**after:**
> Do not bundle moment-timezone that we don't use 

- app/reducers/transaction.js
We shouldn't be generating `p2pkh` addresses. We were when a new transaction was received. This switches to generating a `np2wkh` address
> fix(p2pkh): generate np2wkh instead of p2pkh

- webpack.config.base.js
More work to reduce the size of our bundle - this helps speed up the initial load time of the app.
We aren't using moment locales, yet they are being bundled with our app and causing significant bloat.
Removing these shaves an additional 136.63k of our final renderer.prod.js bundle size, bringing it down from 1.12mb to just under 1mb.
More info:
- https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
- https://medium.com/@michalozogan/how-to-split-moment-js-locales-to-chunks-with-webpack-de9e25caccea
**before:**
**after:**
> Do not bundle moment locale data data that we don't use

- app/api/index.js
- app/app.html
- app/main.dev.js
- package.json
- webpack.config.renderer.dev.js
- webpack.config.renderer.prod.js
- yarn.lock
Currently we hardcode our CSP directly into `app.html`. The current policy is geared towards development - it allows loading resources from localhost, inline scripts, and scripts that contain `eval`. Some of these settings are needed for our development builds, but not for production.
In this PR I have reworked things slightly to enable us to have differing CSP's for development vs production builds as well as more restrictive policy for development builds.
- First, we switch to using [`HtmlWebpackPlugin`](https://webpack.js.org/plugins/html-webpack-plugin/) to generate our final html file so that we can dynamically inject scripts into the page at compile time.
- We refactor the `app.html` page a little to remove all inline scripts and move these back to the relevant webpack configs.
- …
> Implement a more restrictive Content Security Policy for production builds

- resources/lnd.conf
Commented out as testnet is still our default.
> enhance(mainnet conf): add an lnd.conf entry for bitcoin.mainnet

- app/components/Contacts/Network.js
Before our conditionals in `Network.js` were looking at `channels` which does not account for `pendingChannels`. So the bug was that a user with no channels would open their first one and not see it pending. This fixes our conditionals by looking at the `currentChannels` list
> fix(channel-list): change the logic to look at the currentChannels

- app/components/Contacts/Network.js
We weren't using `currencyName` in the channel details. This fixes that
> fix(channel-details): use currencyName

- app/components/Contacts/Network.js
- app/reducers/channels.js
`waiting_close_channels` is a fairly new property of the `pendingChannels` object returned by `LND`. any channels that were returned in this list were:
1) displayed as `offline`
2) not included in the `Closing` filter in the channels list
This PR just accounts for `waiting_close_channels` and fixes both issues above
> fix(waiting_close_channels): account for waiting_close_channels

- app/lnd/index.js
- app/main.dev.js
If there is a problem initializing the lnd gRPC connection, show an error message to the user and quit the app.
This is an extraction of some of the changes from https://github.com/LN-Zap/zap-desktop/pull/479
> fix(grpc): handle gRPC startup issues

- app/main.dev.js
Fix an incompatibility between electron 2.x and devtools by patching the electron webRequest handler.
See https://github.com/electron/electron/issues/13008#issuecomment-400261941
Fix #490
> fix(devtools): patch webrequest to fix devtools

- app/main.dev.js
Add some logging so that we can see how long it takes from starting up the app until the user is first able to interact with it.
> Add logging to show boot time

- .gitignore
- .huskyrc
- CONTRIBUTING.md
- package.json
- yarn.lock
Make the linters run automatically for all users. This helps ensure that all
contributions adhere to our practices.
> style(husky hooks): drop opt --in from husky hooks

- package.json
It looks like we were a little hasty in #492 as rimraf is used directly within package.json in the `flow-typed` script and so it needs to remain as a dev dependency.
See https://github.com/LN-Zap/zap-desktop/pull/492
> Add missing rimraf dependency

- app/components/Contacts/ContactModal.js
- app/components/Contacts/Network.js
- app/components/Form/Pay.js
- app/lnd/methods/channelController.js
- app/reducers/channels.js
- app/reducers/contactsform.js
- app/reducers/payform.js
- app/routes/activity/components/components/Payment/Payment.js
- package.json
We only use 3 functions from lodash - `find`, `filter` and `isEmpty` - all of which can be done easily with straight ES6.
This PR removes lodash.
Shaves a nominal 34.57k of final renderer.prod.js bundle size.
**before:**
**after:**
> Remove lodash dependency

- app/main.dev.js
It looks like there was a typo in the fix for https://github.com/LN-Zap/zap-desktop/pull/491. This PR corrects it.
> Fix devtools electron compatibility issues

- package.json
- yarn.lock
Electron v2.0.3 was released a few days ago which fixes a number of minor bugs which are likely to affect us. There is also one fix which is marked as a security fix
See https://github.com/electron/electron/releases/tag/v2.0.3
Also, update electron-builder which has had quite a few nice updates since the version we had installed.
Have tested with `npm run dev`, `npm start`, and via a package built with `npm run package` and everything appears to work as expected.
> Update electron and electron builder to latest versions

- .travis.yml
- appveyor.yml
Unset the `ELECTRON_DISABLE_SECURITY_WARNINGS` environment variable which was being used to disable the security checks when testing the app on ci. This is no longer needed now that we have a more strict Content Security Policy when the app runs in production mode.
See https://github.com/LN-Zap/zap-desktop/pull/456
> Enable electron security checks on travis/appveyor

- app/main.dev.js
- app/menu.js
Wait until the `dom-ready` event has fired before opening up the devtools window. This prevents the following error message showing up multiple times when the app starts in dev mode:
> Extension server error: Operation failed: : has no execution context
See https://github.com/electron/electron/issues/12438
Fix #499
> Fix devtools startup error messages

- app/components/Contacts/Network.js
We were looking for the wrong property on the channel object here which was resulting in closing channels being displayed as offline. We want to be looking for `limbo_balance`.
> fix(channels): correct property for waiting_close_channels object

- app/components/Onboarding/Onboarding.js
Concerning issue #415. Now users can't proceed when password is empty.
> fix(onboarding-empty-pass): add empty password validation

- ADVANCED.md
The anchor links on the Advanced Usage page weren't working in Chrome on Ubuntu. Making them lowercase and removing the parentheses seems to solve the problem.
> Fix anchor links in docs

- app/components/Onboarding/ConnectionDetails.js
- app/components/Onboarding/ConnectionDetails.scss
- app/components/Onboarding/Onboarding.js
- app/containers/Root.js
- app/lnd/config/index.js
- app/lnd/index.js
- app/lnd/lib/lightning.js
- app/lnd/lib/neutrino.js
- app/lnd/lib/util.js
- app/lnd/lib/walletUnlocker.js
- app/package.json
- app/reducers/ipc.js
- app/reducers/onboarding.js
- app/yarn.lock
- app/zap.js
- package.json
- yarn.lock
If you try to connect to a custom LND instance with some credentials that are incorrect, we currently show a native error dialog and then quit the app.
This PR improves this so that we instead show the relevant errors to the user and allow the user to correct and try again.
eg:
> feat(grpc): lnd connection error recovery

- app/components/Onboarding/Onboarding.js
- app/reducers/onboarding.js
This PR fixes:
- It was possible to proceed with:
Password: `1234`
Confirm Password: `12`
- It was also possible to proceed with filled in Password but Confirm Password empty.
I hope that's the last PR related to #415 :)
> fix(onboarding-password-bug): add more password validation

- app/zap.js
Fix a race condition that could cause the app to think that it is still syncing even after it has completed and as a result being stuck reporting 100% syncing during the onboarding process.
`startGrpc` can take some time to fully establish and verify that the connection is set up as we wait for a successful result from a call to `getInfo`.
Previously, we would send the `lndSyncing` message to the app only after `startGrpc` was complete. However, if the syncing process had actually completed before `startGrpc` then we would first notify that syncing had completed, only to then notify that it had started after it had already completed.
In this fix, we notify the app of `lndSyncing` immediately after the wallet has been unlocked.
> fix: ensure onboarding completes after syncing

- app/api/index.js
- app/reducers/lnd.js
- webpack.config.renderer.dev.js
- webpack.config.renderer.prod.js
Call out to 3 different block explorers to get the current block height and use the result from whichever responds quickest.
Fix #463
> Fetch block height from multiple block explorers incase one is unavailable

- app/components/Onboarding/Syncing.js
- app/components/Onboarding/Syncing.scss
- app/containers/Root.js
- app/lnd/lib/neutrino.js
- app/reducers/ipc.js
- app/reducers/lnd.js
- app/zap.js
This patch fixes some issues with the sync process. The parsing of lnd log entries where we calculate the current sync progress has been moved from the renderer back to the main process and updated to improve it's accuracy.
We now call dispatch a call to `fetchInfo` as soon as the gRPC connection has been established so that we get the node info as early as possible, and we defer showing the syncing screen until we are sure that a grpc connection has been established and syncing is in progress.
These enable us to provide better feedback to the user and prevent further race conditions that I have observed.
As a bonus, we show the user some more information about the current sync progress.
> Improve feedback to users during sync process

- app/utils/log.js
Reduce our loggers to `info` level by default to reduce the amount of noise that gets output on the console.
> Reduce default log level to info to reduce terminal noise

- .eslintrc
- app/lnd/lib/neutrino.js
When matching log lines, switch on the regex match rather than an
excerpt, so that there are never any false positives.
Note this allows conditional assignment within parens as well.
> fix: improve lnd log line matching

- app/api/index.js
- app/components/Onboarding/Syncing.js
- app/containers/Root.js
- app/lnd/lib/neutrino.js
- app/lnd/lib/util.js
- app/reducers/ipc.js
- app/reducers/lnd.js
- app/routes/app/containers/AppContainer.js
- app/zap.js
- package.json
- webpack.config.renderer.dev.js
- webpack.config.renderer.prod.js
- yarn.lock
Fetch the current block height from multiple block explorers early on in the sync process. This ensures that we get the correct block height in the case where our BTCd node is still mid way through syncing. Do this in the main process rather than in the render process.
> Ensure that we fetch the correct block height in the case where BTCd is mid way through syncing

- app/components/Onboarding/Syncing.js
- app/components/Onboarding/Syncing.scss
- app/containers/Root.js
- app/lnd/lib/neutrino.js
- app/reducers/ipc.js
- app/reducers/lnd.js
- app/zap.js
Handle the case were the Neutrino backend BTCd node is still synchronising the blockchain as LND is not able to start syncing until the BTCd node that it is connected to is fully synced.
In this case, we display a message to the user indicating that we are waiting for peers. If it takes more than 10 seconds that generally indicates that the btcd node is quite far behind (eg, it has been restarted and is doing a full/fresh sync) and so after 10 seconds of waiting we advise the user that it could take some time.
This PR corrects a bug from https://github.com/LN-Zap/zap-desktop/pull/529 where we calculate the current block height incorrectly. In that PR, we incorrectly assumed that the message `Syncing to block height X` from lnd would tell us the current block height however it actually …
> Handle case where BTCd node is not fully synced with the blockchain

- app/lnd/methods/index.js
Use `info` log level when logging successful results.
Previously we were logging successful results as errors.
> Don't log successful results from lnd as errors

- app/components/Activity/TransactionModal.js
It seems that the fix in https://github.com/LN-Zap/zap-desktop/pull/542 for #539 was the wrong way round (sent showing as received, received showing as sent). This reverses it.
Fix for #539
> Don't show sent for received tx

- app/reducers/onboarding.js
- Set the default connection type to `local`
- Set the default for autopilot to `true`
> Ensure there are sensible default values for onboarding screens

- ADVANCED.md
I tried running "npm run test" as suggested at the end of these instructions and got a bunch of errors saying "The main process is not built yet. Build it by running "npm run build-main" so just making a note of that in the docs
> Update docs to suggest building before running tests

- app/components/Contacts/Network.js
Ensure that the channel filter shows instead of the suggested nodes list when an empty channel filter is selected.
Fix #507
> Show channel filter when there is an empty active filter

- package.json
Windows build is failing on this line with:
```
> node --trace-warnings -r babel-register ./node_modules/.bin/webpack-serve --config webpack.config.renderer.dev.js
C:\Users\user\Documents\zap-desktop\node_modules\.bin\webpack-serve:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
^^^^^^^
SyntaxError: missing ) after argument list
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
at Module._extensions..js (module.js:663:10)
at Object.require.extensions.(anonymous function) [as .js] (C:\Users\user\Documents\zap-desktop\node_modules\babel-register\lib\node.js:152:7)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at …
```
> fix(windows): reference webpack-serve js directly

- app/containers/Root.js
I saw a warning that a required argument to NewAezeedPassword was not
present and tracked it back to here.
updateAezeedPasswordConfirmation is a function and should be sourced
via the dispatchProps, while the aezeedPasswordConfirmation holds the
value.
> fix: aezeedPasswordConfirmation propagation

- app/components/Contacts/ConnectManually.scss
- app/components/Contacts/SubmitChannelForm.scss
- app/components/Form/Pay.scss
- app/components/Form/Request.scss
White on yellow presents accessibility challenges and should be avoided. Change the white on yellow used in highlighted buttons for a darker colour against the yellow background.
Fix #356
**Before:**
**After:**
> fix(accessibility): don't use white on yellow text

- app/components/Form/Pay.scss
- app/components/Form/Request.scss
Ensure that the currency selector dropdown on the pay/request form shows ontop of other elements on the page to ensure that the full area of the dropdown is clickable.
(currently it is partially hidden behind the errors message divs.
> fix(ui): increase currency selector z-index

- app/routes/activity/components/components/Activity.scss
- app/routes/activity/components/components/Invoice/Invoice.js
- app/routes/activity/components/components/Payment/Payment.js
- app/routes/activity/components/components/Transaction/Transaction.js
Currently, it's not immediately obvious which transactions are on-chain vs off-chain when scanning the activity list.
Add an icon that shows the activity type in the activity list to help users clearly distinguish between on-chain and off-chain transactions.
**Before:**
**After:**
> feat(ui): show activity type icon in activity list

- app/components/Contacts/Network.js
- app/reducers/channels.js
This changes the Network component conditional for showing channels suggestions to `!(loadingChannelPubkeys.length || pending_open_channels.length || channels.length)` from `!((loadingChannelPubkeys.length || currentChannels.length || channels.length || searchQuery.length)`
The theory is we should show search and selection whenever any channels exist or are being looked up, regardless of whether search input is supplied or current channels are selected.
>  fix: don't show channel suggestions if pending channels exist

- app/components/Contacts/Network.js
Prevents the display of an unwanted "0" by ensuring that conditional uses an actual boolean value.
> fix: ensure conditional display uses boolean

- app/reducers/onboarding.js
It is more common for new users to create a new wallet than to import an existing one. Make the "create new wallet" option the default selected value in the onboarding process.
> fix(onboarding): default to create new wallet

- app/lnd/lib/lightning.js
- app/lnd/lib/walletUnlocker.js
- app/zap.js
This avoids expanding the acceptable cipher suites in general lnd connections
relative to the possibility of BTCPay server being involved.
> chore(security): tailor GRPC_SSL_CIPHER_SUITES to the connection type

- app/components/Onboarding/FormContainer.js
- app/components/Onboarding/FormContainer.scss
Add a help link to our onboarding forms that links to our Desktop "Getting Started" tutorial in case anyone gets stuck
> feat(help): add help link to tutorial

- app/reducers/transaction.js
LND errs on the side of providing redundant transaction reports, so
we should filter before issuing notifications.
> fix: only notify if we have not seen the transaction before

- app/components/Onboarding/ConnectionDetails.js
- app/components/Onboarding/ConnectionDetails.scss
Don't use field placeholders for form field help text as this is only visible when the form field is empty. Instead.
This PR moves the help text to just below the fields so that it is always visible to the user in order to help them ensure they are entering the correct values. Also, I have added example values so that the user knows what format we are expecting the values in (we get a lot of people asking what exactly they should enter in slack)
Here is decent article that highlights why placeholders are bad in many cases https://uxdesign.cc/alternatives-to-placeholder-text-13f430abc56f. Using for help text presents a usability issue.
**before:**
(no indication of what the user should be entering is visible once the user has started typing)
**after:**
(help text is always visible)
> fix(onboarding): improve custom connection form field help text

- app/lnd/config/index.js
- internals/scripts/fetch-lnd-for-packaging.js
- package.json
- webpack.config.renderer.prod.js
- yarn.lock
Use `lnd-binary` to download the correct mac/windows/linux lnd binary into the relevant location in the resources directory as part of the install process.
See https://github.com/mrfelton/lnd-binary
This has a couple of advantages:
1. We make the installtion process easier for users
2. We ensure that users always have the version of lnd that we expect/requite
3. `lnd-binary` takes extra steps to verify the checksum of the downloaded binary to ensure its integrity
4. downloaded binary is cached by npm so future builds are faster
In this version of the PR, I download the binary for all 3 supported operating systems, which is useful for packaging purposes. However, we might want to instead only download the one for the users current platform. Thoughts?
> build: auto download lnd-binary on install

- .gitignore
- README.md
- package.json
- yarn.lock
We have a test suite, so we should have code coverage reports to go with it.
Coverage reports make it easy to see what is and isn't covered by tests and encourages developers to write tests for new and existing code.
This PR:
- generates test coverage reports whenever tests are run (output to `.coverage` directory)
- provides the command `yarn coverage` which will open up an html version of the test coverage report (see screenshot below)
- posts test coverage data to coveralls (eg https://coveralls.io/github/mrfelton/zap-desktop) at the end of every successful build on travis
- adds a status badge to the project homepage to provide visibility into he current test coverage of the project (I also added a couple of other useful status badges).
> Generate code coverage reports

- app/reducers/channels.js
Ensure that the currently active unit of account is honoured when opening a new channel.
Fix #523
Also see #604
> fix: honour currency when opening channel

- app/components/Onboarding/Onboarding.js
- app/containers/Root.js
- app/lnd/walletUnlockerMethods/index.js
- app/reducers/onboarding.js
Improve the wording of the message users see when they go through onboarding and we detect that they already have an existing wallet
Addresses:
https://github.com/LN-Zap/zap-desktop/issues/602
https://github.com/LN-Zap/zap-desktop/issues/598
https://github.com/LN-Zap/zap-desktop/issues/597
https://github.com/LN-Zap/zap-desktop/issues/594
https://github.com/LN-Zap/zap-desktop/issues/591
**Before:**
**After:**
> fix(onboarding): improve existing wallet found message

- app/lnd/lib/lightning.js
- app/lnd/lib/walletUnlocker.js
- package.json
- yarn.lock
Fix grpc depreciation warning from `grpc.load`:
> grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Fix #621
> refactor(grpc): use @grpc/proto-loader

- app/containers/Root.js
- app/lnd/lib/neutrino.js
- app/reducers/ipc.js
- app/reducers/lnd.js
- app/reducers/onboarding.js
- app/zap.js
This PR cleans up some of the naming of methods and events in relation to the Neutrino client to make them more consistent and descriptive.
I'd like to try to get this in before starting work on https://github.com/LN-Zap/zap-desktop/issues/620 as this will make it easier to do a cleaner solution for that.
> refactor(neutrino): more consistent naming in Neutrino class

- app/lnd/index.js
- app/lnd/lib/lightning.js
- app/lnd/lib/util.js
- app/lnd/subscribe/channelgraph.js
- app/lnd/subscribe/index.js
- app/lnd/subscribe/invoices.js
- app/lnd/subscribe/transactions.js
- app/lnd/walletUnlockerMethods/index.js
- app/main.dev.js
- app/reducers/channels.js
- app/reducers/ipc.js
- app/reducers/onboarding.js
- app/reducers/requestform.js
- app/zap.js
- package.json
- yarn.lock
The standard approach on Darwin is to keen applications running when the window is closed. Clicking the apps icon again in the doc should bring back the application window.
This changeset refactors things to properly handle this. It will keep Zap and lnd running in the background when the main application window is closed. The gRPC connection is closed out when the window is closed and a new gRPC connection is established again once it has been reopened. Quitting the app will stop both the app and lnd.
I think there are further improvements that can be made to the user experience here as part of https://github.com/LN-Zap/zap-desktop/issues/520
> feat(ux): keep app running when main window closed

- app/components/Onboarding/Syncing.js
- app/containers/Root.js
- app/lib/lnd/neutrino.js
- app/lib/zap/controller.js
- app/reducers/ipc.js
- app/reducers/lnd.js
- package.json
- resources/lnd.conf
- resources/rpc.proto
- test/unit/lnd/neutrino.spec.js
- yarn.lock
In an ideal world, lnd would make nightly snapshots available that we could download. However currently they don't do this so I have created our own solution that we can use to compile and publish lnd binaries.
I have created a fork of the lnd repo at https://github.com/LN-Zap/lnd on which I have added support for [goreleaser](https://goreleaser.com/).
You can see the changes that enable this here:
https://github.com/lightningnetwork/lnd/compare/master...LN-Zap:zap/canary-releases?expand=1
With this, we can easily publish a new release with a simple call to `./canary.sh`. This will build lnd for all of the platforms and targets that we support and then create a github release and publish the binaries to it.
For example, here is the release that I have just created from the current master …
> feat(lnd): update BTCD and LND to latest versions

- app/lib/zap/controller.js
On darwin, we keep the app running and just hide it when the window is closed as that is the standard convention. On linux and windows the app should be quit when the window is closed.
This resolves an issue where on linux/windows the app would remain open when the window is closed, with no way to properly quit it short of doing a force quit.
> fix(app): quit when window closed on non-darwin

- app/routes/activity/components/components/Invoice/Invoice.js
- app/routes/activity/components/components/Payment/Payment.js
- app/routes/activity/components/components/Transaction/Transaction.js
Fix a bug where we were showing transaction amounts as transaction fee.
Fix #662
> fix(activity): correct tooltips in activity log

- app/reducers/invoice.js
Fix a bug where we were incorrectly notifying users that an invoice had been successfully paid when it had actually just been created.
Fix #670
> fix(invoice): only notify on settled invoices

- app/lib/lnd/neutrino.js
The lnd sync process doesn't currently handle multiple btcd connections well. Remove the alternate btcd hosts for testnet and mainnet.
See https://github.com/lightningnetwork/lnd/issues/1752
> fix(lnd): only connect to single btcd host

- app/lib/lnd/neutrino.js
During the sync process there are log message that relate to syncing filters and filter headers. This fixes an issue where we were parsing messages about syncing filters as if they were filter headers, which would cause the progress indicator to jump around during the middle of the sync process due to it thinking that more filter headers had been synced than was actually the case.
> fix(lnd): don't treat filters as filter headers

- app/lib/lnd/config.js
- app/lib/lnd/lightning.js
- app/lib/lnd/subscribe/channelgraph.js
- app/lib/lnd/subscribe/invoices.js
- app/lib/lnd/subscribe/transactions.js
- app/lib/lnd/util.js
- app/lib/zap/controller.js
- app/main.dev.js
- test/e2e/e2e.spec.js
- test/unit/__mocks__/electron.js
- test/unit/lnd/lightning.spec.js
- test/unit/lnd/lnd-config.spec.js
- test/unit/lnd/neutrino.spec.js
Do not try to send incoming data from GRPC streams to the main window after the window has been closed.
Fix #677
Things to test:
**mac:**
**windows:**
> fix(grpc): ensure full disconnect on window close

- app/lib/lnd/neutrino.js
- app/lib/zap/controller.js
- test/unit/lnd/neutrino.spec.js
If lnd unexpectedly exists, show the user the last error message reported by lnd in order to help diagnose issues.
See #674
> feat(lnd): show error message if lnd exits

- resources/lnd.conf
Disable the REST interface which by default runs on port 8080 so as to avoid conflicts with users that are using port 8080 for other things. We don't use the REST interface so we don't need to expose it.
Fix #674
>  fix(lnd): disable lnd REST interface on port 8080

- app/reducers/onboarding.js
Ensure that the loading bold graphic shows whist the seed for a new wallet is being generated. This provides a smoother user experience and prevents users from being able to initiate actions through the UI when they shouldn't be able to.
> fix(ux): show loading bolt while seed is generated

- resources/lnd.conf
This PR adds private channels and minconfs=0 to our autopilot configuration.
We don't want our light client users advertising channels because they are not likely to be reliable nodes with high uptime. Fixes #681.
**NOTE: This PR can only be merged _after_ we update to LND master. These new flags aren't supported with the LND that is currently packaged and LND will shut down on start because of it at the moment. (Customized my binary path to test this works)**
> feat(autopilot): enable private and minconfs=0

- app/components/Onboarding/ReEnterSeed.scss
- app/components/Onboarding/RecoverForm.scss
Due to differences in font rendering cross-platform set line-height to ensure consistent experience on mac/linux.
Fix #665
**before:**
**after:**
> fix(ui): increase line-height in seed reentry form

- app/components/Activity/InvoiceModal.js
- app/lib/utils/btc.js
- app/reducers/invoice.js
- app/routes/activity/components/components/Invoice/Invoice.js
Settled invoices show the amount paid by the payee instead of the requested
value from the invoice. This involves using an updated version of the lnd rpc
protocol.
This is in response to issue #654.
amt_paid is exposed to users via invoice.finalAmount, which is constructed
via a new invoice decorator.
> fix(invoice-amt-paid): settled invoices show amt_paid

- package.json
- yarn.lock
This resolves an issue with jest that was preventing tests from completing on windows environments and is the reason that lots of our builds on appveyor have been failing.
See facebook/jest#6639
> chore(deps): update jest to v23.5.0

- .flowconfig
We're missing flow type definitions for grpc. This is due to the fact that it is installed in `app/node_modules` and not `node_modules`
```
$ yarn flow
yarn run v1.9.2
$ flow
Launching Flow server for /Users/tom/workspace/zap-desktop
Spawned flow server (pid=76836)
Logs will go to /private/tmp/flow/zSUserszStomzSworkspacezSzZap-desktop.log
Monitor logs will go to /private/tmp/flow/zSUserszStomzSworkspacezSzZap-desktop.monitor_log
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ app/lib/lnd/lightning.js:3:18
Cannot resolve module grpc.
1│ // @flow
2│
3│ import grpc from 'grpc'
4│ import { loadSync } from '@grpc/proto-loader'
5│ import { BrowserWindow } from 'electron'
6│ import LndConfig from './config'
```
Currently, in our `.flowconfig` file we …
> build(flow): include node_modules in flow config

- app/lib/zap/controller.js
Start the app, hit `cmd+r` twice, then try to progress through the onboarding process. You will get a `transition is invalid in current state` error.
The `onOnboarding` state transition handler only fires if you are entering the `onboarding` state from another state. If you are already in the `onboarding` state it does not fire when the `startOnboarding`
event is initiated. By contrast, `onStartOnboarding` always fires when `startOnboarding` is run.
Ensure that IPC listeners are only registered once when transitioning to the `onboarding` state from another state.
> fix(wallet): ensure clean state after refresh

- app/lib/lnd/subscribe/channelgraph.js
- app/reducers/transaction.js
- test/unit/reducers/__snapshots__/transaction.spec.js.snap
- test/unit/reducers/transaction.spec.js
Make a call to fetch the updated balance and channels list whenever a new transaction is detected.
Fix #579
> fix(wallet): fetch updated channels and balance after a new transaction

- app/lib/lnd/methods/channelController.js
- app/reducers/channels.js
- test/unit/reducers/channels.spec.js
This PR we make sure that if a user of ours is using neutrino that we flag their channels as private when they manually open them. Reason for this is because light consumer clients are not expected to have high uptime. 
However we cannot hardcode channels as private every time because we do support more power users driving their remote nodes or BTCPay Server with Zap. So we only flag channels as private if the `activeConnection` is `local`.
Addresses #681
> fix(channels): neutrino clients manual channels flagged private

- app/components/AmountInput/AmountInput.js
- app/components/AmountInput/index.js
- app/components/Contacts/SubmitChannelForm.js
- app/components/Form/Pay.js
- app/components/Form/Request.js
- app/routes/app/containers/AppContainer.js
- test/unit/components/AmountInput.spec.js
- test/unit/components/Form.spec.js
- test/unit/components/Form/Pay.spec.js
- test/unit/components/Form/Request.spec.js
Add a new `AmountInput` component to render an input field for entering bitcoin denominated amounts. Has special handling for bitcoin / sats / bits to ensure that only valid amounts can be entered and that the formatting looks visually correct.
Use the new `AmountInput` component throughout the wallet.
Credits to @DataCourier who provided an initial implementation of this in https://github.com/LN-Zap/zap-desktop/pull/322
Fix #682
In order to reproduce the issue that this PR addresses:
1. Open up the request or pay forms
2. With the currency set to Bitcoin, enter an invalid amount such as `0.00000000001`
3. Change the currency to bits or satoshi
You should see that the entire UI goes black and the only way out is to restart/reload the app. With this PR in place, it should be impossible to …
> feat(components): add new AmountInput component

- app/lib/lnd/lightning.js
- app/lib/zap/controller.js
Lnd doesn't currently do a graceful shutdown when a `SIGTERM` is issued. To ensure a graceful shutdown, call `stopDaemon` on the gRPC interface prior to terminating lnd.
See
- https://github.com/lightningnetwork/lnd/issues/1028
- https://api.lightning.community/#stopdaemon
> fix(lnd): ensure graceful shutdown

- app/components/Contacts/Network.js
Due to different API results our `displayNodeName` function wasn't comparing the closing channels pubkey when searching for the node and its alias, resulting in closing channels being listed by their pubkey and not their alias. This PR fetches the pubkey correctly if the channel is a closing one so that closing channel UX is better and closing channels are listed by their pubkey
> fix(network): ensure alias for closing channels

- app/components/Contacts/Network.js
We had `satoshisToBtc` hardcoded for our network (channel) balance. This updates it to use the `Value` component to ensure it displays correct balance depending on if the user is viewing in `sats`, `bits` or `btc`
> fix(network): ensure accurate btc balance

- app/lib/lnd/config.js
- app/lib/lnd/neutrino.js
- package.json
- resources/rpc.proto
- test/unit/lnd/lnd-config.spec.js
This updates LND to the latest commit from master. This was incompatible with the version of BTCD that we were running so I have also updated `testnet1-btcd.zaphq.io` and `testnet2-btcd.zaphq.io` to the latest version of BTCD (which got several updates in the last week). I verified first that this new version of BTCD was still compatible with the old version of lnd that we were previously running so as not to impact users of 0.2.1.
> feat(lnd): update lnd to v0.4.2-beta-913-g26f68da5

- app/components/GlobalError/GlobalError.js
- app/components/GlobalError/GlobalError.scss
- app/lib/utils/userFriendlyErrors.js
- test/unit/utils/userFriendlyErrors.spec.js
I know the lnd team is working on improving their error messages but I think zap would really benefit by having its own set of user-friendly error messages. You may understand what `Error: 11 OUT_OF_RANGE: EOF` means if you've been hands on with `lnd`, but the average user is left confused by seeing that after the failure of a channel connection - I sure was.
> feat(errors): create a util for making error messages more user-friendly

- app/lib/lnd/methods/channelController.js
- app/lib/lnd/methods/index.js
- app/lib/lnd/methods/invoicesController.js
- app/lib/lnd/methods/networkController.js
- app/lib/lnd/methods/paymentsController.js
- app/lib/lnd/methods/peersController.js
- app/lib/lnd/methods/walletController.js
- app/lib/lnd/push/closechannel.js
- app/lib/lnd/push/openchannel.js
- app/lib/lnd/push/subscribeinvoice.js
Update a number of places in the lnd service wrapper where a call error was being resolved after it was already rejected.
> fix(lnd): do not resolve after rejecting

- app/reducers/activity.js
- app/routes/activity/components/Activity.js
- app/routes/activity/components/Activity.scss
- app/routes/activity/containers/ActivityContainer.js
Adds a toggle button to show/hide expired payment requests (invoices). The button is only displayed on the 'All' and 'Requested' tabs. 
TODO: The UI needs to be improved as discussed in slack with @JimmyMow 
A few options I've thought of:
- display an icon in the activity header next to Refresh and change the word 'Refresh' to an icon as well.
- display a footer positioned absolute to the bottom of the activity list, similar to the My Network search field. Inside of the footer on the left or right, display a toggle switch and 'Show Expired Requests' label
Suggestions and nitpicks are welcome on this first PR.
Fixes #521
> feat(toggle-expired-requests): add button to show/hide expired requests

- app/components/Wallet/Wallet.js
- app/components/Wallet/Wallet.scss
- app/reducers/payment.js
- app/routes/activity/containers/ActivityContainer.js
- test/unit/reducers/__snapshots__/payment.spec.js.snap
In this commit we add a 60 second timeout when paying a LN invoice. If the payment doesn't successfully route after 60 seconds we display an error. 
Addresses #715, #637 
New payment success UX:
New payment fail UX:
> feat(payment): add 60 second payment timeout

- app/lib/lnd/methods/invoicesController.js
- app/reducers/invoice.js
- test/unit/reducers/__snapshots__/activity.spec.js.snap
We currently do not flag for private channel routing hints when we create invoices. We need to if the user is a light client because all channels will be private. This commit checks which type of client is using zap and flags invoices to add private hints if it's a light client.
Fix for #725
> feat(invoice): add priv routing hints for light clients

- app/components/Contacts/Network.js
We currently hard code our channel explorer links to the channel point (funding transaction). For closing channels this isn't really relevant and bad UX. This PR updates the logic for the explorer link: if the channel has a closing tx (it's in the process of being closed) then let's link to that, otherwise the funding tx is fine 👍
> fix(channels): closing channels link to closing_txid

- app/lib/lnd/lightning.js
- app/lib/lnd/walletUnlocker.js
Configure gRPC to use Numbers to represent long values instead of Strings. This ensures that we can do accurate handling of numerical values.
This ensures that numbers are actually numbers and not strings so a check like `if (val) { ... }` would will give expected results.
For example:
```
if (0) { echo "something" }
=> undefined
```
but 
```
if ("0") { echo "something" }
=> "something"
```
(`"0"` is a truthy value, whilst `0` is not)
Fix #727
Bux fix
> fix(grpc): use Numbers to represent long values

- app/package.json
- package.json
This bumps the version to 0.2.2-beta which will trigger electron-builder to start publishing builds to the 0.2.2-beta release draft.
> chore(version): bump to 0.2.2-beta

- app/routes/activity/components/Activity.js
Due to a recent change in the way that we handle numeric data from gRPC we need to be explicit when checking for unset/null values.
Wallet GUI missing for new wallets with a zero balance.
Create and sync new wallet and verify that the UI shows correctly.
Bug fix
> fix(ui): show wallet once balances are loaded

- app/components/Activity/InvoiceModal.js
- app/components/Activity/InvoiceModal.scss
- app/components/Onboarding/Syncing.js
- app/components/Onboarding/Syncing.scss
- app/components/Wallet/ReceiveModal.js
- app/components/Wallet/ReceiveModal.scss
Fix for a more standard QR code color scheme for compatibility with QR scanners. Changed background color to white, and foreground color to dark. Added 2 pixel wide css border. Changes applied to wallet, invoice and syncing js and scss files (where the the element is invoked). Able to test wallet and invoice QR codes with my Android device, but not lnd syncing.
Fix for #675 
Scanning with Android barcode scanner and Eclair wallet now works.
Minor UI changes.
> fix(qrcode): re-invert QR colors and 2 px border for maximum compatibility

- app/components/Wallet/ReceiveModal.scss
- app/routes/app/containers/AppContainer.js
Show the node public address if known to make it easier to share node
details with other users. Add the data in both the Node address text
field as well as the node address QR code.
There is currently no way to see the public node address including the IP address and port.
1. Start the internal node and verify that the node address shows ok
2. Connect to a custom node with external ip address set and verify that the ip address and port are included in the node address (text and QR code)
New feature
> feat(wallet): show node public address if set

- app/lib/zap/controller.js
Ensure that a failed lnd connection attempt prevents the FSM from changing state by moving the connect handlers to the `onBefore<TRANSITION>` lifecycle events.
See https://github.com/jakesgordon/javascript-state-machine/blob/master/docs/lifecycle-events.md#cancelling-a-transition
Fix for #739
1. Start zap
2. select custom mode
3. enter invalid connection details
4. proceed to connect
5. after returning to the connect form, submit for a second time with invalid credentials
Bug fix
> fix(fsm): ensure lnd connect before state change

- app/components/Form/Pay.js
This PR fixes a bug where Zap crashes when a user tries to send to an on-chain address
When entering an on-chain address into the Pay form the Pay form goes blank. This is because it is trying to focus on `amountInput` which does not exist.
You can reproduce the issue on master by simply pasting an on-chain address in the pay form and watch the app crash. 
If you checkout to this PR and paste an on-chain address the app acts normally.
- [] I have added tests to cover my changes where needed.
- [] All new and existing tests passed.
> fix(pay): dont focus on value input

- app/lib/lnd/lightning.js
- app/lib/lnd/methods/index.js
- app/lib/lnd/subscribe/channelgraph.js
- app/lib/lnd/subscribe/invoices.js
- app/lib/lnd/subscribe/transactions.js
- app/lib/lnd/walletUnlocker.js
- app/lib/lnd/walletUnlockerMethods/index.js
- app/lib/zap/controller.js
- app/reducers/info.js
- test/unit/lnd/lightning.spec.js
When connecting to a remote wallet we assume that the wallet is already unlocked. In the case where it is not already unlocked, forward the error message to the UI.
Fix #738
This is a first step towards #543
1. Start up a remote lnd node and leave it in a locked state.
2. Start up zap wallet and try to connect to the node
Previously this would result in the loading screen showing indefinitely with no indication to the user as to what happened.
With these changes in place, the user will see a friendly error message telling them that thir wallet needs to be unlocked first.
**NOTE: This PR builds on https://github.com/LN-Zap/zap-desktop/pull/740 which should be merged first.**
Bug fix
> fix(grpc): show error on connect to locked wallet

- app/components/Onboarding/Onboarding.js
- app/lib/lnd/lightning.js
- app/lib/lnd/methods/index.js
- app/lib/lnd/subscribe/channelgraph.js
- app/lib/lnd/subscribe/invoices.js
- app/lib/lnd/subscribe/transactions.js
- app/lib/lnd/walletUnlocker.js
- app/lib/lnd/walletUnlockerMethods/index.js
- app/lib/zap/controller.js
- app/reducers/info.js
- app/reducers/onboarding.js
- test/unit/lnd/lightning.spec.js
If when connecting to a remote wallet we detect that it is locked initialise the wallet unlocker to allow users to unlock their remote wallets.
Users shouldn't need to manually unlock remote wallets before being able to connect to the as this adds friction.
Addresses #543
1. Start up a remote lnd node and leave it in a locked state.
2. Start up zap wallet and try to connect to the node
3. Verify that you are presented with the wallet unlocker screen and are able to log in.
**NOTE: This PR builds on #741 which should be merged first.**
New feature
> feat(grpc): ability to unlock remote wallet

- app/lib/lnd/util.js
- app/lib/zap/controller.js
- package.json
- yarn.lock
There is no need to check wether an lnd process exists and prevent Zap from starting if so. We don't care if there is another process running. We only care that we can successfully start up our own process. If there is a conflict with another lnd process such as a port that we need already being in use we already handle this elsewhere in our code and we pass more detail to the error message the other way.
The lnd process lookup is slow, unreliable, and not needed. Remove redundant code that adds unneeded dependencies and improve user experience.
1. Start up an lnd process:
```
lnd --bitcoin.active --bitcoin.testnet --bitcoin.node=neutrino --neutrino.connect=mainnet1-btcd.zaphq.io
```
2. Then start up zap and verify that it gives you an error message, as before (actually we get more …
> fix(lnd): do not require a single lnd process

- app/containers/Root.js
- app/lib/lnd/lightning.js
- app/lib/lnd/neutrino.js
- app/lib/lnd/util.js
- app/lib/lnd/walletUnlocker.js
- app/lib/lnd/walletUnlockerMethods/index.js
- app/lib/zap/controller.js
- app/reducers/ipc.js
- app/reducers/lnd.js
- app/reducers/onboarding.js
- package.json
Consolidate the flow for local and remote wallet connections for consolidate. When unlocking a local wallet wait for the macaroon to be generated before we try to use it.
Before this PR, creating a new local wallet would hang indefinitely because it was trying to use the macaroon file before it exists.
Test all init flows:
Bug Fix
Refactor
> fix(grpc): ensure connection to lnd on init

- app/components/Contacts/SubmitChannelForm.js
- app/components/Contacts/SubmitChannelForm.scss
- app/reducers/contactsform.js
- app/routes/app/containers/AppContainer.js
Display a warning when the user attempts to open a channel to a node that already has active channels open. Also display the node alias and total capacity of the existing channels in the warning message. The total capacity units automatically change when the user changes the unit in the dropdown menu on this screen.
Fixes #252 
Attempted to open channels to a node in each of these scenarios:
- node with no existing channels open. the warning is not displayed
- node with multiple open channels. the warning shows with the number of open channels, the alias and total capacity
- node with an open channel but no alias: the warning shows with the total capacity but no alias
Minor UI improvement
> feat(channels): warn when opening multiple channels to the same node

- resources/lnd.conf
This PR adds the new experimental routing flag that will improve the efficiency of autopilot and improve the overall on-boarding UX as autopilot will now start searching for channels before the headers are synced
Added the new routing flag
Autopilot will open channels quicker and users will be on-boarded more seamlessly 
Use the new routing flag with autopilot
Push a new flag into the neutrino args
> feat(autopilot): use new routing flag

- app/lib/lnd/util.js
- test/unit/__mocks__/dns.js
- test/unit/lnd/util.spec.js
Do not assume that an address that starts with a number is an IP address and expand validation to cover all FQDNs and IP addresses.
Fix #766
Added some unit tests
Bug fix
> fix(validation): improve hostname/ip validation

- app/lib/lnd/neutrino.js
- app/lib/utils/log.js
This PR includes three enhancements to our error logging:
1. Ensure that lnd output that goes to the stderr stream gets logged using the error log level and that the cause of the error is captured.
2. Limit the log namespaces that are enabled by default to only include the top level zap namespace and not also all of it's sub-namespaces.
3. Ensure that logs are output when the app is run in production mode. not only development mode so that its easier to diagnose an issue with a production build.
If lnd has a panic attack, the log messages are not using the proper error level and the cause of the error is not being captured and displayed to the user.
Manual testing with lnd instance that is crashing.
**Before:**
**After:**
Bug fix
> fix(log): log lnd stderr output as errors

- appveyor.yml
Remove the node and yarn caches on travis/appveyor They are rarely ever used and take several minutes to restore and unzip at the start of every build
If package.json changes that will trigger a rebuild of the node_modules. package.json changes fairly infrequently. Caching node_modules is enough and we don't also need to cache the npm/yarn caches in addition.
Caching npm and yarn caches adds a lot of extra time to builds unnecessarily. It takes several minutes to restore these directories from the cache and unzip them into place and they are not used 90% of the time. The only time they would be used is if package.json changed and that was triggering a rebuild of node_modules, in which case installing with a clean npm/yarn cache may be preferable to using an old npm/yarn cache.
Ensure …
> ci(appveyor): remove node/yarn caches

- package.json
We already have the html reporter setup and an npm script to enable easy viewing of the data (`yarn coverage`) so the text reporter isn't adding anything useful.
The text coverage reporter generates a lot of output that makes it hard to see the actual test results without scrolling up a lot first.
- Run tests
- Verify that test coverage output only show summary report and not full details.
- Verify that full coverage report can be accessed by running `yarn coverage`
Test improvements
> test(coverage): disable text coverage reporter

- package.json
The detectOpenHandles flag was added to help pin down an issue that we were facing with some of our tests a while back. This flag comes with a very high performance penalty and is no longer needed in our setup.
Slow builds.
CI improvement
> ci(jest): remove detectOpenHandles flag

- .flowconfig
Ignore invalid json files in flow config to prevent expected failures from producing errors.
See https://github.com/facebook/flow/issues/869
We are getting this error when running flow:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/npm/node_modules/config-chain/test/broken.json:11:3
Unexpected string
8│     "url": "https://github.com/dominictarr/config-chain.git"
9│   }
10│   //missing , and then this comment. this json is intensionally invalid
11│   "dependencies": {
12│     "proto-list": "1",
13│     "ini": "~1.0.2"
14│   },
```
See https://github.com/facebook/flow/issues/2364
run `yarn flow` and verify error is no longer produced,
Bug fix
> build(flow): ignore config-chain/test/broken.json

- package.json
Run jest with --forceExit flag to prevent stuck builds on CI.
Jest is sometimes unable to detect when tests have completed which can result in tests hanging indefinitely, which breaks our CI builds on Appveyor.
This is a known issue in jest and they added a `forceExit` in order to help users facing this issue.
See https://github.com/facebook/jest/issues/1456
CI improvement
> test(jest): run jest with --forceExit flag

- package.json
Coverage tests are only relevant for the unit tests and do not work in the context of the e2e test suite. Only generate coverage reports for the unit tests.
Coverage reports take some time to generate so there is no point in trying to generate them for the e2e tests since that is not supported.
- Run e2e tests and verify coverage reports are not generated.
- Run unit tests and verify coverage reports are generated.
Test improvements
> test(coverage): coverage only for unit tests

- package.json
- yarn.lock
react-addons-test-utils is depreciated, no longer used by us, and produces warnings on install.
> chore(deps): remove react-addons-test-utils

- app/lib/utils/btc.js
We need to pass a number to `<FormattedNumber>` for it to properly display the currency values. In some cases we were passing a pre-formatted string which was causing some currency amount to render as NaN.
Currency values showing as `NaN`
Manually test app
Bug fix
> fix(i18n): parse fiat amounts to number type

- app/components/Contacts/Network/Network.js
If the total channel balance is zero, do not show the channel balance at the top of the network view as the zero doesn't convey any useful information and looks strange.
Manually test app
**Before:**
**After:**
UX improvement
> fix(wallet): hide zero channel balance

- app/components/Contacts/Network/Network.js
Use `currencyName` in the req limit
The req limit was using capitalized `SATS`, `BITS` and `BTC` which is old and not used by the rest of the app
Manually
> fix(channels): use currencyName in req_limit

- app/components/Contacts/Network/Network.js
Display the currency name (BTC/tBTC etc) next to the amount that shows at the top of the network view.
We weren't showing the currency name, leaving up to the user to guess what the number meant.
Manually
**Before:**
**After:**
Bug fix
> fix(channels): display currencyName in network

- test/e2e/e2e.spec.js
Combine the e2e tests so that they use a single setup/teardown step which will reduce the frequency of random test failures.
There is currently a bug with Spectron which is causing random test failures due to `app.quit` not working as it should.
See:
- https://github.com/electron/spectron/issues/131
- https://github.com/electron/spectron/issues/186
- https://github.com/electron/spectron/issues/272
CI Improvement
> test(e2e): combine e2e test setup/teardown steps

- app/components/Activity/Activity.js
- app/components/App/App.js
- app/containers/Activity.js
Call `fetchChannels` from the `Activity` `componentWillMount` not in the `App.js` callback 
`App.js` `componentWillMount` callback gets called before we signal to the state machine that we are fully synced. `Activity.js` callback is where we call for all other app related user node data and only renders afterwards. In this PR we move the `fetchChannels` call to `Activity.js` so that it can be received by `ipcMain` and return us channel data.
Run the app on master and see the issue, run this PR and see it's fixed
> fix(channels): fetch in activity mount not app

- app/components/LoadingBolt/LoadingBolt.js
- app/components/LoadingBolt/LoadingBolt.scss
- app/containers/Root.js
- app/lib/zap/controller.js
- package.json
- test/unit/zap/controller.spec.js
- yarn.lock
Show the loading bolt for a little longer and then fade into the onboarding screen.
The loading screen only shows for 500ms, which is very short and almost not enough time to read the test 'loading`. After the 5000ms is up it switches instantly to the onboarding screen. The end result is that it kinda looks like it flickers.
The idea here is to smooth this out a little by showing the loading screen for a little longer and then fading into the onboarding screen.
Style changes
> style(loading): fade out loading bolt

- app/components/Onboarding/FormContainer/FormContainer.js
- app/components/Onboarding/FormContainer/FormContainer.scss
Remove the onboarding title bar and replace it with some padding
Windows and Linux had a UI bug because of the title bar
Manually
> fix(onboarding): replace title bar with padding

- app/lib/zap/controller.js
- app/main.dev.js
Dereference the main window after it has been closed in order to prevent messages from being set to it when it no longer exists.
On windows / Linux, if a message is sent to the mainWindow after it has been closed it causes an error to pop up in the users face.
Manually on Linux
Bug fix
> fix(wallet): dereference window after closing

- app/components/Onboarding/Syncing/Syncing.js
- app/components/Onboarding/Syncing/Syncing.scss
If we are syncing after having already completed the initial sync we do not show the funding address QR code. In this case, adjust the title padding so that the page title is better centred.
The sync page looks a little off when syncing a wallet that has already synced at least once.
Manually
**Before:**
**After:**
Style adjustment
> style(sync): vertically centre sync page title

- app/components/Onboarding/FormContainer/FormContainer.scss
Ensure that the previous and next buttons have a consistent height and do not move when switching pages in the onboarding process.
A slight difference in height between the previous and next buttons was causing the next button to appear to move when switching between a page with or without the previous button.
Manually - watch the next button move slightly when moving between page 1 and 2 of the onboarding process.
Style fix
> style(onboarding): ensure constant button position

- app/lib/lnd/neutrino.js
- app/lib/zap/controller.js
- package.json
- test/unit/lnd/neutrino.spec.js
- yarn.lock
Select free ports for lnd from a pool of options. By default we will use the standard lnd ports (10009 and 9735) but if those are not available then we will search for free ports in a nearby range.
This allows us to have multiple instances of the wallet running and avoids possible conflicts with other instances of lnd that the user may be running.
Manually
Enhancement
> feat(lnd): use free port for lnd

- app/components/Activity/Activity.js
Hide the "show / hide expired" toggle for new users with no previous activity.
For new users with an empty wallet it doesn't make any sense that in middle of the activity list there is a toggle button to show/hide expired requests, since we know the user has no requests.
Manually
UI/UX improvement
> fix(wallet): hide expired toggle for empty wallet

- app/components/App/App.scss
- app/components/Onboarding/FormContainer/FormContainer.js
- app/components/Onboarding/FormContainer/FormContainer.scss
Bring bak the titlebar so that the window can be moved, but make it transparent and pinned to the top of the window.
The window can no longer be moved on mac since removing the titlebar.
Manually.
Bug fix
> fix(ui): ensure draggable titlebar

- app/lib/utils/btc.js
Fix an app crash where the user had inputted some non-whole amount in BTC then tried to switch to satoshi. We fix this crash by rounding up if the number is not whole before calling `toBitcoin()`
Before this commit the app would crash if a user switched to satoshis while there was an input amount of some non-whole number (for example `0.1`)
You can verify the big in master by clicking into the pay form, setting the amount to 0.1 BTC, exiting the form and changing the app to satoshis. The app will crash. 
Then you can checkout to this PR and verify it no longer crashes
> fix(utils): dont pass non-whole num to toBitcoin()

- package.json
- test/e2e/e2e.spec.js
Jest process doesn’t quit after last test completes. This can cause our tests to fail sometimes, particularly on on Appveyor.
As an attempt to get past this previously we had set `--forceExit` in our jest cli options, but this doesn't always work either.
Further research suggests that setting ``--maxWorkers=2` could resolve the issue.
See
- https://github.com/facebook/jest/issues/1456#issuecomment-424356243
- https://github.com/facebook/jest/blob/master/docs/Troubleshooting.md
Fix #774, Fix #773
Run e2e tests locally and on CI.
CI improvement
> ci(jest): set maxWorkers to 2

- app/components/Contacts/SuggestedNodes/SuggestedNodes.js
- app/components/Contacts/SuggestedNodes/messages.js
- app/reducers/channels.js
- app/translations/en.json
If we are unable to load the suggest nodes list, display a message prompting the user to open channels.
Previously we would show an infinite spinner.
Fix #392
Manually - edit the suggested nodes URL here https://github.com/LN-Zap/zap-desktop/blob/master/app/lib/utils/api.js#L32 and start zap in order to simulate fetching a broken url.
**Normal:**
**With error - before:**
**With error - after:*
Bug fix
> fix(channels): handle suggested nodes load failure

- app/containers/Root.js
- app/lib/zap/controller.js
- app/reducers/onboarding.js
If there is a problem connecting to the Lightning interface on a local lnd instance, return the user to the onboarding screen and show the user the error message.
Previously, the app would hang on an infinite loading screen.
Simulate a problem connecting to the Lightning interface when using the local lnd by changing the connection deadline from 20 seconds to 0 seconds here https://github.com/LN-Zap/zap-desktop/blob/master/app/lib/lnd/lightning.js#L102 and trying to start up zap in the default mode.
You should be returned to the onboarding screen with the error message shown as a global error.
Bug fix
> fix(lnd): show error on problem connecting to lnd

- test/e2e/e2e.spec.js
Increase jest and spectron timeouts from their defaults.
Tests sometimes run very slowly on Appveyor and can timeout before they finish.
> ci(jest): increase timeouts

- app/components/Contacts/ChannelForm/ChannelForm.scss
- app/components/Contacts/ConnectManually/ConnectManually.scss
- app/components/Contacts/Network/Network.scss
- app/components/Form/Form.scss
- app/components/Settings/Settings.scss
- app/styles/tooltip.scss
Ensure that we import styles/variables.scss before attempting to use the z() helper function that it provides.
Several of our elements were missing z-index property, causing them to display incorrectly in the app.
Manually verify z-index ordering is correct throughout the app.
**Before:**
**After:**
Bug fix
> fix(ui): ensure settings menu shows on top

- app/package.json
- package.json
Bump version number to `0.2.3-beta` so that we can get automatic packaged builds going for the next release as part of the CI cycle.
> chore(version): bump to 0.2.3-beta

- app/components/UI/MainContent.js
- app/components/UI/Page.js
- app/components/UI/Sidebar.js
- stories/components/page-elements.stories.js
- test/unit/components/UI/MainContent.spec.js
- test/unit/components/UI/Page.spec.js
- test/unit/components/UI/Sidebar.spec.js
- test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
- test/unit/components/UI/__snapshots__/Page.spec.js.snap
- test/unit/components/UI/__snapshots__/Sidebar.spec.js.snap
Add reusable Page, Sidebar and MainContent components
**NOTE: This builds on the work in https://github.com/LN-Zap/zap-desktop/pull/840**
Provide page layout components that can be used throughout the app in a consistent way, with consistent styling.
`yarn storybook` and view the the components in `Components/Layout`
Enhancement
> feat(ui): add Page components

- app/components/Value/Value.js
Do not display insignificant trailing zero decimal places when displaying BTC currency amounts.
The additional trailing zeros make numbers unnecessarily long and harder to read.
Manually
**Before:**
**After:**
UI enhancement
> fix(ui): strip trailing zeros from currency values

- app/lib/lnd/methods/invoicesController.js
By default, lnd only returns the latest 100 invoices. Ideally we would implement pagination, but until then here is a quick fix to increase the max number of invoices returned by lnd to 1000.
Fix #911
Generate over 100 invoices with lnd and verify they all show in the app.
Bug fix / Enhancement
> fix(wallet): increase invoice fetch count to 1000

- app/reducers/channels.js
Disable the desktop notification for when a new channel opens or closes.
Desktop notifications every time a channel opens or closes is noisy and not really necessary. Most users will use autopilot for channel management and should not care too much when it opens or closes a channel.
Fix #879
Manually
Bug fix / enhancement
> fix(notifications): disable channel notifications

- app/components/App/App.js
- app/components/Contacts/Network/Network.js
- app/containers/Root.js
Load the suggested nodes list as early as possible, when the Root container first mounts. Ensure that we display nothing when node list was not loaded.
Fix #943 
Manually
Bug fix
> fix(wallet): load suggested nodes on Root mount

- package.json
I was just looking through the source and spotted this.
The keywords aren't relevant to the project, it looks like they were left in from a boilerplate generator.
I just removed the whole `keywords` property because this isn't a package published to npm to there's no need for them at all.
> Remove package.json keywords

- app/reducers/network.js
Do not store details of channel edges in redux. 
We are seeing an error in the console warning of excessive memory usage. It links to https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#excessive-use-of-memory-and-cpu
This is caused by us trying to store all of the `edges` data from the network in redux. The edges data is massive and given that we aren't using it there is no need to store it in redux.
> perf(redux): don't store channel edges

- resources/lnd.conf
Enable LND `restlisten` in default mode
Change `restlisten=0.0.0.0:8086` in `resources/lnd.conf`
There are folks building lapps that rely on an already running node for users, some relying on LNDs REST interface being enabled, most recently the Joule browser plugin.
A nice setup would be Zap desktop with neutrino and using these other applications on top of it
Manually
> feat(rest): enable LND restlisten

- app/reducers/network.js
- app/store/configureStore.dev.js
Avoid excessive use of memory and CPU in redux devtools by stripping out large objects and replacing with placeholders.
This PR reverts the changes from #985 and reimplements in a different way by using [actionSanitizers](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer) to strip out large data and replace with placeholders.
This reduces the size of the state data propagated to devtools from about 30k lines to 3k lines.
Start up the app and view the redux state in redux devtools.
Performance enhancement
> perf(devtools): strip large data from devtools

- app/reducers/channels.js
Always fetch channel balances after receiving channel data.
Fix #939
Manually
Bug fix
> fix(channels): fetch balance on receiving channels

- app/components/Pay/Pay.js
- app/reducers/pay.js
Reset the pay form and ensure validation and form submission is triggered immediately when a lightning: link is used.
Fix #1006
Manually - test various `lightning:` links in various different app states (modal already open, modal not already open, pay form already partially filled etc)
Bug fix
> fix(pay): ensure lightning: links validate

- app/containers/Initializer.js
- app/preload.js
- app/reducers/wallet.js
- app/store/db.js
When starting up the app, scan the local filesystem for wallet directories. If we find a directory without a corresponding entry in indexeddb, create a new database entry so that the wallet becomes available within the app.
- Ensure that users upgrading from an old version of Zap (pre indexeddb) have their wallets continue to be available.
- Make it possible to import wallets simply by moving them to an expected location on the filesystem and then starting the app
Manually -
1. Check out an old version of Zap (prior to the implementation of  indexeddb) and create a local wallet (check out the `0.2.2-beta` tag)
2. Quit Zap, Update the codebase to the `next` branch and restart the wallet.
You should find that your old wallet is now visible in the new home screen.
You can also test by …
> feat(migration): import wallets from fs

- app/components/GlobalError/GlobalError.js
- app/preload.js
- app/reducers/info.js
- app/reducers/wallet.js
Remove wallet data from the filesystem when `deleteWallet` is called.
Previously, deleting a wallet would not actually remove it from the file system, causing it to reappear when restarting the app.
Manually
Enhancement
> feat(wallet): delete wallet from filesystem

- app/components/Syncing/Syncing.js
- app/reducers/lnd.js
Update sync percentage calculator to base its percent on the total data that needs to be synced rather than the total size of the blockchain.
If I already have 98% of the data synced when I start the wallet, then the bar should go from 0-100 for the remaining 2%, rather than from 98-100
Resyncing an old wallet after this upgrade to 0.5.1 is slow if that wallet is quite old (as it has to resync frrom the wallet birthday), and the bar shows 99% for the entire thing - which looks like it's actually going to take an hour or more in my case
Looking at a sync bar saying 99% for an hour is offputting
Create new wallets and open old ones and verify sync progress bar represents remaining sync only.
Enhancement
> fix(sync): progress bar only consider remaining sync

- app/reducers/channels.js
- package.json
- yarn.lock
We can receive a lot of channel updates from channel graph subscription in a short space of time. If these involve our our channels we make a call to `fetchChannels` and then `fetchBalances` in order to refresh our channel and balance data.
Debounce these calls so that we don't fire too many times in quick succession.
Performance enhancement
> perf(grpc): debounce channel fetching

- app/reducers/channels.js
- package.json
- yarn.lock
This is a follow up to #1040 which fixes some issues with the implementation. Now we use `throttle` rather than `debounce` to ensure the frequency of the call to fetch channels (throttled to once per second).
debounce implementation was not working as expected with errors being logged in the console.
Manually
Bug fix
> perf(grpc): throttle calls to fetch channels

- app/components/Contacts/AddChannel/AddChannel.js
- app/components/Contacts/Network/Network.js
- app/components/Wallet/Wallet.js
Clean up network list:
- Fix padding at top of the window so it aligns with the wallet header
- Make search result rows clickable rather than just the `connect` button.
- Apply hover styles to rows rather than just the `connect` button.
- Adjust font sizes and colors
- Truncate long node names with ellipsis
Improve style of the network list
Manually
**No results**
**Results list:**
Style updates
> style(network): clean up network list

- app/components/Activity/Activity.js
- app/components/Contacts/AddChannel/AddChannel.js
- app/components/Contacts/Network/Network.js
- app/components/Pay/Pay.js
- app/components/Request/Request.js
- app/components/Syncing/Syncing.js
- app/components/UI/Modal.js
- app/components/UI/Panel.js
- test/unit/components/UI/__snapshots__/Modal.spec.js.snap
- test/unit/components/UI/__snapshots__/Panel.spec.js.snap
Explicitly enable scroll bars on `<Pane.Body>` elements when needed, rather than assuming it as a default.
There are only a couple of specific places where we want scroll bars to appear, so enable there only rather than enabling by default and disabling everywhere where we don't want them.
Unwanted scroll bars appearing when using app with a small window size. 
Manually. Navigate all app pages and  ensure that unwanted scrollbars don't appear as you resize the screen.
You can reproduce an instance of unwanted scrollbars (prior to this patch) by starting up the app, leaving the window size at the default size, and go through the onboarding process. Scroll bars will flicker on and off as you navigate between pages.
Bug fix
> style(panel): explicitly enable panel scroll bars

- app/containers/Initializer.js
Ensure that we boot into the onboarding process if the user doesn't have any saved wallets.
This fixes a bug that caused the app to launch into the homepage for new users that launch the app for the first time, rather than into the onboarding process.
1. Move your Electron user data directory out of the way (you can find the path for this here: https://electronjs.org/docs/api/app#appgetpathname)and launch the app in order to simulate a new user that has never opened the app before. Verify that the app launches into the onboarding process.
2. Log out of the wallet, quit the app, and relaunch. Verify that you start on the homepage this time.
3. Log out, delete your wallet, and relaunch the app. Verify that you start on the onboarding process again, as if you were opening the app for the …
> fix(onboarding): launch onboarding if no wallets

- app/store/configureStore.dev.js
This fixes an issue where we were mutating redux state in our redux devtools `stateSanitizer` which was causing the network node data to be resanitized different after every update to the redux state.
Look at the state diff in the redux action log - every single update contains changes to `network.nodes` and `network.edges`. This should only happen once rather than every state change.
Monitor the state diffs in redux dev tools.
Bug fix
> fix(redux): dont mutate network data

- app/components/Contacts/Network/Network.js
Always show channel balances at the top of the network tab.
Previously, we were only showing the channel balance if it was non zero. This made the UI feel a little inconsistent as sometimes the header of the network pane would show a the channel balance, and at other times it would not.
Also, when a user has some open channels, but no value in them it feels like a bug that we don't tell them that they have $0 in their channels and just completely hide the current balance.
Manually
**Before:**
**After:**
Enhancement
> fix(network): always show channel balances

- app/components/App/App.js
- app/containers/App.js
- app/reducers/contactsform.js
- app/reducers/ticker.js
- package.json
- yarn.lock
Show list of nodes in network search list when no search criteria have been entered. Sort list with connected peers at the top of the list.
Additionally, refetch node and network info on an exponential backoff schedule to ensure that node data is available when users need it. This starts off fetching every 2 seconds and increases by a factor of 1.5 until a maximum of a 10 minute refetch schedule is reached, where it remains until the app is unmounted.
Make the network list more useful.
Rebase and update https://github.com/LN-Zap/zap-desktop/pull/340 to work with latest codebase
1. Spin up a new local node.
2. As soon as it has finished syncing, click the `Add channel` button.
3. You will see an empty node list.
4. Within a few seconds, the list should start to fill up with node data. …
> feat(network): show connected peers first

- internals/webpack/webpack.config.renderer.prod.js
Ensure that empty.html file is copied over to the production build.
When the app first boots up, we load a blank html page into a hidden browser window in order to access the indexeddb database and fetch the user preferences as early as possible.
This file was missing and that was preventing the user settings from being properly fetched on a production build.
Run the app in production mode with debugging enabled:
```
DEBUG=zap* DEBUG_LEVEL=debug yarn start
```
Notice the error in the console:
```
zap:main [DBG]  Fetching user settings from indexedDb (using database "ZapDesktop.production") +72ms
zap:main [WRN]  Unable to determine user locale and theme [object Object]
zap:main ___Inspected object #1___
zap:main { __ELECTRON_SERIALIZED_ERROR__: true,
zap:main   message:
zap:main    'Failed …
```
> build(webpack): copy empty.html to final build

- app/lib/lnd/neutrino.js
- resources/lnd.conf
Use port 11009 (rpc) and 8180 (rest) for lnd when running in production mode.  When running in dev mode, user a random range bound port for both rpc and rest.
This ensures that users have a consistent port that they can connect to.
Manually - run app in dev mode and production mode, at same time.
Enhancement
> fix(lnd): use static ports for production builds

- app/components/App/App.js
Ensure that `fetchDescribeNetwork` is called correctly in App `componentDidMount()`
We were incorrectly calling fetchDescribeNetwork within a setInterval() which was resulting in an unsafe-eval CSP warning.
Make a production build:
```
yarn package --mac
````
and start it with `PROD_DEBUG` enabled:
```
DEBUG_LEVEL=debug DEBUG=zap* DEBUG_PROD=true ./release/mac/ZapDesktop.app/Contents/MacOS/ZapDesktop
```
Login to one of your wallets. You will see an error like:
> Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
Apply this patch, rebuild …
> fix(wallet): ensure describe network on timer

- package.json
Ensure that `yarn dev` works correctly on Windows machines.
`yarn dev` would produce an error, making it impossible to run the app in dev mode on Windows.
Run `yarn dev` on windows and verify that app starts up in dev mode.
Bug fix
> fix(windows): ensure yarn dev works on windows

- app/lib/zap/updater.js
Set the update channel to `beta` so that users will be only be upgraded to "beta" or "latest" versions of the app automatically. Allow overriding the update channel by starting the app with the `AUTOUPDATE_CHANNEL` environment variable set.
This frees up the alpha channel to be used by developers or users that specifically enable it. 
Electron build change
> build(electron): set autoupdate channel to "beta"

- app/components/Home/Home.js
- app/components/Home/WalletLauncher.js
- app/containers/Home.js
- app/reducers/lnd.js
Show a global error if we fail when launching a remote connection.
Previously, if there was a problem connecting to a saved remote node connection, the error would not be shown to the user and there was no indication that there was a problem.
Disconnect your computers wifi and try connecting to a saved remote wallet.
Bug fix
> fix(home): show connection errors

- app/components/Onboarding/Steps/messages.js
- app/translations/en.json
Caught this on the Onboarding screen and couldn't help myself 😄.
> style: fix spelling of "default" in Onboarding menu

- app/lib/zap/controller.js
- app/main.dev.js
- Refactor main controllers to make easier to follow
- Ensure that grpc streams are disconnected before quitting the app
- Ensure that all instances of the mainWindow are dereferenced when quitting
- Fixup issues with app quit process on Ubuntu.
Issues with app exit process
https://github.com/LN-Zap/zap-desktop/issues/1053
1. Quit app from home screen
2. Quit app from wallet launcher screen
3. Quit app from sync screen or fully loaded wallet
Bug fix
> fix(electron): clean up and fix app quit process

- app/store/db.js
When first creating the database, scan testnet wallets on the file system. If found, create in the database and set the active wallet.
This ensures that users upgrading from pre 0.3.0 have their old wallets available immediately.
Bug fix
> fix(migrate): migrate old wallets early

- app/components/Pay/Pay.js
Ensure that the correct amount is displayed on the Pay form send button as per the selected currency unit display.
Value was incorrect on the send button on the pay form when switching between the different btc units.
Manually - try different combinations of currency before and after moving to the pay summary page.
Bug fix
> fix(wallet): display correct amount on send button

- package.json
- yarn.lock
Merge latest changes from the bolt11 library into our fork in order to add support for deciding invoices that include milisat amounts.
See https://github.com/bitcoinjs/bolt11/issues/9
Fix #1166
Try to pay various ln invoices, including one from the blockstream store.
Bug fix
> fix(pay): update bolt11 to support millisatoshis

- app/components/Home/WalletLauncher.js
- app/containers/Initializer.js
- app/containers/Root.js
If there is a failure connecting to the active wallet when the app first starts up, redirect the user to the wallet launcher and show an error message.
Previously, the app would hang indefinitely at the Initializer component.
Fix #1173
1. Start the app and connect to a remote wallet
2. Quit the app
3. Disconnect your internet connection
4. Start the app again
Without this patch it will hang on a blank screen.
With this patch it will show the loading screen for up to 20 seconds whilst we try to connect to lnd and then redirect to the wallet launcher with an error message indicating that the connection failed.
Bug fix
> fix(boot): redirect to launchpad on failed connect

- app/containers/Initializer.js
- app/containers/Logout.js
- app/lib/zap/controller.js
- app/reducers/app.js
- app/reducers/onboarding.js
- app/reducers/wallet.js
Only trigger the onboarding process to start once the app is ready. This means waiting until we have loaded all the available wallet data and the onboarding process has been triggered from the main process.
This ensures that we do not attempt to start the onboarding process until the main process has been fully reset (disconnect / stop lnd) and prevents us from trying to start lnd when it is already started after a window refresh.
This is a more comprehensive fix for https://github.com/LN-Zap/zap-desktop/issues/1108 which doesn't have the sideeffect of breaking app reload.
Connect to a wallet, and then trigger a window reload (cmd+r). Previously this would result in a blank screen and an error about trying to start lnd in an invalid state on the terminal. With this patch it should work as …
> fix(app): reset onboarding after app refresh

- app/components/GlobalError/GlobalError.js
Fixes #1200.
I set the `z-index` property on for the `GlobalError` component to `99999` from `100`. The bug was caused by the modal having a higher z-index value than the error (`999` vs `100`).
This bug is fixed for now, however, a more robust solution needs to be implemented to avoid these types of bugs in the future. See this post for some ideas: [https://css-tricks.com/handling-z-index/](https://css-tricks.com/handling-z-index/).
Also, there might be a bug somewhere in the `componentDidUpdate` because I noticed that the timeout of `10000` doesn't always apply. If you trigger an error, wait a bit, close it and then quickly trigger another error you will see that the new error disappears in much less than 10 seconds.
> fix(ui): set global error z-index to 99999

- app/components/UI/Modal.js
- app/components/UI/Page.js
- test/unit/components/UI/__snapshots__/Modal.spec.js.snap
- test/unit/components/UI/__snapshots__/Page.spec.js.snap
Give positioning properties to the `Page` element (by setting `display: relative`) and ensure that the `<Modal>` component covers the full width and height of its container.
Fix display glitch with modal window.
Manually
1. `yarn storybook` and navigate to `Components/UI/Modal`. Compare before and after the patch.
2. Test all modal windows in the app.
**Before:**
Before the patch, the Modal was not bound to the Page element.
**After:**
With this change, the Modal will fill the containing Page element and not break outside of it.
> fix(style): ensure modal covers full page

- app/components/UI/Modal.js
- test/unit/components/UI/__snapshots__/Modal.spec.js.snap
Make modal's scrollable. Always keep the modal header (close button) visible, but scroll the rest of the content.
When viewing the app with a small window size, or when viewing a modal with long content that doesn't all fit above the fold, there is no way to see the bottom of the content.
Making the modal ensures that you can can always access all of the content, regardless of it's length.
Open up the Pay or Request modal, and make the window as short as possible. Verify that you can scroll the modal to access the bottom of the content.
Bug fix
> fix(ui): make modal scrollable

- app/components/Activity/Activity.js
- app/components/Contacts/Network/Network.js
- app/reducers/activity.js
- app/reducers/lnd.js
Fetch user balance and activity history after LND grpc is ready
Under some circumstances there is a race condition between establishing grpc connection and loading user balance\activity when unlocking a wallet. In particular when connecting to a locked remote node. It results in `SET_LIGHTNING_WALLET_ACTIVE ` being dispatched after `fetchChannels` action. This results in app being stuck on the loading screen because app is unable to handle a response from the LND via IPC. This happens due to IPC handler being added only after `SET_LIGHTNING_WALLET_ACTIVE ` is dispatched. The solution applied also fixes [#1193](https://github.com/LN-Zap/zap-desktop/issues/1193)
Manually
N/a
Explicit loading of user balance and activity history has been added after grpc is ready to avoid race condition
- …
> fix(startup-fetch-activity): fetch activity history when grpc is ready Fix #1193

- app/components/GlobalError/GlobalError.js
- app/components/Home/Home.js
- app/components/Home/WalletLauncher.js
- app/components/Onboarding/Steps/ConnectionConfirm.js
- app/components/Onboarding/Steps/ConnectionDetails.js
- app/containers/Home.js
- app/containers/Initializer.js
- app/containers/Onboarding.js
- app/containers/Root.js
- app/lib/zap/controller.js
- app/reducers/lnd.js
- stories/containers/home.stories.js
Consolidate errors from startLnd into a single object, and ensure that we handle all lnd start errors.
When the app starts it tries to automatically log into the last active wallet. If there is a problem with the cert or macaroon files, the user is left hanging on the loading screen.
Fix #1215
1. Set up a connection to a remote node
2. Open the wallet and then quit zap
3. Delete or move the cert or macaroon file
4. Start Zap and verify that you are taken to the launchpad with the cause of the connection error showing.
Bug fix
> fix(onboarding): handle host/cert errors on boot

- app/components/Onboarding/Steps/ConnectionDetails.js
Remove `lndConnect` prop in spread operator to ensure it doesn't get passed to the DOM as part of `...rest` 
Error in console on `ConnectionDetails` component in onboarding process.
> Warning: React does not recognize the `lndConnect` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `lndconnect` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
1. Create new remote wallet
2. Check the console when on the Connection Details step
Bug fix
> refactor(props): do not pass lndConnect to DOM

- app/lib/lnd/config.js
`SETTINGS_DEFAULTS ` const is defined twice in lib/lns/config.js`, probably the result of a bad conflict resolution. Remove the duplicate.
Fix #1270
Chore
> chore(config): remove duplicate code

- app/reducers/wallet.js
Remove additional unused arg in call to `setWalletsLoaded`
Fix #1260
Ensure wallets load properly
Cleanup
> refactor(reducer): remove unused arg

- app/components/GlobalError/GlobalError.js
- app/components/Home/WalletLauncher.js
- app/components/UI/Notification.js
- app/containers/Root.js
- app/reducers/error.js
Enhance the error reducer and GlobalError component to allow for multiple messages and ensure that error messages are visible for 10 seconds or until they are manually cleared.
Fix #1206
Manually - trigger the global error in various different ways.
Bug fix
> fix(ui): ensure error messages are visible

- app/components/Icon/Orbit.js
- app/icons/orbit.svg
Remove unneeded namespaces from svg icon
This svg icon has some namespaced attributes that are causing errors in the console when generating the coverage report after running the unit tests.
Run `yarn test-unit` and verify that the error message shown below no longer appears.
Bug fix
> refactor(icons): remove namespace from orbit icon

- app/components/Onboarding/Steps/BtcPayServer.js
- app/components/Onboarding/Steps/ConnectionConfirm.js
- app/components/UI/TextArea.js
- test/unit/components/UI/__snapshots__/LightningInvoiceInput.spec.js.snap
Fix black screen of death issue when trying to connect to a btcpayserver instance.
After submitting the BtcPayServer connection form, the user is left on a black screen with no way to recover.
Try to set up a new wallet that connects to a BTCPayServer node. You can use these details for testing:
```
{
"configurations": [
{
"type": "grpc",
"cryptoCode": "BTC",
"host": "example.com",
"port": "19000",
"macaroon": "macaroon"
}
]
}
```
(they are not valid connection details so you will not be able to connect, but they follow the expected format and will trigger the error/solution)
Bug fix
> fix(onboarding): handle btcpayserver connection issues

- app/lib/zap/controller.js
Ensure macaroon error is categorised as such.
If you try to connect to a remote server with a macaroon that has incorrect line endings the error message shows as a host error rather than a macaroon error
(these can get converted when, for example, committing a macaroon file to github:
> warning: CRLF will be replaced by LF in test/e2e/fixtures/readonly.macaroon.
> The file will have its original line endings in your working directory
Manually - try connecting to a remote server using a macaroon file whose line endings have been altered
**before:**
**after:**
Bug fix
> fix(onboarding): better categorize macaroon error

- app/components/Activity/Payment/Payment.js
- app/components/UI/Message.js
- app/lib/lnd/methods/index.js
- app/lib/lnd/methods/paymentsController.js
- app/lib/utils/promiseTimeout.js
- test/unit/components/UI/__snapshots__/Message.spec.js.snap
Mark payments as failed if there is no response within 60 seconds.
Fix #1292
Try to pay a payment that times out.
I was able to do this by trying to send a payment immediately after logging into a local wallet - presumably before lnd had a chance to reestablish an up to date network picture.
Bug fix
> fix(payment): timeout payment requests after 60 seconds

- app/lib/lnd/lightning.js
- app/lib/lnd/util.js
- app/lib/lnd/walletUnlocker.js
Load files asynchronously to ensure that we don't block the event loop needlessly.
grpc proto file and tls.cert was being loaded using Sync versions of the fs methods which causes a bit of hanging in the boot process. Replace with non-blocking async versions.
1. Create new wallet
2. Load existing wallet
Performance enhancement.
> perf(boot): load files asynchronously

- app/lib/utils/btc.js
> fix(btc): use correct parameter when converting from millisats to fiat

- package.json
- yarn.lock
Switch from custom fork of bolt11 to v1.2.2 official release.
My last patch against bolt11 to support uppercase payment requests was merged and 1.2.2 released with the fix.
Verify that uppercase and lowercase payment requests can be parsed.
Chore
> chore(deps): update bolt11 dependency to v1.2.2

- app/containers/Root.js
Do not show the loading screen when starting up lnd
It usually takes less than a second to start lnd, and showing the loading screen for a split second is distracting and looks like a display glitch.
Click the `launch` button on the wallet settings page for a local wallet.
Prior to this patch, the Loading screen would show for a split second before the password entry screen shows.
Bug fix
> fix(ui): loading screen flicker on wallet start

- app/lib/utils/notifications.js
Correctly apply `Notification.onClick` property. We don't actually use the onClick anywhere currently, but the current code would not work if we did.
Fix #1336 
Manually - verify all notifications work correctly
Refactor / Fix
> refactor(lib): apply notification.onClick properly

- app/lib/utils/btc.js
Allow for phots to ltc conversion
Fix #1345
1. Connect to litecoin node
1. Navigate to Request form
1. Set currency unit to photons
1. Enter a value in the amount field
1. Change currency unit to LTC
Ensure that correct conversion happens (previously would result in an error)
Bug fix
> fix(wallet): phots to ltc conversion

- app/lib/utils/btc.js
Millisatoshi should be satoshi * 1000 (we were converting satoshi to bits first, and then multiplying by 1000 which was resulting in an incorrect conversion.
Fix #1332
Bug fix
> fix(wallet): satoshi to millisatoshi conversion

- app/lib/lnd/methods/channelController.js
- app/lib/lnd/methods/invoicesController.js
- app/lib/lnd/methods/networkController.js
- app/lib/lnd/methods/paymentsController.js
- app/lib/lnd/methods/peersController.js
- app/lib/lnd/methods/walletController.js
- app/lib/utils/index.js
- app/lib/utils/promisifiedCall.js
Promisify lnd calls
Refactor lnd methods to use promisify. This reduces boilerplate code, makes it more compact and easier to read. Also simplifies addition of new methods in future
Manually. Tested functionality that involves corresponding lnd calls
Refactor
> refactor(lnd): promisify lnd calls

- app/components/UI/Input.js
- app/components/UI/TextArea.js
- app/components/withRequiredValidation/index.js
- app/components/withRequiredValidation/withRequiredValidation.js
- stories/forms/form.stories.js
- test/unit/components/UI/__snapshots__/Input.spec.js.snap
- test/unit/components/UI/__snapshots__/LightningInvoiceInput.spec.js.snap
- test/unit/components/UI/__snapshots__/Select.spec.js.snap
- test/unit/components/UI/__snapshots__/TextArea.spec.js.snap
- Ensure that input field borders are correctly highlighted when you click into them.
- Refactor `Input` and `TextArea` fields to be more consistent
- Extract some common input behavior out into an HOC
This fixes an issue with the inputs where by they don't properly get highlighted when you click in to them.
- Added several more examples to the storybook.
- Test behavior of various input fields throughout the app
**Default state Before:**
**Default state After:**
**With errors Before:**
**With errors  After:**
Bug fix
> fix(ui): highlight border of selected inputs

- app/lib/utils/btc.js
- test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
- test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
When converting crypto amounts to fiat, use rounding rather than string conversion to ensure that the result remains as a Number type.
Fix #1334
In #1374 we changed how we handle conversions to fiat to use `toFixed`, which results in a String. We want to the the result as a number so that we can work with it as a number. Conversion top string with fixed dp should happen at display time rather than at time of conversion.
This fixes a bug that has broken the Request page. Currently in master, the app crashes when trying to create an invoice because in the `Value` component (which we use for displaying value amount) we convert numbers to the correct number of decimal places. But in the case of fiat the value is already a string. This causes a fatal error since `toString` can not be called on …
> fix(btc): use rounding in fiat conversions

- app/components/App/App.js
- app/reducers/channels.js
- app/reducers/network.js
Rather than calling describe network periodically and replacing our entire node list with an updated list, subscribe to channel updates and only update node data for specific nodes that have been updated or added.
Pulled commit out of https://github.com/LN-Zap/zap-desktop/pull/1352 to make it easier to review in isolation
Enable component update highlighting in react dev tools and connect to a wallet with several channels and transactions.
Compare renders before and after the patch.
> perf(ui): only update node data when changed

- .travis.yml
- appveyor.yml
Our current CI process is relatively time consuming, largely due to the fact that we currently build and test the app on node LTS in addition to the current node version.
Node LTS primarily exists to server enterprises with an inability to move fast and keep technology current. We don't fit into that category and shouldn't waste time building and testing the app on an old node LTS version.
We could cut our build times in half with this change. I don't think any developers working on this project are likely to be using LTS node.
CI improvement
> ci(node): do not build and test on node LTS

- app/components/Request/Request.js
Use correct prop type for `invoice` prop in `Request` component.
Error in console when creating an invoice due to incorrect prop type.
Verify console error no longer appears.
Bug fix
> refactor(request): use correct prop type for invoice

- app/main.js
- internals/webpack/webpack.config.main.prod.js
Default `NODE_ENV` to `development` in the main process.
We already do this for the renderer process via `EnvironmentPlugin` (See [here](https://github.com/LN-Zap/zap-desktop/blob/master/internals/webpack/webpack.config.renderer.prod.js#L53-L55) and [here](https://github.com/LN-Zap/zap-desktop/blob/master/internals/webpack/webpack.config.renderer.prod.js#L53-L55)). Ensure that we do the same for the main process.
`NODE_ENV` was unset in the main process, preventing development related menu items from showing up (they only show when `NODE_ENV` is set to `development`)
Start up the app in development mode and verify that development menu items are visible and that `cmd+r` reloads the app.
Run app in production mode and ensure that development menu items are not visible
devtools fix
> refactor(main): run app in development mode by default

- app/components/Activity/Activity.js
- app/components/Activity/ActivityListItem.js
- app/components/App/App.js
- app/components/Contacts/Network/Network.js
- app/components/Wallet/Wallet.js
- app/containers/Activity.js
- app/containers/Activity/InvoiceContainer.js
- app/containers/Activity/PaymentContainer.js
- app/containers/Activity/TransactionContainer.js
- app/containers/App.js
- app/containers/Wallet.js
- app/reducers/balance.js
Separate out the Wallet and Activity containers in order to reduce unnecessary re-renders of these components.
Pulling commit out of https://github.com/LN-Zap/zap-desktop/pull/1352 to make it easier to review in isolation.
Enable component update highlighting in react dev tools and connect to a wallet with several channels and transactions.
Compare renders before and after the patch.
> perf(ui): reduce wallet & activity re-renders

- app/components/Contacts/Network/Network.js
- app/containers/App.js
- app/containers/Contacts/SuggestedNodes.js
- app/reducers/contactsform.js
Connect the Network component to the store directly to avoid re-renders of unrelated components when props that are only relevant to the Network component change.
Separate commit out of https://github.com/LN-Zap/zap-desktop/pull/1352 to make it easier to review in isolation.
Enable component update highlighting in react dev tools and connect to a wallet with several channels and transactions.
Compare renders before and after the patch.
> perf(ui): reduce network pane re-renders

- app/components/Home/Home.js
- app/containers/Home.js
Ensure that the active wallet is closed when the launchpad is mounted.
This fixes an edge case in which the app will try to connect to your previously open wallet even after it has failed to do so.
1) Connect to a remote wallet
2) Quit the app
3) Disconnect your internet connection
4) Open the app
The app will fail to connect to the remote wallet, and you will be taken to the home page.
Quit the app again, reconnect your internet connection. and relaunch the app. Again, it will try to connect to the other wallet automatically - which it should not do since when you were last in the app, you quit whilst on the lauchpad.
Bug fix
- [x I have read the _CONTRIBUTING_ document.
> fix(launcher): ensure wallet close on laucnhpad mount

- app/components/Pay/Pay.js
- app/containers/Initializer.js
- app/containers/Pay.js
- app/lib/zap/controller.js
- app/main.js
- app/reducers/pay.js
If a lightning link is used when the app is closed, wait for the the app to finish loading before passing the link onto the app.
Fix #1401 
This PR resolves for mac users. Issue persists for Windows.
1. Build the app (`yarn package`)
2. Install the app (on the mac, for example, you must copy the app out of the release dir and replace your app in `/Applications`). You need to ensure that the version that you just built will be opened when using the lightning link.
3. Test lightning links when the app is closed
4. Test lightning links when the app is already open
Bug fix
> fix(wallet): handle lndconnect links when app closed (mac)

- app/components/Home/WalletLauncher.js
- app/components/Onboarding/Onboarding.js
- app/components/Onboarding/Steps/ConnectionDetails.js
- app/containers/Onboarding.js
- app/lib/zap/controller.js
Do not double notify startup errors.
Errors connecting to a wallet can be shown twice, or not at all.
1. Set up a new remote connection using the onboarding process
2. Enter an incorrect port as part of the hostname
3. Wait 20 seconds for the connection attempt to timeout
4. You will be taken back to the connection details form with the timeout error showing below the host field.
5. Close the modal
6. The same error will now show at the top of the screen ads a global error.
Bug fix
> fix(launcher): do not double notify startup errors

- app/components/Channels/ChannelCapacity.js
- app/components/Channels/messages.js
- app/components/Icon/FolderOpen.js
- app/components/Icon/ZapSolid.js
- app/components/UI/ProgressBar.js
- app/components/UI/Value.js
- app/icons/zap-solid.svg
- stories/containers/channels/channel-capacity.stories.js
Add a new ChannelCapacity component that can be used to display channel capacity information using progress bars to visualise the channel state.
**Note: This builds on the work in #1433, which should be reviewed / merged first**
Re #1425
Part of the new Channel UI
Storybook
New component
> refactor(ui): add new ChannelCapacity component

- app/components/Pay/Pay.js
- app/components/UI/Value.js
- test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
- test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
- yarn.lock
Ensure that strings are coerced into numbers in the Value component prior to formatting them for output.
Additionally, use `FormattedNumber` to output properly formatted numbers.
Fix #1452
Follow reproduction steps in #1452
Bug fix / Enhancement
> fix(wallet): prevent crash on currency conversions

- app/lib/lnd/neutrino.js
- app/lib/zap/controller.js
- app/preload.js
Wait for lnd to finish terminating before attempting to run next e2e test, and try to force kill it if it doesn't kill within 50ms.
e2e tests often fail when run on travis/appveyor
Run `yarn test-e2e` several times and ensure that they complete each time
Rerun build on ci several times and ensure that e2e tests are consistently passing.
Test improvement
> test(e2e): force kill lnd after e2e tests

- app/lib/lnd/util.js
Fix invalid try/catch syntax
Found this issue whist debugging an issue on another branch. Using try/catch without the bracket causes an issue when testcafe tries to parse the code. Possible it also has other unknown side effects.
I haven't been able to find a definitive answer to the question of wether the `()` is actually needed or not (although every example I see shows that it does). Missing it out does break some things though so better to include.
Bug fix / refactor
> refactor(js): fix invalid try/catch syntax

- app/preload.js
- test/e2e/onboarding-btcpay.spec.js
- test/e2e/onboarding-connect.spec.js
- test/e2e/onboarding-create.spec.js
- test/e2e/onboarding-import.spec.js
- test/e2e/utils/helpers.js
Wait until tests have fully finished before deleing lnd data, and ensure that when we do delete it, we delete all lnd data rather than a single wallet.
When investigating test failures on travis I fond that sometimes there can be a javascript error in the browser console due to the fact that we were deleting the wallet data whist the app was still running. This can fail the tests.
Run tests locally and on travis.
test/ci improvement
> test(e2e): delete lnd data dir after test fixtures

- .storybook/preview-head.html
Use correct text colour for storybook
Some text elements are using the wrong colour in the storybook.
`yarn storybook`
**Before:**
**After:**
Docs improvement
> docs(storybook): ensure story font colour correctly applied

- app/package.json
- package.json
Bump version to `0.4.0-alpha` in preparation for the upcoming `0.4.x` release.
> chore: bump version to 0.4.0-alpha

- .eslintrc.js
- .gitignore
- app/index.js
- app/lib/lnd/config.js
- app/lib/utils/db.js
- app/main.js
- app/preload.js
- app/reducers/address.js
- app/reducers/info.js
- app/reducers/lnd.js
- app/reducers/locale.js
- app/reducers/theme.js
- app/reducers/ticker.js
- app/reducers/wallet.js
- app/store/db.js
- config/default.js
- internals/webpack/webpack.config.base.js
- internals/webpack/webpack.config.main.prod.js
- internals/webpack/webpack.config.renderer.dev.dll.js
- package.json
- stories/Provider.js
- yarn.lock
Introduce a global config system and use to to allow overriding of the database name based on user defined conditions.
By default, include the domain `next` when using the app with a version greater than 0.4.0-alpha in order to allow us to use dedicated databases for master vs next.
So, by default database names will be:
**0.3.x:**
```
ZapDesktop.development / ZapDesktop.production
```
**0.4.x:**
```
ZapDesktop.next.development / ZapDesktop.next.production
```
We have different database schemas in next vs master and want an easy way to work with both branches without causing conflicts.
Also, we want a global config store that we use to define global config variables (eg autopilot settings, rpc port/host) in a single location, with the ability for developers to easily override these …
> chore(devops): set db name based on app version

- app/reducers/contactsform.js
Node alias is an optional property that is only set if a node operator has configured an alias for their node.
Do not assume that a node alias exists when filtering the network node list.
Fix #1515
I was unable to reproduce the original issue, but looking at the offending code I can clearly see that a missing node alias could/should trigger issues just like the one logged.
Bug fix
> fix(wallet): check node alias exists before using

- app/containers/Contacts/SubmitChannelForm.js
- app/reducers/contactsform.js
Fix issue with search query not clearing when closing suggested nodes list. This previously resulted list to shrink or go empty because of hidden search query
Manually. Put some search string then press X and go back to suggested nodes
Bugfix
> fix(ui): fix issue with suggested node list shrinking

- app/components/Contacts/Network/Network.js
- app/containers/App.js
- app/reducers/channels.js
- test/unit/reducers/__snapshots__/channels.spec.js.snap
Make channel filter widget consistent UX as other search fields.
Fix #1517
Manually
Fix / Enhancement
> fix(ui): add missing channel search cancel button

- app/components/Contacts/AddChannel/AddChannel.js
- app/components/Contacts/Network/Network.js
- app/components/UI/Modal.js
- test/unit/components/UI/__snapshots__/Modal.spec.js.snap
Remove ability to horizontally scroll channels & suggested channels panels.
Fix minor visual issue
Manually
Styles bugfix
> fix: hscroll for current and  suggested channels panels

- app/components/Home/Home.js
- app/components/Home/WalletLauncher.js
- app/containers/Home.js
Disable the wallet `launch` button when launch is in progress to give the user some indication that something is happening.
When you click the launch button to connect to a wallet, there is no feedback in the UI to indicate that anything happened. This is especially problematic if you try to connect to a node that isn't actually online because the user has to wait upto 20 seconds in order to receive any feedback about the error.
Manually
1. click the launch wallet button - the button should become disabled with a processing spinner icon
2. also try the above, connecting to a remote node that is offline.
Bug fix
> fix(launchpad): disable launch button when launch is in progress

- app/components/UI/CryptoAmountInput.js
- app/components/UI/FiatAmountInput.js
- app/components/withNumberInputMask/index.js
- app/components/withNumberInputMask/withNumberInputMask.js
- app/components/withRequiredValidation/withRequiredValidation.js
- app/lib/utils/getDisplayName.js
- Improve input mask masking for crypto/fiat amount input fields when a period character is entered
- Extract duplicate code from `FiatAmountInput` and `CryptoAmountInput` components into a reusable HOC.
Fix #1547 in which entering `.` into the crypto amount input would cause the app to crash.
Manually
Bug fix
> fix(forms): more robust handling for amount inputs

- app/containers/Logout.js
Refactor `Logout` route to use declarative redirect approach as was done for the `Initializer` route in #1561
Manually
Refactor
> refactor: make logout route redirect declarative

- app/components/Pay/Pay.js
- app/components/Request/Request.js
Use the Input/Textarea `label` prop for adding labels to form elements on the pay & request forms rather than custom implementations.
Pay / Request forms were built before the `Input` and `Textarea` elements had support for `label` prop. Migrate to that for consistency.
This will allow #1501 to be updated to add the tooltip directly to the Input / Textarea elements.
Manually.
Refactor.
> refactor(forms): use input labels in pay/request

- app/components/Pay/Pay.js
- app/reducers/activity.js
- app/reducers/payment.js
Do not crash after paying msat invoices by ensuring that the data that we pass to the activity list always has a valid amount to display.
Fix #1568
Try paying this invoice (it's expired so your payment wont go through fully):
```
lnbc1336679810p1pwx5kefpp5nz4su9aezl8k77yakmpnvlg2fr3mg4y39a9cjyf72w4yxeum4jusdr2gfkx7cmtwd68yetpd5s9xar0wfjn5gp59cunjgz42dzzqen0wgszy3r0dcnhggz5wf6hxapwyptx2unfveujug3q2d6xjcmtv4ezq7pqxycqp2rzjqthv88m958rhnzyscgwuqay3dg7tsmvqp02cm62wzjy65tsu7q65kzyk3cqq20gqqyqqqqlgqqqqqqgqjqxuga2vz6ycmttj82cka76hdtj5682ahca2cxm9ezly6tzdrnd0jxyvzzelemgt67a6vrygt2tq5l2lup6a4syknmcs8klrgrchsxuhspndzpf5
```
Bug fix
> fix(wallet): do not crash after paying msat invoices

- app/components/LoadingBolt/LoadingBolt.js
- app/components/withLoading/withLoading.js
- app/containers/App.js
- app/containers/Root.js
- app/containers/Syncing.js
- app/reducers/utils.js
Introduce singleton loading screen
Under certain circumstances loading screen animation restarts (because currently it's possible to have multiple instances of them at a time). This PR leaves `withLoading` HOC only to be applied to `Root`. Other location must handle `isLoading` state by adding corresponding conditions to `reducers/utils/isLoadingPerPath`
Manually
Bugfix/Refactor
> fix(ui): introduce singleton loading screen

- app/components/App/App.js
- app/components/Settings/Fiat/Fiat.js
- app/components/Settings/Locale/Locale.js
- app/components/Settings/Menu/Menu.js
- app/components/Settings/Settings.js
- app/components/Settings/Theme/Theme.js
- app/components/UI/Dropdown.js
- app/containers/App.js
- app/main.js
Remove the old network sidebar from the UI. This PR does not fully remove all the old network related code as we have not yet finished reimplementing everything but instead focuses on removing the network list from the UI.
Will follow with a PR to remove all old/unused code at a later point.
Ideally, we should merge #1568 prior to this one since we need that in place to ensure that we can still do all basic channel management through the new UI.
Resolves #1426
Manually
Refactor
> refactor(channels): remove old network sidebar

- app/components/UI/CryptoAmountInput.js
Fix incorrect fiat -> satoshi conversion in Request modal
Steps to reproduce
1. Press Request button
2. Switch denomination unit to satoshis
3. Start filling fiat field
4. Satoshi value will have a dot in the end, making it an invalid request amount
Manually
Bugfix
> fix(ui): incorrect fiat to satoshi conversion

- .travis.yml
- appveyor.yml
Update CI jobs so that deploy scripts are run on the `next` branch in addition to `master`.
Give us ability to have concurrent builds against `master` and `next` targeting different release versions.
> chore(devops): run deploy jobs on next branch

- app/components/Contacts/SubmitChannelForm/SubmitChannelForm.js
- app/components/Pay/Pay.js
- app/components/Request/Request.js
- app/components/UI/CurrencyFieldGroup.js
- app/components/UI/Input.js
Ensure that the amount fields on pay / request / channel open forms have required asterisk.
The amount fields are missing the required asterisk, even though they are required fields.
Manually
**Before:**
**After:**
Bug fix
> fix(ui): ensure amount input group has required flag

- app/lib/zap/menuBuilder.js
In the current version of Zap the sub-menu item Help > Community Discussions is a dead button (on macOS). The linter does not like the invite code.
The sub-menu item "Community Discussions" under "Help" is a dead link. Adding the proper "https://" to the "shell.openExternal('https://zaphq.slack.com')" statement opens the url. 
Edited the argument passed to the shell.openExternal() function. 
Improved user experience. Allows users to find the Slack channel easier. This should result in an increase in community interaction. 
Dead links aren't good. 
I don't believe this has been submitted as an issue. 
- [ x ] My code follows the code style of this project.
- [ x ] I have reviewed and updated the documentation accordingly.
- [ x ] I have read the _CONTRIBUTING_ document.
- [ x ] My commits …
> fix(wallet): resolve broken link in help menu

- app/components/GlobalNotification/GlobalNotification.js
Ensure notifications don't cover modal close button
Notifications cover the modal close button, forcing users to close notifications before they can close a modal.
Trigger a notification in a modal - eg, try to create an invoice for a large amount.
**Before:**
**After:**
Bug fix
> fix(ui): ensure notifications don't cover modal close button

- app/components/Activity/Invoice/Invoice.js
- app/components/Activity/Payment/Payment.js
- app/components/Activity/Transaction/Transaction.js
Make incoming/outgoing transactions more obvious by applying the green colour to the full amount rather than only the very small `+` symbol.
This change is based on designs supplied in Zeplin.
Fix #1538
Manually
**Before:**
**After:**
UI improvement
> fix(ui): make incoming/outgoing transaction more obvious

- app/components/LoadingBolt/LoadingBolt.js
- app/containers/ModalStack.js
Disable pointer events when fading out overlays
App is unresponsive during a fade out event (loading screen or modal close) - you can't click on anything until the fade out has fully completed.
Manually
Bug fix
> fix(ui): disable pointer events on fade

- app/lib/lnd/neutrino.js
- app/reducers/utils.js
- test/e2e/utils/helpers.js
Show the sync screen as early as possible.
If you connect to a local lnd node that is connected to a btcd node that it is not fully synced, the app will be stuck on the loading screen until btcd has completed it's sync and the lnd node starts syncing.
Rather than showing the loading screen, we should show the sync screen as it has additional context about the current sync progress for the user.
The reason it was stuck on the loading screen is because we didn't fetch the current block height from block explorers until lnd had started syncing, and knowledge of the current block height as well as the lnd current sync height was a pre-requisite for hiding the loading screen.
This change updates so that we fetch the current block height from block explorers as soon as the attempt to start lnd …
> fix(lnd): show sync screen as early as possible

- app/components/App/App.js
- app/containers/App.js
- app/reducers/activity.js
- app/reducers/lnd.js
Defer fetching activity/channel data from lnd until sync is complete.
Attempting to fetch channel data can cause neutrino to crash with an error like `unable to find arbitrator`.
There is no need for us to attempt to fetch this data until we mount the App, (after syncing has completed in the case of local neutrino wallets).
Manually
Bug fix
> fix(lnd): defer fetching data until sync complete

- app/components/Channels/Channels.js
- app/components/TabControl/PersistentTabControl.js
- app/components/TabControl/Tab.js
Improve performance of channel management tab view
Currently we unmount current tab when switching between card and list view, which results in some significant delay upon that action. This PR introduces persistent tab control component which hides inactive tabs without unmounting them.
One side effect of this change is that switching between tabs retains their respective scroll positions. If  this is totally undesired, this can be mitigated probably. 
Manually
Perf improvement
>  perf(ui): use persistent tabs in channel management

- app/components/Channels/ChannelCreateForm.js
- app/containers/Channels/ChannelCreateForm.js
Display the wallet balance rather than the channel balance in the channel create form footer message.
Fix #1648
Manually
Bug fix
> fix(channels): display wallet balance on create form

- app/components/Home/WalletLauncher.js
Disable wallet launch button while starting LND
Currently there is no response from UI when launching wallet. User can click `launch` button multiple times while wallet is starting.
Manually
Bugfix
> fix(ui): disable launch button when opening wallet

- app/containers/Root.js
- app/lib/lnd/config.js
- app/lib/lnd/neutrino.js
- app/lib/utils/localWallets.js
- app/lib/zap/migrations/purge-local-wallets.js
- app/lib/zap/migrator.js
- app/main.js
- app/preload.js
- app/reducers/wallet.js
- config/default.js
- config/development.js
- config/production.js
- config/storybook.js
- config/test.js
- package.json
- test/unit/__helpers__/setup.js
- yarn.lock
Reconfigure Zap to connect to 2 new btcd nodes that are running the latest version of btcd. And, update lnd to the latest build from master.
Introduce a basic migration system and use it to trigger a rescan of all local wallets which is needed as part of an upgrade to the latest btcd and lnd.
- consolidate local wallet methods
- trigger resync for all local wallets
- update lnd to v0.5.1-beta-795-ga6ba965b
- update lnd-grpc to v0.1.7
- switch to testnet3 and testnet4 btcd nodes
Update LND and BTCD to latest versions.
Manually
> fix(lnd): update btcd & lnd and trigger a resync for local wallets.

- app/components/Channels/ChannelNodeSearch.js
- app/components/Channels/messages.js
- app/translations/en.json
Make channel search results header more informative
Right we have generic `All nodes` header for any search case (including no results) which is not very informatove
Manually
Enhancement
> fix(ui): make channel search results header more informative

- app/components/Syncing/Syncing.js
- app/reducers/info.js
- app/reducers/lnd.js
Ensure that we only set the `hasSynced` property when a sync completes, and always show the QR code in the sync process unless this has been set.
Fix #1367
Manually:
1. Create a new wallet - verify that QR code shows when syncing
2. Exit sync process early, and reload the wallet - verify that QR code shows when syncing
3. Wait for sync process to complete, exit the wallet, reload the wallet - verify that QR code does not show
Bug fix
> fix(sync): ensure QR code shown when syncing

- app/components/Activity/Transaction/Transaction.js
- app/components/Activity/TransactionModal/TransactionModal.js
- app/components/Activity/TransactionModal/messages.js
- app/reducers/activity.js
- app/reducers/transaction.js
Show channel limbo amount and block maturity height for transactions that relate to channels that are in the process of a force close.
**NOTE:** This PR builds on the work in #1677 which should be merged first.
Fix #1176
Force close a channel, when the remote party is offline. This should put the channel in a pending force close status. Then, view the `Pending` tab in the activity list and verify that the amount is what you expect. Then, click the transaction to the see the details and verify that the amount is correct and that the block maturity is displayed.
Previously, the amount would show as 0
Enhancement
>  fix(activity): show limbo amount for force close transactions

- app/reducers/channels.js
Remove unused getLegacyStatus method
This was needed when we were supporting old and new channel ui. Old channel ui was removed and this is no longer needed.
Manually (check channel ui)
Refactor
> refactor: remove unused getLegacyStatus method

- app/components/UI/CurrencyFieldGroup.js
- app/containers/Channels/ChannelCloseDialog.js
Mark non-required props as such
There are a couple of places where there are warnings in the log about required props not being set.
1. View channel details for a channel that is in the process of force closing and verify that no error shows in the console.
2. Open the Pay form and verify that there are no errors in the console about a missing required `validate` prop.
> refactor: mark non-required props as such

- app/components/Activity/Activity.js
- app/components/Activity/InvoiceModal/InvoiceModal.js
- app/components/Activity/PaymentModal/PaymentModal.js
- app/components/Activity/TransactionModal/TransactionModal.js
- app/components/Channels/ChannelCardListItem.js
- app/components/Channels/ChannelCreate.js
- app/components/Channels/ChannelCreateForm.js
- app/components/Channels/ChannelCreateSummary.js
- app/components/Channels/ChannelData.js
- app/components/Channels/ChannelHeader.js
- app/components/Channels/ChannelNodeSearch.js
- app/components/Pay/Pay.js
- app/components/Pay/PaySummaryLightning.js
- app/components/Pay/PaySummaryOnChain.js
- app/components/Request/Request.js
- app/components/Request/RequestSummary.js
- app/components/UI/Bar.js
- app/components/Wallet/ReceiveModal/ReceiveModal.js
- app/themes/base.js
- test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
- test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
- test/unit/components/UI/Bar.spec.js
- test/unit/components/UI/__snapshots__/Bar.spec.js.snap
Standardize hr line weights used throughout the app.
- Create `normal` and `light` theme variants for Bar element
- Use normal (0.6 opacity) for hr's under headings
- Use light (0.3 opacity) elsewhere
Some pages have heavy hr's (eg the transaction detail page), others have light ones (eg channel details) and we are not consistent in our approach.
Manually - view all pages of the app and verify hr weights look consistent.
Style fix
> fix(ui): standardize hr line weights

- .github/config.yml
Set up [welcome bot](https://github.com/apps/welcome) to welcome new users and help them get their commits merge ready.
Provide some more help for new users (see the 2nd comment in https://github.com/electron/electron/pull/17126 for an example of a welcome message on a new PR by a new contributor). I think this is quite nice and useful.
The templates I have created are based on the [electron ones](https://github.com/electron/electron/blob/master/.github/config.yml) with slight modifications.
> chore(devops): configure welcome-bot

- app/containers/Initializer.js
Mark non-required properties as such
Console warning about required `isWalletOpen` in the `Initialiser` component. This boolean prop now only gets set to true if there is an an open wallet and can be undefined as well as false if not. Same for `hasWallets`
Previously these props were copied from the settings to the wallet reducer and explicitly initialised as false if not true. Now, we read the settings directly from the settings selector in which the values may or may not be set.
Start app without open wallet and verify no warning in the log about this missing prop
Fix
> refactor: mark non-required properties as such

- app/components/Home/Home.js
- app/components/UI/Sidebar.js
Increase the homepage sidebar width.
Sidebar looks disproportionately small compared to the main content area and the create new wallet button looks squashed.
Manually
**Before:**
**After:**
Style adjustment
> fix(home): increase sidebar width

- app/containers/Settings.js
Properly detect active submenu
Submenu is broken as a result of a recent refactor in which the menu state was separated from the settings state.
Manually
Bug fix
> fix(ui): properly detect active submenu

- app/components/Icon/ArrowDown.js
- app/components/Icon/ArrowUp.js
- app/icons/arrow-down.svg
- app/icons/arrow-up.svg
- stories/icons/icon.stories.js
Add new `ArrowDown` and `ArrowUp` icons so that we have all 4 directional variations of our arrow icon.
Needed for new zap website, but figured it would make sense to add them to the repo here so that we have all of our icons in a single location.
Ultimately, we should probably look to extract these icons to a standalone repo but that's not something that I want to address at this point.
Storybook
Refactor
> refactor: add ArrowDown and ArrowUp icon

- app/components/Pay/Pay.js
When a user enters a valid address into the address field the form should automatically progress to the next form step.
This functionality was broken through the recent merge of the bip21 support https://github.com/LN-Zap/zap-desktop/pull/1724
Test pay form manually, and via `bitcoin` and `lightning` links. Try using the form in as many different ways as you can think of.
Bug fix
> fix(wallet): ensure pay form auto submits on valid address

- app/reducers/app.js
Ensure tickers are ready before displaying app by adding an additional condition the `isAppReady` selector. 
There is a race condition in which it's possible for the app to try to render before the currency tickers have loaded. This causes the app to crash because the `Value` component doesn't have everything that it expects in order to render currency amounts.
Manually
Bug fix
> fix(wallet): ensure tickers are ready before displaying app

- package.json
Updates lnd to latest build from master. This build of lnd has mainnet neutrino support enabled.
Bring lnd build up to date.
> fix(deps): update lnd to v0.5.1-beta-847-gc4a438e

- app/lib/lnd/methods/index.js
- app/reducers/balance.js
- test/unit/reducers/__snapshots__/balance.spec.js.snap
- test/unit/reducers/balance.spec.js
Include pending channel balances in the wallet total balance.
Right now the pending open channel balance is not factored into a users balance, resulting in money seemingly disappearing when a channel is opened.
Fix #1770
Manually
Bug fix
> fix(wallet): include pending channel balance in wallet balance

- app/components/Icon/PlusOnboarding.js
- package.json
lint icons after generation
Ensure that newly generated icons do not fail lint checks, and the existing icons are not regenerated with changes that fail our lint rules.
Manually (run `yarn generate-icons` and verify existing icons are not modified.
Lint fix
> style: lint icons after generation

- app/reducers/settings.js
- app/reducers/ticker.js
- config/default.js
Set default currency to sats. This affects new users only, or users that have not already manually set the currency within the app.
Better UX for new users with small balances.
Delete the `chain.bitcoin` entry  from the `settings` database table, and then restart the app. Should be reset to `sats`.
Enhancement
> feat(wallet): set defatult currency to sats

- app/lib/lnd/neutrino.js
Neutrino seems to struggle with channel validation, resulting in Zap users not being able to open channels. To resolve this, for the time being, we enable `assumechanvalid` on mainnet, so that users can test neutrino on mainnet.
Make sure mainnet neutrino is functional
Enable mainnet on a local wallet and open a channel
Fix
> fix(lnd): enable assumechanvalid on mainnet

- app/lib/lnd/methods/index.js
- app/lib/lnd/methods/paymentsController.js
- app/lib/lnd/push/sendpayment.js
- app/reducers/activity.js
- app/reducers/payment.js
Use the sendPayment streaming API to send payments and update the app with details of successful/failed payment when we get the relevant response back from lnd.
Remove arbitrary 60 second timeout.
Manually - test successful and failed payments and ensure that UI updates correctly.
Enhancement
> fix(wallet): better payment success/error handling

- app/components/Request/RequestSummary.js
Improve payment request  status color scheme
- Green is paid
- Orange is not paid
- Red is expired
Currently it's hard to distinguish between states based on color
Enhancement
> fix(ui): change invoice status color scheme

- app/components/Pay/Pay.js
Only show fee widget for onchain transactions
Transaction fee widget was recently added to the pay form, but it's currently showing up if you try to pay a lightning invoice with a `zero` amount. It should only show for onchain transactions.
This PR ensures that it only shows for onChain transactions.
Try to pay a LN invoice with a 0 amount, eg https://tippin.me/@mrfelton and verify that the onchain transaction fee widget does not show.
Bug fix
> fix(ui): only show on-chain transaction fee widget for onchain transactions

- config/default.js
Bump stable version to 0.4.x
Set `0.4.x` as stable app version. This will cause `0.4.x` code to once again connect to the default database namespace, freeing up the `next` database namespace to be used in conjunction with `0.5.x`.
> chore: bump stable version to 0.4.x

- app/package.json
- package.json
Bump version to 0.5.0-alpha
Bump version in `5.x` branch to `0.5.0-alpha` (`5.x` branch will soon become the new `next`)
> chore: bump version to 0.5.0-alpha

- app/components/Dialog/DialogLndCrashed.js
Do not reset the lnd state when DialogLndCrashed unmounts (this only happens during hot reload).
When the app hot reloads (in development mode), the lnd state is currently being reset and the user is sent back to the launchpad. This causes a broken app state since lnd is actually still running but the app thinks that it isn't.
Trigger app hot reload and verify that user is not thrown back to the launchpad.
Bug fix
> fix(lnd): don't reset lnd state on hot-reload

- app/components/Onboarding/Onboarding.js
Remove the Autopilot form step from the onboarding flow if the user has selected mainnet.
Autopilot is currently not recommended to use on mainnet.
Manually
Enhancement
> fix(onboarding): don't allow autopilot on mainnet

- app/lib/lnd/lightning.js
- app/lib/lnd/walletUnlocker.js
- package.json
- yarn.lock
Update lnd-grpc package to latest version that includes additional handling to detect lnd master builds.
BTCPay Server users unable to connect due to unpredictable lnd  version strings.
Manually
Bug fix
> fix(lnd): improve lnd version detection

- electron/main.js
On mac, closing the main window when the app is in fullscreen mode results in a black screen (see #1893). To resolve this, ensure that we exit fullscreen mode before hiding the app.
See https://github.com/electron/electron/issues/6033
Fix #1893
Follow repro steps in #1893
Bug fix
> fix(electron): exit fullscreen before closing

- electron/about/index.js
- electron/menuBuilder.js
- webpack/webpack.config.renderer.prod.js
Since flattening the repo in #1895 the linux builds have been broken. On investigation I've discovered that it's attempting to package a bunch of node_modules that it should not be.
By default, electron-builder packages app production dependencies and ignores devDependencies. Since we bundle all of our code with webpack, technically everything is a development dependency so one solution would be to move all dependencies to `devDependencies`. However, I think it's cleaner for us to just exclude `node_modules` and to keep the `dependencies` section referencing only the dependencies that we actually use in the app.
Additionally, this adjusts how we package the `about` window code and resolves an issue where it was not correctly displaying the logo when running `yarn start`
Fix build issues. …
> build(electron): exclude node modules from production app

- renderer/components/Channels/ChannelCreateForm.js
- renderer/components/Pay/Pay.js
- renderer/components/Request/Request.js
- renderer/containers/Channels/ChannelCreateForm.js
- renderer/containers/Pay.js
- renderer/containers/Request.js
Refetch fiat ticker data every time one of our payment forms are open in order to help ensure that conversion rates are up to date. Covers the Pay, Request and CreateChannel forms.
Fix #1953
Manually
Bug fix
> fix(wallet): refetch fiat tickers when forms open

- renderer/reducers/network.js
- renderer/store/configureStore.dev.js
Do not store network edges in state. We don't use this data anywhere, and it takes up a lot of memory.
I was doing some debugging and analysing the memory heap. The thing that takes up the bulk of our memory (sometimes over 50%)is the network edge list. It grows considerably over time as the app remains open.
Look at memory snapshot (taken from memory tab of devtools)before and after patch.
> perf: do not store network edges in state

- renderer/components/Util/WalletName.js
Show a fallback value in case we are unable to determine the wallet name, rather than crashing the app.
This PR sets the wallet name as `[unnamed]` in the case that we can't determine the wallet name.
In some situations (eg #1997) it's possible that a corrupt wallet config gets saved such that we are unable to determine the wallet name correctly. In this case, the app crashes as it assumes that a wallet config has a value for `host`.
Put an invalid wallet config into the db (one without a host prop) and verify that the app doesn't crash when trying to access the wallet's settings form.
Bug fix
> fix(launchpad): fallback wallet name incase host unknown

- package.json
- renderer/components/Onboarding/Steps/ConnectionConfirm.js
- yarn.lock
Convert old style lndconnect links to the new format before storing as part of a wallet config.
fix #1997
Try an old style lndconnect link, like the ones used by Node Launcher:
edit to work with your own node:
```
lndconnect:?cert=~/.lnd/tls.cert&macaroon=~/.lnd/admin.macaroon&host=example.com:10009
```
Bug fix
> fix(lndconnect): support old style lndconnect links

- renderer/components/App/App.js
- renderer/components/Channels/ChannelDetail.js
- renderer/containers/Channels/ChannelDetailModal.js
- renderer/containers/ModalStack.js
- renderer/reducers/modal.js
- renderer/reducers/utils.js
FIx app crash when closing a channel
This PR fixes/changes a couple of things
1. A crash when the channel is closed and removed from the list (resolves #1996)
2. Automatically closes channels details modal after closing is done
3. Add ability to pass additional data when opening a modal and then carpet-closing modals based on predicates
Manually
Bugfix/Refactor
> fix(channels): prevent crash when closing a channel

- electron/menuBuilder.js
Ensure that currently selected language is selected in the language menu.
Fixes a bug where the selected language did not change in the language menu after changing the app language.
Change the language and ensure that the selected language in the system language menu updates correctly.
Bug fix
> fix(i18n): select current locale in language menu

- renderer/components/UI/GlobalStyle.js
Improve scrollbar visibility:
- Use the primary text colour as the accent colour for the scrollbars.
- Increase the width by 2px
fix #2025
Manually (dark and light theme)
**Before::**
**After:**
UI improvement
> fix(ui): improve scrollbar visibility

- package.json
- renderer/components/Channels/ChannelCardList.js
- renderer/components/Channels/ChannelCardListItem.js
- renderer/components/Channels/ChannelSummaryListItem.js
- yarn.lock
Improve channels virtualized list rendering by reducing overscan for the card view, removing dynamic objects (css style) and introducing deep compare for the props. We have a complex `channel` object which is produced by a selector and is additionally decorated. This was causing redundant re-renders of the channel list items. Overscan count was reduced only  for the card view because are a lot larger than summary items.
Manually
Perf improvement
> perf(channels): optimize list rendering

- package.json
Use os rather than platform name for releases. 
Create releases with more human friendly names.
before:
```
Zap-darwin-v0.5.0-alpha.dmg
Zap-linux-amd64-v0.5.0-alpha.deb
Zap-win32-v0.5.0-alpha.exe
```
after:
```
Zap-mac-v0.5.0-alpha.dmg
Zap-linux-amd64-v0.5.0-alpha.deb
Zap-windows-v0.5.0-alpha.exe
```
`yarn package -mlw`
Build fix
> fix(electron): use os rather than platform name for releases

- lnd/neutrino.js
Increase lnd debug level
At some point recently, the lnd log level has reverted from `debug` to `info`. We rely on debug level log output from lnd in order to monitor it's sync process when running as a local neutrino client. We are missing some of the messages that only show on the debug level, which we use to determine the sync state and as a result the progress bnar is updating very infrequently.
Manually - note, granularity and regularity of sync progress updates is increased.
Bug fix
> fix(lnd): increase lnd debug level

- electron/updater.js
Handle autoupdate errors and do not retry updates in the event that the first attempt was unsuccessful.
Autoupdate is not supported for the `.deb` release, so gracefully handle errors caused by trying to run the updater.
Fix #2070
Manually
Bug fix
> fix(electron): handle autoupdate errors

- config/custom-environment-variables.json
- config/default.js
- electron/updater.js
Read autoupdate config from global config rather than hardcoding into the autoupdater class.
Consolidate settings and make easier to change config.
Manually
Enhancement
> feat(config): read autoupdate settings from global config

- .travis.yml
- appveyor.yml
Pin node to version 11 on ci environments.
Travis just updated node to v12, and it's not building properly (eg https://travis-ci.com/LN-Zap/zap-desktop/jobs/195058149)
> ci: pin node to version 11.x

- services/grpc/grpc.js
- services/grpc/grpcService.js
- services/grpc/lightning/lightning.js
- services/grpc/walletUnlocker/walletUnlocker.js
Rename `Grpc` service to avoid conflict with `GrpcServce` and document classes.
Confusion/conflict between `Grpc` and `GrpcService` (both were called `GrpcService`)
CI
Refactor
> refactor: rename Grpc service class

- test/e2e/utils/helpers.js
Fix e2e tests getting stuck in windows under certain circumstances
Resolve #2076 
`yarn test-e2e`
e2e tests fix 
- [x ] My commits have been squashed into a concise set of changes.
> test(e2e): fix tests getting stuck on win in some cases

- renderer/reducers/address.js
Store and reuse unused address.
This fixes a bug in the next branch in which fetched addresses are not being stored properly in the database, resulting in a new address being generated every time a wallet is launched.
1. Create a new wallet
2. Note the address that is shown in the sync screen
3. Exit the sync process
4. Relaunch the wallet and verify that the same address is shown.
Bug fix
> fix(wallet): store and reuse unused address

- renderer/components/Onboarding/Steps/ConnectionDetailsManual.js
- renderer/components/Onboarding/Steps/Recover.js
- renderer/components/UI/Input.js
- renderer/components/UI/TextArea.js
- test/unit/utils/parseSeed.spec.js
- utils/parseSeed.js
If the user pastes a valid 24 word seed into the first input of the wallet recovery form, parse the seed from the clipboard into individual words and paste the words into each of the 24 inputs.
Entering a seed into the wallet recovery pager is tedious and slow.
- Added unit tests
- Manual test of recover UI
New feature
> feat(onboarding): paste seed support in wallet recover

- renderer/components/Pay/Pay.js
- renderer/components/Request/Request.js
Pluck unused props before passing to dom
Warning like this when accessing Pay and Request forms:
```
react-dom.development.js:507 Warning: React does not recognize the `fetchTickers` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fetchtickers` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Refactor
> refactor: pluck unused props before passing to dom

- renderer/components/App/App.js
- test/unit/utils/scheduler.spec.js
- utils/scheduler.js
Prevent unnecessary `App` re-renders by extracting peer poll timeout from the `state` into a ref
`nextFetchIn` doesn't  influence anything in render func so can be safely extracted into a ref
Manually by monitoring redux log
Refactor/perf improvement
> perf(app): prevent superfluous top level re-renders

- package.json
- services/grpc/grpc.js
- services/grpc/grpcService.js
- services/grpc/lightning/lightning.js
- services/grpc/lightning/lightning.subscriptions.js
- services/grpc/lightning/streamify.js
- services/grpc/walletUnlocker/walletUnlocker.js
- yarn.lock
Resolves #2128 
This PR builds on top of #2134 `scheduler` functionality. So ideally that one should be merged first. The idea of the PR is to create a poll service (streamify util) for grpc commands which allows outer code to work with them as with regular LND subscriptions.  To solve #2128 we need to subscribe to topology update only after sync process is complete. To achieve this  `getInfo` is streamified and channel graph stream is set only after `sycned_to_chain` is true  
Manually
Refactor/bugfix
> fix(grpc): subscribe for topology update only after sync is done

- services/grpc/grpc.js
Ensure that we wait for gRPC state transitions to complete before emitting events indicating that they have.
Guard against potential issues arising from us thinking that a grpc state change had completed before it actually had.
Manually
Refactor / bug fix
> refactor(grpc): notify after state transitions

- scripts/lnd-release/.goreleaser.yml
Updates our lnd build script to include new tags for the new grpc subservices.
Enabling the new services in our lnd build is a pre-requisite to being able to use them (needed to implement autopilot BOS scoring for example)
> chore: add new build flags to lnd build script

- electron/controller.js
- electron/preload.js
- package.json
- renderer/reducers/app.js
- renderer/reducers/ipc.js
- renderer/reducers/neutrino.js
- test/e2e/onboarding-connect-manual.spec.js
- test/e2e/onboarding-create.spec.js
- test/e2e/onboarding-import.spec.js
- test/e2e/utils/helpers.js
Kill lnd directly after e2e tests rather than trying to do a clean app shutdown.
Sometimes lnd doesn't get properly killed. In the previous setup this could potentially happen if lnd/neutrino processes are already in the process of being shutdown when we attempt to kill them from the test suite.
Rn e2e tests several times.
Test improvements
> test(e2e): ensure lnd is killed after tests

- services/grpc/grpc.js
- disconnect getinfo stream on chain sync complete
- consolidate grpc subscription setup code
- unsubscribe streams before disconnecting
- dynamic gRPC subscription registration
Fix #2166 
Since we are not making use of the info subscription after the initial sync has completed I have opted to disable it once the sync has completed and we have activated the channel subscription. 
Manually
Refactor / fix
> refactor: consolidate/optimise grpc subscription setup code

- utils/appRootPath.js
fix appRootPath to run in main or preload process
Fixes an issue that prevents that app from starting up in production mode `yarn package`
- `yarn dev`
- `yarn start`
- `yarn package`
Fix
> refactor: fix appRootPath to run in main or preload process

- renderer/reducers/lnd.js
Improved connection error messages.
This PR ports over some error handling from master that got lost in the gRPC refactor and adds some additional detail to the `Failed to connect before the deadline` message to help users diagnose the issue.
Error messages are not i18n aware as is the case for many errors message throughout the app - adding i18n support to the error messages can be handled separately.
Fix #1564
Try connecting with an invalid cert.
Enhancement
> fix(onboarding): improved connection error messages

- services/grpc/grpc.js
- services/grpc/lightning.subscriptions.js
If we fail to subscribe to the channel graph after initial sync has completed keep retrying until we get a successful connection.
Fix #2226
Manually
Bug fix
> fix(grpc): setup channel graph stream after sync

- electron/preload.js
- renderer/components/Onboarding/Steps/ConnectionConfirm.js
- test/unit/utils/splitHostname.spec.js
- utils/splitHostname.js
- utils/validateHost.js
Resolve #2172
Resolve #2270 
Currently, ipv6 addresses are sanitized incorrectly when using lndconnect string or manual connection. E.g
`lndconnect://[1fff:0:a88:85a3::ac1f]:10009?cert=x&macaroon=y`
Manually
`lndconnect://[1fff:0:a88:85a3::ac1f]:10009?cert=x&macaroon=y`
Bugfix/enhancement
> fix(ui): ipv6 validation and formatting issues when connecting to a remote node

- config/default.js
Set default address type to Bech32
Address type is now configurable via the settings page. Users that don't want to use Bech32 can switch if they like.
Manually
Enhancement
> feat(wallet): set default address type to Bech32

- renderer/reducers/app.js
Retain selected theme on reload
This fixes a bug that occurs when you do `crtl+r` to reload the app in which the theme gets reset back to what it was when you launched the app= even if you have since changed it.
1. Launch the app
2. Change the theme
3. Reload with `crtl+r` and verify that your theme selection is retained
Bug fix
> fix(ui): retain selected theme on reload

- renderer/reducers/app.js
- renderer/reducers/settings.js
Wait for settings on app init
Prevents us from redirecting to the Initialiser before settings have been loaded from the database and ensures that if the user was logged into a wallet when they quit the app, they remain logged into it when then restart the app.
This preserves exist5ing functionality from master which got broken as part of the settings revamp.
Manually
Bug fix
> fix(app): wait for settings on app init

- package.json
- scripts/genIcons.js
- yarn.lock
Add ability to generate a specific SVG icon instead of re-generating all of them
Currently `genereate-icons` re-generates all icons every time, which is redundant since icons are added one by one to the project
Manually
`yarn generate-icon icons/icon.svg`
Devops change
> build(icons): add ability to generate specific icons

- renderer/components/Pay/Pay.js
- renderer/components/UI/CurrencyFieldGroup.js
- renderer/components/UI/TextArea.js
Fix pay form crash.
This fixes a bug that was causing the pay form to crash on load. The issue was related to some recent updates to the way that informed handled forward refs. Resolved by converting `CurrencyFieldGroup` to a stateless component and properly handling forward refs using `React.forwardRef`
Manually
Bugfix
> fix(ui): fix pay form crash

- renderer/components/Channels/ChannelCardList.js
- renderer/components/Channels/ChannelCardListItem.js
- renderer/components/UI/Card.js
- test/unit/components/UI/__snapshots__/Card.spec.js.snap
Display channel cards at equal heights
Fix #2327
Manually
UI enhancement
> fix(ui): display channel cards at equal heights

- renderer/components/Home/WalletUnlocker.js
Recent migration to `withRouter` HOC usage instead of `connected-router-dom` results in `staticContext` prop being added to wrapped components, which is not recognized as a DOM prop when spread onto `Form`
Dev tools monitoring
Refactor
> fix: dom props warning

- renderer/components/Activity/ActivityActions/ActivityFilter.js
- renderer/components/Settings/SettingsFieldsGeneral.js
- renderer/components/Settings/SettingsFieldsWallet.js
Use initialValue to set initial value for Select
Fix issue on Preferences page where clicking the `cancel` button in the action bar would not properly reset the value of the Select widgets.
Manually
Bug fix
> refactor: use initialValue to set initial value for Select

- config/default.js
- config/production.js
Currently, it's not possible to simultaneously run standalone LND and  Zap with a local setup on the same machine on Windows. At least with my current setup. Upon investigation, the issue appeared to be incorrect free p2p port resolution by `get-port`. Could be related to
https://github.com/sindresorhus/get-port/issues/8
Manually. Launch local lnd and then launch zap with neutrino wallet
Bugfix
> fix(lnd): allow to simultaniously run lnd and local zap locally on win

- renderer/components/App/App.js
- renderer/containers/App.js
- renderer/containers/Initializer.js
Suggested nodes list goes empty after logout because of app state reset. This PR fixes this by re-fetching suggested nodes every time the user logs into a wallet
Manually. Login into a wallet and then logout and then login again
Bugfix
> fix(ui): empty suggested nodes after logout

- renderer/components/Settings/SettingsMenu/SettingsMenu.js
- renderer/containers/Settings/SettingsMenu.js
- renderer/reducers/info.js
- renderer/reducers/lnd.js
- services/grpc/grpc.js
- services/grpc/lightning.subscriptions.js
- stories/containers/settingsmenu.stories.js
Use `busy` state of the wallet connectivity indicator if `synced_to_chain` is false to give the user more info on the current state of the wallet. This is especially useful when used with remote nodes. This PR also re-instates `getInfo` polling after initial sync is done, but does it in a less resource-consuming manner by reducing the polling interval
Manually. Connected to a node that was in a process of sync
Enhancement
> feat(ui): make wallet connection indicator more informative

- renderer/components/UI/GlobalStyle.js
On windows when resizing Windows to a minimum allowed height double scrollbars sometimes appear.
This PR fixes this issue
Manually
Bugfix
> fix(ui): prevent double scrollbars on windows

- renderer/reducers/invoice.js
This is another kick the can down the road fix to increase the number of invoices we will fetch until we get round to implementing pagination.
See Ref https://github.com/LN-Zap/zap-desktop/search?q=pagination&type=Issues
In the current release we had already increased to the `1000`. But there is a regression in `next` that resets this back to the default of `100`.
In this PR we bump it to `2500` to buy us some time.
Some users with large number of invoices have complained about invoices not showing in Zap (eg https://github.com/LN-Zap/zap-desktop/issues/2404)
Manually
Fix
> fix(wallet): fetch upto 2500 invoices

- renderer/containers/ModalStack.js
Add top and bottom padding to autopay modal
This fixes a display issue with the Autopay screen in which the scrollbars were wrongly positioned.
Enable autopay feature and verify page padding looks ok
UI Fix
> fix(ui): add top padding to autopay modal

- electron/main.js
- renderer/components/App/App.js
- renderer/components/Pay/Pay.js
- renderer/containers/App.js
- renderer/containers/Pay.js
- renderer/reducers/pay.js
Clear lightning link payment request after use
When a `lightning:` payment link is used we set `payment.payReq` in the state and we use this when the Pay form opens to autofill form. This state data is meant to be temporary and should be cleared after use to prevent the possibility of it being used again since the lightning payment link is a one-time action.
There is a bug caused by this in which the payment modal immediately opens again after closing.
1. Click on a lightning payment link
2. Try to close the Pay modal
Bug fix
> fix(wallet): clear lightning link payment request after use

- webpack/prod/main.config.js
Ensure NODE_ENV=production for prod build
Build made with `yarn package` has dev tools enabled when it should not.
`yarn package`
Build fix
> build(webpack): ensure NODE_ENV=production for prod build

- renderer/components/UI/CloseButton.js
- renderer/themes/util.js
- test/unit/components/UI/__snapshots__/Modal.spec.js.snap
- use primary colour for primary button
- use primary colour for close button
Fix funky looking dialog button (seen when lnd crashes)
Storybook
**Before:**
**After:**
UI fix
> fix(ui): use primary colour for dialog buttons

- renderer/components/Settings/SettingsFieldsWallet.js
- renderer/reducers/ticker.js
- test/unit/utils/rateProvider.spec.js
- utils/fiat/rateProvider.js
- utils/rateProvider/index.js
- utils/rateProvider/providers.js
- utils/rateProvider/requestTicker.js
- utils/rateProvider/requestTickerWithFallback.js
Always use fallback providers when fetching ticker data.
fix #1783
Manually
Enhancement
> fix(walet): ensure fallback when ticker provider is unavailable

- renderer/reducers/activity.js
- renderer/reducers/payment.js
Use selector for sending payments
Entries in sendingPayments state are not suitable for direct display. We use a selector to decorate them with additional/missing information but that selector was not being used.
Manually - make a ln payment and verify app doesn't crash after clicking send
Bug fix
> fix(wallet): use selector for sending payments

- renderer/components/Onboarding/Onboarding.js
- renderer/components/Onboarding/Steps/components/Container.js
- renderer/components/UI/Wizard.js
Ensure onboarding next button fully clickable
This addresses a bug in which the `Next` button in several of the onboarding steps is not fully clickable (specifically, the left hand edge of the button). This happens because the form wizard content is being absolutely positioned over the top of the buttons.
This affects the steps that are wrapped in the `Container` element such as `ConnectionType`, `BackupSetup` and `BackupSetupLocal`
Manually
UI fix
> fix(ui): ensure onboarding next button fully clickable

- renderer/components/Home/WalletLauncher.js
Alert user to the fact that the probably don't want to click on the delete button by using the danger (red) button variant.
Using red for destructive actions is a fairly typical design pattern and we already do this in the delete wallet modal for example.
Manually
**Before:**
**After:**
> refactor: use danger variant for delete wallet button

- renderer/components/Home/WalletSettingsFormLocal.js
- renderer/components/Home/WalletSettingsFormRemote.js
- renderer/components/UI/LndConnectionStringEditor.js
Adjust sizes of launchpad inputs.
Input sizes a bit wonky and inconsistent.
Manually
**Before:**
**After:**
UI fix
> fix(ui): adjust sizes of launchpad inputs

- renderer/reducers/activity.js
- renderer/reducers/transaction.js
Ensure we use decorated selector for transactions sending in the activity list. Fixes issue similar to https://github.com/LN-Zap/zap-desktop/pull/2458
App crashes after sending onchain payment
Make on-chain payment
Bug fix
> fix(wallet): use decorated selector for transactions sending

- package.json
- scripts/fetch-lnd-for-packaging.js
- scripts/genIcons.js
The `generate-icons` script is broken since switching to lodash subpackage import style. Convert all imports to ES module imports and use babel when running the script.
The `generate-icon` script is broken since.
run `yarn generate-icon /path/to/icon`
Bug fix
> refactor: fix lodash import in generate-icon script

- renderer/reducers/activity.js
Though the activity search was improved recently we can still do better.
The PR adds the following improvements:
1. Makes search case-insensitive
2. Allows search by memo field
3. Allows search by type field (invoice, payment etc)
4. Allows search by date
5. Delivers perf optimization of the search process
A little more on search by date.
Currently, we don't have an ability to filter activity by date range, which is quite a common use case.
This PR instead adds search by date.
The current implementation has some limitations though. The biggest one is that it currently has no intl support because search is performed against a raw dataset and date localization happens at the UI level. This can be addressed by future PR since it requires some more refactoring.
Manually
For instance type …
> feat(activity): improve search

- renderer/components/Home/WalletLauncher.js
Use Informed formApi.reset to do the wallet settings form reset.
This resolves an issue in which the cancel action bar button was not working when editing a field that was initially empty.
Test all kinds of different scenarios of clicking the cancel button when editing wallet settings on the launchpad.
Bug fix
> fix(launchpad): ensure full form reset on cancel

- renderer/components/Onboarding/Steps/ConnectionConfirm.js
- renderer/components/UI/LndConnectionStringInput.js
Prevent app from crashing when using a valid LND connect with leading or trailing spaces
Manually
Bugfix
> fix(ui): ensure lndconnect string is trimmed

- renderer/components/Activity/PaymentModal/PaymentModal.js
- renderer/components/Activity/PaymentModal/messages.js
- translations/da-DK.json
- translations/en.json
- translations/es-ES.json
- translations/ga-IE.json
Add CopyButton to preimage in Payment modal
fix #2490
Manually
Enhancement
> fix(ui): add CopyButton to preimage in Payment modal

- electron/controller.js
- electron/main.js
- renderer/reducers/app.js
Correctly shutdowns the app on Windows and Linux. Previously renderer window was closing before having a chance to respond to `terminateApp` IPC event causing `electron` process to become stuck.
Manually
Bugfix
> fix: electron shutdown flow on win and linux

- package.json
- webpack/webpack.config.dll.js
- yarn.lock
Fork @grpc/proto-loader to @ln-zap/proto-loader and remove the code which attempts to unconditionally load in additional google grpc proto files. These files are not needed and the dynamic require does not function properly in the context of webpack+electron.
@grpc/proto-loader attempts to require code from a relative node_modules directory instead of from the electron root and fails due to an incorrect include path.
run `yarn package` to build a package. Then try to run the build with a `cwd` other than `zap-desktop` repo root.
Fix
> fix(grpc): do not include extra google protos

- renderer/components/Activity/ActivityListItem.js
- renderer/components/Activity/Payment/Payment.js
- renderer/components/Activity/PaymentModal/PaymentModal.js
- renderer/containers/Activity/Payment.js
- renderer/reducers/activity.js
- renderer/reducers/invoice.js
- renderer/reducers/payment.js
- renderer/reducers/transaction.js
- renderer/reducers/utils.js
Old versions of lnd provided a `payment.value` prop that had the payment value. In 0.5.1 this was replaced with `.value_sat` and `.value_msat`.The old `payment.value` prop is still supported but marked as deprecated.
Stop using deprecated lnd payment props to future proof things.
Make payments
Open existing payments
Verify payments sending functionality works correctly
Verify payments look correct on the activity list and in the payment modal
Refactor
> refactor: stop using deprecated lnd props

- .huskyrc
- package.json
- yarn.lock
This PR removes `lint-staged`.
As per https://github.com/LN-Zap/zap-desktop/issues/2231 lint-stage has a rather fatal issue that can result in a painful loss of work. The repo maintainers have shown little interest in fixing the problem. To mitigate the problem I have removed this dependency.
If you have our tooling setup correctly (including prettier) then lint-staged should not really be needed as linting and autofixing will happen every time you save a file. Any issues that do get through the new locally and make their way in to a commit will be caught by our test suite.
fix #2231
Manually
devops improvement
> build(lint): remove lint-staged and run lint in pre-push hook

- renderer/components/UI/IntegerInput.js
This PR fixes two issues with the settings form:
1) After creating a new wallet and navigating to the preferences page and clicking the wallet tab the action bar shows up even though there are no changes.
2) conf targets are being saved as strings instead of numbers and this causes a prop-type error when they are used on the payment form
Manually
Bug fix
> fix(settings): ensure number fields use number type

- renderer/reducers/lnd.js
- services/grpc/grpc.js
Following a recent update to the node-lnd-grpc package `activateLightning` must now be manually called after creating a new wallet.
Update our createWallet action to properly handle this.
Fix bug where wallet hangs on `creating wallet` indefinitely after successfully creating a new wallet.
Manually
Bug fix
> fix(grpc): activate Lightning grpc after init wallet

- renderer/components/Profile/ProfilePaneNodeInfo/ProfilePaneNodeInfo.js
- renderer/containers/Profile/ProfilePaneNodeInfo.js
- renderer/reducers/info.js
- services/grpc/lightning.methods.js
Split the version string out from the commit identifier and display over two lines with the commit identifier in a smaller lighter font.
When connected to a node that is running a custom lnd build the lnd version string as reported by `getInfo` is quite long since it contains the version string and commit identifier.
This causes a display glitch on the node profile page when viewed at the default window size.
Manually
**Before:**
**After:**
Bug fix
> fix(ui): separate version/commit on profile pane

- renderer/reducers/lnd.js
In order to effectively render the wallet we must know which wallet is being rendered (which wallet is the active wallet). This chance ensures that we set the current active wallet before registering that the lnd gRPC Lightning interface has been successfully connected to, since this is the trigger that use for redirecting between the onboarding process and the wallet screen.
Random crash when connecting to 
```
Uncaught TypeError: Cannot read property 'type' of undefined
at SettingsMenu (SettingsMenu.js?addf:82)
at renderWithHooks (react-dom.development.js:12939)
at mountIndeterminateComponent (react-dom.development.js:15021)
at beginWork (react-dom.development.js:15626)
at performUnitOfWork (react-dom.development.js:19313)
at workLoop (react-dom.development.js:19353)
```
Conceptually …
> fix(ui): ensure active wallet is set early

- renderer/components/UI/MainContent.js
- renderer/components/UI/Modal.js
- renderer/components/UI/Sidebar.js
- test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
- test/unit/components/UI/__snapshots__/Modal.spec.js.snap
- test/unit/components/UI/__snapshots__/Sidebar.spec.js.snap
Ensure sidebar/main sizes respected
This fixes a glitch in the `Sidebar` & `MainContent` components which manifests when trying to position a sidebar on the right side of the main content area or when trying to use sidebars with different widths. Previously, with the sidebar positioned on the right it would display over the top of the modal close button. Also, sidebar width was not being properly applied.
Manually
Bug fix
> fix(ui): ensure sidebar/main sizes respected

- renderer/reducers/pay.js
- utils/crypto.js
Ensure routes extract from queryroutes and add add 1 sat buffer to fee limits
Route information is not being correctly extracted from `queryroutes`, so ln fee estimations are not working.
Additionally, ensure that the fee limits that we apply are 1 sat larger than estimates returned by query routes. This provides a buffer incase the actual fee is over the estimated sat limit by some msats.
Manually
Bug fix
> fix(wallet): fix LN fee estimates and add 1 sat buffer to fee limits

- package.json
- yarn.lock
Update all lodash variants to 4.17.14. This is meant as a temporary override until all of our dependencies get around to upgrading.
Update lodash dependencies to avoid CVEs found in the 'lodash' package.
Manually
Security upgrade
> fix(deps): update all lodash variants to 4.17.14

- docs/ADVANCED.md
Update `Advanced Usage` docs to use `yarn` instead of `npm`
- changed usage of `npm` to `yarn`
- updated node version to `>= 12`
> fix(docs): change npm to yarn in advanced usage docs

- renderer/components/UI/CurrencyFieldGroup.js
- renderer/components/UI/Dropdown.js
- renderer/containers/UI/CryptoSelector.js
- renderer/reducers/ticker.js
Currently, when switching between mainnet and testnet wallets at some point wrong units are displayed in the UI (BTC instead of tBTC etc. for the testnet wallets)
Manually. Switch between wallets that use different networks
Bugfix
> fix: use correct crypto unit names based on network

- renderer/components/Activity/Activity.js
Simplify the activity list rendering and improve performance.
#2584 introduced uniform height for activity items, allowing us to get rid of react-virtualized `CellMeasureer` infrastructure and speed up rendering
Manually. 5000 tx node strikes again
Perf improvement
> perf: simplify activity list renderer

- config/default.js
- stories/containers/home.stories.js
This prevents spending unconfirmed funds by default. Ref https://github.com/lightningnetwork/lnd/issues/3341
fix #2591
fix #2531
Manually
Fix
> fix(lnd): increase autopilot minconfs to 1

- README.md
- package.json
Remove .deb linux target
Currently we distribute both a `.deb` file and a `.AppImage` file for linux. This is unnecessary and there are a couple of issues with this:
1) AppImage is already supported on Debian based distributions, so we are offering a redundant choice to users.
2) AppImage is supported in many more places than `.deb` files (in addition to all the places where .deb files run) so the .deb offers nothing over and above the AppImage
3) Linux users have 4 downloadable assets to choose from on our releases. It bloats the releases page and makes it look intimidating. There is no reason for users to choose - they can just run the AppImage file.
4) Increased maintenance effort to test both .deb and .AppImage releases.
5) Increased build times to build multiple linux targets.
`yarn …
> build: remove .deb linux target

- renderer/components/Channels/ChannelData.js
Resolves #2581 partly
This PR changes channel card view from always showing funding tx to showing last on-chain tx. So closing tx for closing channels and funding tx for the rest
Manually
UX Enhancement
> fix(ui): show last on-chain updating tx in channels card view

- icons/layout-list.svg
- renderer/components/Icon/LayoutList.js
Ensure that the hamburger icon is not cut off at the bottom.
fix #2656
Manually
**Before:**
**After:**
UI fix
> fix(ui): improve channel list hamburger icon

- docs/ADVANCED.md
- docs/CONFIG.md
Add documentation for configuration options
Create a page that we can point people to when they ask how to change default config values.
Docs
> docs: add documentation for configuration options

- renderer/components/Pay/Pay.js
- renderer/components/Request/Request.js
Left align help text in Pay and Request forms in order to prevent strange looking gaps in the text at certain screen sizes.
fix #2655
Manually
UI Fix
> fix(ui): remove gaps in pay/request form help text

- scripts/lnd-release/.goreleaser.yml
This just updates our lnd build script to remove the 386 targets which we are no longer using.
Clean up
> refactor: remove unused 386 lnd build targets

- electron/updater.js
Ensure autoupdate setting is honoured
Autoupdates are not working since 0.5.0 due to mishandling of the autoupdate config values.
Manually - run add in production mode with debug logging enabled and verify that the autoupdate logs look correct when starting the app and after editing the autoupdate config.
Big fix
> fix(app): ensure autoupdate setting is honoured

- renderer/components/Home/WalletLauncher.js
Not only it doesn't make sense to delete wallet while it's launching, but it doing so can cause weird bugs. This PR makes `delete wallet` button to be disabled while the wallet is in the launching state
Manually
Bugfix/Enhancement
> fix(ui): disable delete wallet button in launching state

- renderer/components/Activity/ErrorDetailsDialog.js
- renderer/components/Autopay/AutopayCreateModal.js
- renderer/components/Channels/ChannelCloseDialog.js
- renderer/components/Home/DeleteWalletDialog.js
- renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
- renderer/components/UI/Dialog.js
- renderer/hooks/useCloseOnUnmount.js
Close dialogs with Escape key.
This was already in place for some dialogs. PR updates to set as standard behavior.
fix #2677
Manually
Enhancement / Refactor
> feat(ui): close dialogs with Escape key

- utils/promiseTimeout.js
Fixes corner case with `promiseTimeout` which prevents node.js process from exiting because of hanging timeout. This PR ensures timeout is cleared as soon as promise race resolves
Manually
Bugfix
> fix: ensure timeout is cleared asap in promiseTimeout

- package.json
- yarn.lock
Add grpc connection timeout to avoid ui getting stuck when connecting to a hanging LND node.
Manually. Tried to connect to a hanging node and waited for 60 secs
Bugfix
> fix(grpc): add connection timeout

- renderer/components/UI/LightningInvoiceInput.js
properly validate msat invoices
Invoices that only contain an msat amount are not validating in the pay form
Create an invoice on the blockstream store and try to pay it.
Fix
> fix(wallet): properly validate msat invoices

- renderer/containers/Channels/ChannelCloseDialog.js
Pretty straightforward change which just makes sure csv_delay property exists in the channel object before returning it.
Addresses #2692
> fix(channels): ensure csv_delay property is defined before returning it

- renderer/components/UI/QRCode.js
- test/unit/components/UI/__snapshots__/QRCode.spec.js.snap
Made sure QR code is always centered perfectly using some CSS magic.
Fixes #2700
Manually and unit tests.
> fix(ui): make sure QR code is centered perfectly

- electron/updater.js
Ensure that we set electron-updater `allowDowngrade=false` after setting the update channel, since `autoUpdater.channel` is a setter which explicitly sets `allowDowngrade=true`.
See https://github.com/electron-userland/electron-builder/blob/v20.41.0/packages/electron-updater/src/AppUpdater.ts#L73-L91
If you try to run a yet unreleased version of the app, it constantly tries to download the previous version of the app.
Manually
Bug fix
> fix(app): disable app downgrade feature

- renderer/components/Pay/PaySummaryLightning.js
- test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
Align amount and crypto unit on LN pay summary page and use crypto unit selector. This is more consistent with the on chain payment summary.
Fix display glitch and make behaviour more consistent with rest of app.
Manually
**Before:**
**After:**
Fix
> fix(ui): align amount and crypto unit

- renderer/components/Autopay/Autopay.js
Correctly apply blue theme overrides
App crashes when trying to access autopay feature.
Enable autopay feature and try to navigate to that part of the wallet ui.
Bug fix
> fix(autopay): correctly apply blue theme overrides

- package.json
- renderer/components/Onboarding/Steps/WalletRecover.js
- services/grpc/grpc.js
- utils/promiseTimeout.js
- yarn.lock
When recovering a wallet wallet ensure that we show the passphrase form in the case that that there is an error due to a missing or invalid passphrase. Show an error dialog incase of all other errors.
Unable to recover encrypted wallet
Try recovering this encrypted wallet:
```
1. abstract   2. solution   3. ramp     4. repeat
5. sentence   6. soup       7. quick    8. trend
9. nation    10. cute      11. bridge  12. note
13. ritual    14. century   15. game    16. sponsor
17. sea       18. impact    19. game    20. wrist
21. follow    22. rail      23. lemon   24. curious
password: password
passphrase: passphrase
```
Bug fix
> fix(onboarding): show recover wallet passphrase form

- renderer/components/Form/Input.js
- renderer/components/Form/TextArea.js
Looks like there was a change during a recent refactor where the `{...otherProps}` piece was moved from the bottom to the top which broke the connection string component. This PR fixes it but I can guarantee it doesn't break something else if that change of moving `{...otherProps}` was intentional and if some other components are relying on this.
fix #2785
Manually
> fix(ui): make sure connection string visibility toggle is respected

- electron/menuBuilder.js
After interacting with the application menu (for example, clicking `Preferences` item) React app loses focus which prevents it from receiving keyboard events and as a result causes issues like keyboard shortcuts not working. This PR adds a global application menu `click` handler that ensures React is focused after `click` handlers
Manually.
Bugfix
> fix: ensure app is focused after menu interaction on windows/linux

- .eslintrc.js
- renderer/components/Form/InputContainer.js
- renderer/components/UI/CenteredContent.js
Importing components from `rebass` directly causes all sorts of issues. This lint rule enforces usage of `rebass/styled-components` instead
`yarn lint`
ESLint rule update
> chore: add rebass to restricted imports rule

- .storybook/patchedReactRedux.js
- .storybook/webpack.config.js
This PR monkey patches `react-redux` connect to use `defaultMergeProps`  that prioritizes `ownProps` over `stateProps`
Simplify sb testing by allowing to mock redux actions
`yarn storybook`
Devops
> chore: allow overriding state props in sb components

- README.md
Been getting reports that our Slack invite expired, so I generated a new one and updated it
> fix(slack): update slack link

- renderer/components/Form/OpenDialogInput.js
- renderer/hocs/withOpenDialog.js
`dialog.showDialog` was signature was changed in `electron 6` and now is async. Our code relies on `v5` api (which is used in master) so `OpenDialog` inputs functionality is currently broken in `next`. This PR updates the code to use `v6` api.
Manually
Bugfix
> fix(ui): open dialog inputs

- renderer/components/UI/Select.js
It seems that our `Select` component is missing one important piece: syncing its value with the underlying form field in case the latter is changed programmatically.
For example consider this:
1. Go to wallet settings
2. Select some invoice expiry period
3. Press cancel
Form will reset, but select will show stale value.
This PR attempts to add sync between underlying form field and select by leveraging downshift control props:
https://github.com/downshift-js/downshift#control-props
PS: These kind of changes are known to be tricky and usually introduce some other corner cases, so it maybe worth to test this for a while before merging
Manually
Bugfix
> fix(select): correctly update select when underlying field changes

- renderer/components/Form/RadioGroup.js
fix #2919
In master `InputLabel` had a `mb` of `2` which is not present in next's `Label` counterpart
https://github.com/LN-Zap/zap-desktop/blob/master/renderer/components/UI/InputLabel.js#L20
Manually
Bugfix
> fix(ui): restore RadioGroup label mb

- renderer/containers/Channels/ChannelCreate.js
- renderer/reducers/channels.js
- services/grpc/lightning.methods.js
Close `Create channel` modal after channel opening is finished (either successful or not). This functionality was broken some time during `Modal Stack` refactoring. Also remove redundant `openChannel.data` handler which was causing `comlink` error. 
```
grpc.services.Lightning.once(	
'openChannel.data',	
proxyValue(data => dispatch(pushchannelupdated(data)))	
)
```
Is redundant because `openChannel` call resolves with exactly same data as per
https://github.com/LN-Zap/zap-desktop/blob/10440046872a95fbe3b33a11ac0f923d3978a25b/services/grpc/lightning.methods.js#L178
Fix #2920 
Manually
Bugfix
> fix(ui): close channel create modal after channel opening is finished

- renderer/components/Channels/ChannelCloseDialog.js
- renderer/components/Home/DeleteWalletDialog.js
- renderer/components/Onboarding/Steps/components/ErrorDialog.js
- renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
- renderer/components/UI/Dialog.js
- test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
> fix(ui): set delete wallet header width to same as content width

- renderer/reducers/pay.js
This PR adds the `use_mission_control` option to the lnd api call of `queryRoutes` so our fee calculations will be made using optimal routes.
We (sparkswap) started seeing users of Zap-Desktop having failing payments that additionally continue to try routing the payment through the same users/paths.
Working with @treygriffith and @JimmyMow, we suspect that the issue occurs where we use `queryRoutes` to get a fee estimate of the route. We use this fee estimate as the `feeLimit` to sendPayment, which then inadvertently selects these bad routes to forward the payment.
By using `use_mission_control` we are hoping that the fee gathered from `queryRoutes` will better reflect valid routes and prevent users from having failing payments during the 3 retries provided by Zap 
Regtest, local …
> perf(routing): update query routes to use mission control

- electron/migrator.js
- renderer/reducers/wallet.js
- utils/lndConfig.js
fix(app): store temp wallets in os tmpdir
temp wallets are single use and should not be reused. These wallets never get fully initialised since they are only used to generate a seed. This can cause problems when upgrading lnd as lnd's migration scripts have been known to assume that the wallet had certain data files that only get created after initialising the wallet.
Fix
> fix(app): store temp wallets in os tmpdir

- test/unit/utils/scheduler.spec.js
- utils/scheduler.js
This PR fixes potential issue with scheduler when using tasks without `taskId`. Such issue could occur because functions can't be used as prop keys in JS objects. Currently it seems that our codebase wasn't using scheduler in this way so no bugs ensued.
Manually and unit tests
Bugfix/refactor
> refactor: simplify scheduler code and handle key cornercase

- renderer/components/Form/OpenDialogButton.js
- renderer/components/Form/OpenDialogInput.js
fix #2987
Manually
Layout bugfix
> fix(ui): incorrect open btn placement in OpenDialogInput errorneus state

- config/default.js
Switch to testnet1 and testnet2 neutrino peers
t1 and t2 have been brought back online and are using a legacy version of bitcoind to serve neutrino filters to 5.x clients.
t3 and t4 have been updated to serve updated filters for the upcoming 0.6 release and are no longer compatible with lnd 0.7.
Manually - sync a testnet neutrino node
Fix
> fix(lnd): switch to testnet1 and testnet2 neutrino peers

- services/neutrino/neutrino.js
Use `--neutrino.addpeer` instead of `--neutrino.connect` to connect to our neutrino nodes. This tells lnd to add our peers but also to seak out additional peers from the network.
This will help prevent syncing issues if our peers are offline.
Manually
Fix
> fix(lnd): connect to additional neutrino peers

- config/default.js
- renderer/components/Pay/Pay.js
- renderer/reducers/payment.js
- test/unit/utils/crypto.spec.js
- utils/crypto.js
In the case the queryRoutes gives us an unplayable route we retry the payment a couple of times. When doing the retries, increase the fee limit to increase the chance of payment success.
fix 32952
Manually
Fix
> fix(wallet): increase fee limit on payment retries

- renderer/components/Channels/messages.js
- translations/en.json
Address "bonus" issue in #3045
Issue #3045 
Manually
> fix(i18n): change open channel status label to "online"

- stories/Provider.js
Ensure window.Zap.getPlatform exists in storybook
Storybook not working due to the fact that `window.Zap.getPlatform` doesn't exist but is now used in some components.
`yarn storybook`
Fix
> refactor: ensure window.Zap.getPlatform exists in storybook

- renderer/components/Pay/Pay.js
- renderer/components/Pay/PayAddressField.js
- renderer/components/Pay/PayPanelBody.js
- renderer/components/Request/Request.js
- test/unit/components/Pay/PayAddressField.spec.js
- test/unit/components/Pay/__snapshots__/PayAddressField.spec.js.snap
- test/unit/components/Pay/__snapshots__/PayPanelBody.spec.js.snap
Don't validate pay/request forms unless there are some values to validate. This prevents the form showing errors when closing the modal in the case that nothing has been entered into the form yet.
fix #3016
Close pay and receive forms without entering any values and verify form fields do not turn red.
Fix
> fix(ui): no form error when form is empty

- renderer/components/Onboarding/Steps/messages.js
- translations/cs-CZ.json
- translations/da-DK.json
- translations/de-DE.json
- translations/en.json
- translations/es-ES.json
- translations/fr-FR.json
- translations/hr-HR.json
Update misleading wallet unlock description.
Change from:
`Set a password to encrypt your wallet. This password will be needed to unlock Zap in the future.`
To:
`Set a password to encrypt your wallet. This password will be needed to unlock the wallet in the future.`
NOTE: I've also updated other text for other languages that have provided translations. Whilst doing so I noticed that some of the other translations still included the phrase `looks like you are new here!`at the start of the text, which was removed from the english translation a while ago so I removed it from those translations too.
We now have a app-wide password feature which currently operates in addition to the wallet level password. The language on the password setup screen as part of wallet onboarding should be more …
> Update misleading wallet unlock description

- renderer/components/Onboarding/Steps/BackupSetup.js
- renderer/components/Onboarding/Steps/WalletCreate.js
- renderer/components/Onboarding/Steps/WalletRecover.js
- renderer/components/Onboarding/Steps/components/ErrorDialog.js
- renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
Use fixed positioning for dialogs that are displayed in the onboarding process to ensure that they appear on top of the wizard controls.
fix #3119
Check dialog display in onboarding process and in the storybook
Fix
> Ensure onboarding dialogs display on top of wizard controls

- renderer/components/Onboarding/Steps/SeedConfirm.js
Don't re render SeedConfirm on mount.
Fix #3118
Manually
Fix
> Don't re-render SeedConfirm on mount

- renderer/reducers/address.js
Ensure failures and successes are properly handled in initAddresses. Wait until all addresses have been fetched/generated before dispatching success action.
Fix #3116
Manually
Fix
> Improve address generation error handling

- .eslintrc.js
Upgrade consistent-return from warn to error
All `consistent-return` lint violations have been fixed, so upgrade this rule from warn to error to prevent new issues creeping into the codebase.
manually
lint update
> Upgrade consistent-return from warn to error

- utils/lndConfig.js
Skip generation of lndconnect qrcode links for temporary wallets.
Temporary wallets are only used for the purpose of generating a new seed and will not support QR code generation as they will never be running long enough to have a certificate or macaroon generated.
Create new local wallet and verify there is no console warning when starting up the temp wallet to generate the seed.
Fix
> Skip generation of lndconnect qrcode links for temporary wallets

- electron/main.js
- renderer/reducers/pay.js
Support lightning invoices that are encoded within a bip21 bitcoin uri.
https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#encoding-overview
> If a URI scheme is desired, the current recommendation is to either use 'lightning:' as a prefix before the BOLT-11 encoding (note: not 'lightning://'), or for fallback to Bitcoin payments, to use 'bitcoin:', as per BIP-21, with the key 'lightning' and the value equal to the BOLT-11 encoding.
The spec is pretty unclear about exactly how this should work, but there is some discussion about it here:
https://github.com/lightningnetwork/lightning-rfc/issues/323
Also some related discussion about this here:
https://www.reddit.com/r/Bitcoin/comments/8wyloi/making_lightning_invoices_backwards_compatible/
Ultimately at …
> Support bolt11 invoices encoded in bip21 uris

- package.json
- renderer/themes/base.js
- test/unit/components/Home/__snapshots__/CreateWalletButton.spec.js.snap
- test/unit/components/Home/__snapshots__/NoWallets.spec.js.snap
- test/unit/components/UI/__snapshots__/ActionBar.spec.js.snap
- test/unit/components/UI/__snapshots__/Button.spec.js.snap
- test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
- yarn.lock
Resolves #3127 
Currently we use `:focus` selector to described focused state for components. This is used for accessibility support. The side effect is that components also transition to a focused state on click, which causes visual issues in some cases. This pr solves the issue by leveraging `focus-visible` pseudostyle polyfill which was specifically designed to handle such cases.
Manually
Bugfix
> Fix components focus issue

- .travis.yml
- appveyor.yml
- package.json
- resources/mac/entitlements.mac.inherit.plist
- scripts/afterSignHook.js
- yarn.lock
Enable notarization for mac builds
Mac Catalinia has made it a requirement for apps to be notarized by apple and by default will not allow installation of apps that have not been notarized.
Travis build
Build process
> Enable notarization for mac builds

- renderer/components/Form/util.js
- renderer/components/Pay/PaySummaryLightning.js
- renderer/components/Request/RequestSummary.js
- renderer/reducers/activity.js
- renderer/reducers/autopay.js
- renderer/reducers/invoice.js
- renderer/reducers/payment.js
- services/grpc/lightning.methods.js
- utils/crypto.js
Ensure failed payments marked as failed
Generate a unique payment id for sending payments to enable more accurate tracking of payments across retry attempts.
Fix #3142
Manually
Fix
> Ensure failed payments marked as failed

- renderer/components/Pay/PaySummary.js
- renderer/components/Pay/PaySummaryLightning.js
- renderer/reducers/pay.js
Ensure fee rate is displayed as `unknown` if no routes are found.
Fix #3154
Manually
Bug fix
> fix(wallet): present correct fee when no route

- renderer/components/UI/Countdown.js
- stories/components/countdown.stories.js
- test/unit/components/UI/Countdown.spec.js
- test/unit/components/UI/__snapshots__/Countdown.spec.js.snap
The largest number (ms) supported by setInterval is 2147483647. If countdown expire date is outside of this range do not use a timer.
Note: Technically if a user was to keep a countdown on the screen for over 24 days it would display an inaccurate expired message, but in practice this is probably such an edge case that it's not worth investing time into addressing at this point.
Fix #3144
Manually
Fix
> Ensure correct expire date for invoices with far future expiry

- test/unit/components/UI/Countdown.spec.js
- test/unit/components/UI/__snapshots__/Countdown.spec.js.snap
Use mock date in countdown tests to ensure predictability.
The `Countdown` component applies offsets to the current date. Unit tests should mock the current date to a predictable value to ensure that tests don't give varying results depending on when they are run.
`yarn test-unit`
Test suite fixes.
> test(unit): use mock date in countdown tests

- renderer/components/Profile/ProfileMenu/ProfileMenu.js
- renderer/components/Profile/ProfilePage/ProfilePage.js
Disable sign message functionality for local wallets.
Local wallets are private nodes and aren't visible in the network graph which renders "sign message" a useless feature for them, because of `verifymessage` implementation details in LND no one will be able to verify such a message.
Manually
UI fix
> Disable sign message functionality for local wallets

- renderer/hooks/useTimeout.js
- services/grpc/grpc.js
- services/grpc/lightning.subscriptions.js
- test/unit/utils/scheduler.spec.js
- utils/scheduler.js
- utils/streamify.js
Improve `synced_to_chain` status polling
Other:
Add ability to execute tasks immediately after they are added via `scheduler` (`runImmediately` flag)
Fix react hook warning and comments typos
If the user connects to a wallet that is already synced, it will continue to do the fast polling for up to 10 minutes or so - until the next block comes in.
Problem is that the info stream only emits data when something in the result changes, so when we first set it up if the chain is already synced then no event will be emitted until block_hash changes
Manually. Connecting to different types of wallets
Bugfix/Refactor
> Fix getInfo subscription cornercases

- renderer/workers/grpc.worker.js
Ensure that protobuf has Long support
NOTE: This PR only enables long support. In order to leverage it we will also need to switch to handling long as Number to handling as String
Protobuf assumes that long.js is either available on the global scope or available to be required. However, when used from the context of one of our web workers neither of these assumptions is true. In order to ensure that Long support is available in protobuf we manually configure protobuf here, before it is used.
See https://github.com/protobufjs/protobuf.js#browserify-integration
This ensures that large numbers (such as those returned from chan_id props) can be properly handled without rounding.
Manually
Fix
> fix(grpc): ensure that protobuf has Long support

- renderer/components/Activity/Activity.js
- renderer/components/Activity/ErrorDetailsDialog.js
> fix(ui): center failed payment error modal dialog

- electron/preload.js
Current help page link leads to old docs which 404. This fixes that.
> fix: update help page link

- electron/walletBackup/gdrive/gdriveApi.js
Set user-agent to `Chrome` for google oauth
fix #3342
Manually
> Set user-agent to `Chrome` for google oauth

- renderer/components/Activity/Transaction/Transaction.js
Prevent app from crashing if there is a transaction whose number of confirmations is unknown or is less than the configured onchain finality settings.
Fix https://github.com/LN-Zap/zap-desktop/issues/3277
Fix https://github.com/LN-Zap/zap-desktop/issues/3258
Fix https://github.com/LN-Zap/zap-desktop/issues/3195
Change default config from:
```js
onchainFinality: {
pending: 0,
confirmed: 1,
},
```
to
```js
onchainFinality: {
pending: 1,
confirmed: 3,
},
```
And then restart the app and make an on-chain transaction.
App will crash with `Cannot read property 'color' of undefined at` error.
Bug fix
> Display transaction as unconfirmed if confs less than min finality

- config/default.js
- renderer/components/Channels/ChannelCreateForm.js
- renderer/components/Pay/Pay.js
- renderer/components/Pay/PayAmountFields.js
- renderer/components/Pay/PayPanelBody.js
- renderer/components/Pay/PaySummary.js
- renderer/components/Pay/PaySummaryLightning.js
- renderer/components/Pay/PaySummaryOnChain.js
- renderer/components/UI/Value.js
- renderer/reducers/info.js
- renderer/reducers/pay.js
- renderer/reducers/payment.js
- services/grpc/grpc.js
- services/grpc/router.methods.js
- test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
- test/unit/utils/btc.spec.js
- test/unit/utils/crypto.spec.js
- utils/btc.js
- utils/coin.js
- utils/crypto.js
- utils/fee.js
And implementation of payment probing.
Implements the recommendations from LL to use payment probing in order to determine an accurate fee estimate along a routable path.
Payment probing will only be used for lnd nodes on version 0.7.1 and above as it requires improved error handing provided by the new Router api.
See https://github.com/lightningnetwork/lnd/pull/2537 for context.
Improve fee estimate accuracy.
Manually
Enhancement
> Use payment probing to improve fee estimate

- renderer/components/Pay/PayPanelFooter.js
- test/unit/components/Pay/__snapshots__/PayPanelFooter.spec.js.snap
Ensure pay form submit button is not disabled on address step when going back from the amount step
fix #3176
Manually
Fix
> Fix pay form submit button disabled state

- renderer/components/Activity/Activity.js
- renderer/components/Activity/ActivityActions/ActivityActions.js
- renderer/components/App/App.js
- renderer/containers/Activity/Activity.js
- renderer/containers/Activity/ActivityActions.js
- renderer/containers/App/App.js
- renderer/reducers/activity/reducer.js
- renderer/reducers/activity/utils.js
- renderer/reducers/invoice.js
Fix activity reloading so that it reloads existing items rather than loading a new page.
Also optimise our network, peer and balance reloads slightly so that we fetch less often and not at times when there is no need to.
Fix #3174
Manually
Fix
> Fix activity reloading

- renderer/reducers/balance/selectors.js
- renderer/reducers/transaction.js
Balance shows as double during channel force close.
What seems to happen is that once the force close channel maturity height is reached the return amount shows up in unconfirmed wallet balance AND in total limbo balance for a period before being moved from unconfirmed to confirmed and getting removed from total limbo balance.
This PR also fixes an issue with the desktop notifications and prevents notifications from showing that say you sent coins when you open or close a channel.
Fix https://github.com/LN-Zap/zap-desktop/issues/3310
Regtest
Fix
> Prevent duplicate channel balance during force close

- renderer/components/Pay/PaySummaryLightning.js
- renderer/components/UI/Link.js
- renderer/containers/Pay/PaySummaryLightning.js
- renderer/themes/base.js
- test/unit/components/UI/__snapshots__/Link.spec.js.snap
Ability to edit fee limit from pay summary. This is just a basic implementation that turns the fee limit into a link that takes you to the preferences page so that you can edit the fee.
A nice follow up enhancement might be to make it take you directly to the specific setting on the preferences page, or to make it editable directly on the page instead.
Manually
Feature
> Ability to edit fee limit from pay summary

- docs/CONTRIBUTING.md
Update dead Slack invite link.
Fix #3557
> docs: update Slack link

- renderer/components/Form/CurrencyFieldGroup.js
- renderer/components/Form/LightningInvoiceInput.js
- renderer/components/Pay/Pay.js
- renderer/components/Pay/PayAmountFields.js
- renderer/components/Pay/PayPanelBody.js
- renderer/components/Pay/PayPanelFooter.js
- utils/crypto.js
Adds ability to copy/paste a bip21 payment uri into the address field on the pay form.
We already support bit21 by clicking on an external link. The address field on the pay form should also support them so that it's easier to copy working payment links between devices.
Manually
- try bip21 from browser
- try copy/pasting bip21 into the form
- ensure standard bitcoin addresses work normally
- ensure ln invoices are unaffected
Enhancement
> Parse bip21 uris in pay address form

- renderer/reducers/info/selectors.js
Ensure node pubkey is correctly loaded from node info.
We're fetching the wrong key for pubkey from lnd node info since we updated to using cammel case with grpc (as per https://github.com/LN-Zap/zap-desktop/pull/3427)
Manually
Bug fix
> Ensure node pubkey is correctly loaded from node info

- renderer/components/Settings/Security/PasswordPromptDialog.js
- renderer/components/Settings/Security/SetPasswordDialog.js
- renderer/reducers/account/reducer.js
- renderer/reducers/account/selectors.js
- utils/sha256.js
Ensure password is stored in the keychain as hex encoded sha256 digest,.
Ref https://twitter.com/cryptonobo/status/1282019127876558848
It seems that as part of this commit https://github.com/LN-Zap/zap-desktop/commit/dc9c73611ba415dce0d4dde9b8f34f810a9c4f51 our `sha256digest` utility was updated to support multiple encoding mechanisms however as part of this the default encoding changed from a hex string to a buffer.
This was done in preparation for keysend support however in the process it broke the password encoding/decoding which expects passwords to be encoded as a hex string for storage in the keychain.
Manually - enable password, change password, disable password. Also, install 0.6.2, enable the password, then upgrade to 0.7.0 and verify that the password still works.
Bug fix
> Ensure password lock/unlock works again

- services/grpc/router.methods.js
Probes can return multiple htlcs but our code assumes there can only be one. This means that we can end up selecting a non-viable route sometimes.
Improve probe success rate.
Manually
Bug fix
> Selecting correct htlc from probe attempt

- renderer/containers/Channels/ChannelsMenu.js
- renderer/reducers/balance/selectors.js
Include limbo balance in balance breakdown
Limbo balance is currently not displayed 
Manually
**Before:**
**After:**
Bug fix
> Include limbo balance in balance breakdown

- renderer/reducers/channels/selectors.js
Ensures that "Total can send" and "Toal can receive" only include balances from active channels.
These numbers are wrong - they include amounts relating to inactive channels.
Manually
Fix
> Only count active channels as usable capacity

- renderer/reducers/index.js
- renderer/reducers/lnd.js
- renderer/reducers/payment/reducer.js
- services/grpc/grpc.js
- services/grpc/router.subscriptions.js
Fetch latest payment data if we detect an HTLC settlement event that was probably not triggered by us. 
Ensures that payments sent by other wallet clients show up immediately in the activity list.
fix #3420
Manually
Enhancement
> Fetch latest paymet on external htlc settle

- renderer/components/Activity/PaymentModal/Htlc.js
- renderer/components/Activity/PaymentModal/PaymentModal.js
- renderer/components/Activity/PaymentModal/Route.js
- renderer/components/Activity/PaymentModal/index.js
- renderer/components/Pay/PaySummary.js
- renderer/components/Pay/PaySummaryLightning.js
- renderer/containers/App/App.js
- renderer/containers/Channels/ChannelCreateForm.js
- renderer/containers/Pay.js
- renderer/containers/Pay/PaySummaryLightning.js
- renderer/containers/Pay/PaySummaryOnChain.js
- renderer/reducers/index.js
- renderer/reducers/pay/index.js
- renderer/reducers/pay/reducer.js
- renderer/reducers/pay/selectors.js
- renderer/reducers/payment/utils.js
Display route summary on payment probe summary screen.
Ability to see details of probed route before paying.
Manually
Enhancement
> Show payment route on probe summary

- package.json
- renderer/reducers/payment/utils.js
- services/grpc/router.methods.js
- utils/crypto.js
Patch lnd to support interceptors (stops penalising intermediate nodes that return `FailIncorrectPaymentAmount` or `FailIncorrectDetails`.
Generates probe hashes deterministically using the schema `sha256("probing-01:" || payment_hash)` (where `||` is the concatenation operator).
Make it possible to pay Breeze users that sit behind an htlc interceptor.
Manually
Enhancements
> Support for interceptor nodes

- renderer/components/Onboarding/Steps/ConnectionConfirm.js
- renderer/components/Onboarding/Steps/ConnectionDetails.js
- renderer/components/Onboarding/Steps/ConnectionDetailsManual.js
- renderer/components/Onboarding/Steps/ConnectionDetailsString.js
- renderer/components/Onboarding/Steps/Name.js
- renderer/containers/Onboarding/Steps/ConnectionConfirm.js
- renderer/containers/Onboarding/Steps/ConnectionDetails.js
- renderer/containers/Onboarding/Steps/ConnectionDetailsManual.js
- test/e2e/basic-ui.spec.js
- test/e2e/onboarding-connect-btcpay.spec.js
- test/e2e/onboarding-connect-lndconnect.spec.js
- test/e2e/pages/onboarding.js
Currently, when connecting to a remote mode, you cannot specify the wallet name, having ability to do it in onboarding process would be helpful
The feature request was requested in #1262 
Manually and via e2e tests
New feature: To allow adding wallet name in the onboarding process for external wallets
- [x ] My code follows the code style of this project.
- [x ] My commits have been squashed into a concise set of changes.
> Ability to add wallet name when connecting to remote node

- package.json
fix 3608
Adjusts the desktop file generated for AppImage to make sure it's inline with the format
Fixes #3608 
By running the AppImage generated after changes via https://github.com/TheAssassin/AppImageLauncher
> Adjust desktop icon name as per icon images

- renderer/components/Channels/ChannelCreateForm.js
Disable feature to adjust remote csv delay feat from #3679, to be moved in global settings in future.
> Disable remote csv delay option
