- README.md
Added location to lnd tls certificate file for windows
> Fix Added location to lnd tls certificate file for windows

- app/api/index.js
- app/lnd/methods/index.js
- app/reducers/ipc.js
- app/reducers/ticker.js
- app/routes/activity/components/Activity.js
- app/routes/activity/components/components/Invoices.js
- app/routes/activity/components/components/Payments.js
- app/routes/activity/containers/ActivityContainer.js
- app/routes/app/components/App.js
- app/routes/app/components/components/Form/Form.js
- app/routes/app/components/components/Nav.js
- app/routes/app/containers/AppContainer.js
- app/routes/wallet/components/Wallet.js
- app/routes/wallet/components/components/Channels/Channels.js
- app/routes/wallet/components/components/Channels/components/Channel/Channel.js
- app/routes/wallet/components/components/Channels/components/ChannelForm/ChannelForm.js
- app/routes/wallet/components/components/Channels/components/ClosedPendingChannel/ClosedPendingChannel.js
- app/routes/wallet/components/components/Channels/components/OpenPendingChannel/OpenPendingChannel.js
- app/routes/wallet/containers/WalletContainer.js
- test/reducers/__snapshots__/ticker.spec.js.snap
- test/reducers/ticker.spec.js
Have a current ticker using selectors based on whatever the current crypto being used is
> Refactor hard-coded tickers to currentTicker

- app/lnd/index.js
- app/lnd/subscribe/index.js
- app/lnd/subscribe/transactions.js
- app/main.dev.js
- app/reducers/ipc.js
- app/reducers/transaction.js
Subscribe to transaction events and listen for new events pushed to the client
> Subscribe to transactions

- app/components/Form/PayForm.js
- app/components/Form/PayForm.scss
- app/reducers/payform.js
- app/routes/app/containers/AppContainer.js
- package.json
- test/components/Form.spec.js
> feature(payform): add form validation to payform

- app/lnd/config/index.js
This commit adds support for Linux, this was the only thing I had to change to get it up and running.
> Linux support

- app/package.json
- app/yarn.lock
- package.json
- yarn.lock
Fixes:
- MarshallOfSound/electron-devtools-installer#64, #78 
- grpc/grpc-node#45
> Upgrade dependencies

- app/components/Peers/index.js
- test/components/Peers.spec.js
> Fix the Peers.spec to run green

- test/e2e/e2e.spec.js
> Fix e2e tests to run green

- .flowconfig
- app/main.dev.js
Main issue was main.dev's use of mainWindow.
> Fix flow to run green

- app/components/LndSyncing/LndSyncing.js
> fix(typo): accross -> across

- app/components/Network/CanvasNetworkGraph.js
- app/components/Network/ChannelsList.js
- app/components/Network/PeersList.js
- app/components/Network/TransactionForm.js
- app/containers/Root.js
- app/lnd/lib/lightning.js
- app/reducers/channels.js
- app/reducers/network.js
- app/routes/channels/components/Channels.js
- app/routes/peers/components/Peers.js
- package.json
- yarn.lock
With this we can set up CI on test-all for PR review, etc.
> Fix lints so that test-all runs green

- app/components/Peers/PeerForm.js
This should enhance user experience for a bit when adding new peers. No side-effects.
> Allow submitting peer on Enter key press

- app/components/ChannelForm/ChannelForm.js
- app/components/ChannelForm/ChannelForm.scss
- app/components/Form/Form.js
- app/components/ModalRoot/ModalRoot.js
- app/components/Peers/PeerForm.js
- app/components/Peers/PeerForm.scss
- app/components/Peers/PeerModal.js
- app/components/Wallet/ReceiveModal.js
- app/routes/activity/components/components/Modal/Modal.js
I changed all close icons to FaClose (look way better than MdClose) except for GlobalError component which will be rewritten anyway.
I also added close icon to PeerForm component.
Second commit is just code cleaning.
Solves #145
> Unified close icons

- README.md
Improve Zap installation instructions
> Improve Zap installation instructions

- app/components/Contacts/ContactModal.js
- app/components/Contacts/ContactsForm.js
- app/routes/contacts/components/Contacts.js
> Fix some whitespace lint errors on the friends feature

- app/components/Form/PayForm.js
- app/components/Form/RequestForm.js
- test/components/Form.spec.js
- test/components/Form/Payform.spec.js
- test/components/Form/RequestForm.spec.js
And make the form proptypes more specific.
> Add some further testing to the PayForm and RequestForm

- app/reducers/payment.js
setTimeout for 10 seconds after sending a payment. if LND hangs while sending a payment we wont show the loading screen forever lol we'll remove it and show an error after 10 seconds
> fix(payment): dont let sending a payment hang foevaaa

- app/routes/network/components/Network.js
- app/routes/network/components/Network.scss
show num of nodes and num of channels the node can see on the network map
> feature(network): network stats

- app/components/Contacts/ContactsForm.scss
- app/components/Contacts/Network.scss
- app/components/Wallet/ReceiveModal.scss
- app/routes/activity/components/Activity.scss
- app/routes/app/components/App.scss
Fix for the unnecessary scrollbars in windows, issue #310 
P.S. Created a new clean branch and new pull request. The old PR could be discarded.
> scrollbar-fix2

- yarn.lock
Should have been updated in 7acb971c05e122e2d77949fc59863e174c16a4b6
> Update yarn.lock for stylelint changes

- app/components/LoadingBolt/LoadingBolt.scss
> Give the bolt a little space to avoid clipping

- app/routes/activity/components/Activity.scss
> Fix the transaction scrollbar to consistently reveal all the transactions

- app/components/Contacts/Network.scss
fix for the same issue as #311 but for the network list.
> fix for the scrollbar issue in the network list

- ADVANCED.md
- CONTRIBUTING.md
- README.md
We need a long term fix as well - tbd. #339
> Fix the slack invite link

- yarn.lock
To fix the build. See:
https://github.com/flowtype/flow-typed/blob/master/CHANGELOG.md#240---2018-03-16
> Bump to flow-typed 2.4.0

- app/components/Form/Pay.js
- app/components/Form/Pay.scss
Redesigned the pay form so that it complies with usability laws and fits well on the default window size of ZAP. Feedback is welcome.
> fix(reformat-pay-form): fixed bad formatting

- app/components/Form/Request.js
- app/components/Form/Request.scss
Redesigned the request form so that it complies with usability laws and fits well on the default window size of ZAP.
> fix(reformat-request-form): fixed bad formatting

- ADVANCED.md
> fix(link-to-lnd-binary): update link to lnd-binary in ADVANCED.md

- app/reducers/channels.js
Update channel filter handlers to correctly consider the node alias.
Fix #396
> fix(channels): filter channel list on node alias

- app/main.dev.js
The onboarding settings are only relevant if the user wants to connect to a
remote LND or have Zap run LND. If the LND is already running locally, the user
is capable of separately configuring it.
This does not support the case of connecting to a remote LND while running LND
locally, but I can't think of a reason why someone would do such a thing. In
such a case, they could quit LND, start Zap, then re-start LND.
> Don't run onboarding if LND is already running locally

- app/components/Activity/ActivityModal.js
- app/components/Activity/TransactionModal.js
- app/components/Contacts/Network.js
- app/components/Wallet/ReceiveModal.js
- app/components/Wallet/Wallet.js
- app/reducers/info.js
- app/reducers/payform.js
- app/reducers/ticker.js
- app/routes/activity/containers/ActivityContainer.js
- app/routes/app/containers/AppContainer.js
- app/utils/blockExplorer.js
- test/reducers/__snapshots__/info.spec.js.snap
This holds network-specific information in state.info.network, initially the explorerUrl,
bitcoinJsNetwork, and the units prefix.
Fixes #422
> Prefix testnet units with 't'

- ADVANCED.md
- CONTRIBUTING.md
- LICENSE
- README.md
**Readme**
- Update format to conform to `standard-readme` format
- Tidy up header section
- Add table of contents
- Add security section
- Add help section
- List maintainers
- Add contribution notes
- Add contributors list
**Contributing**
- Add table of contents
- Add contribution faq
- Add contribution guidelines
**Advanced**
- Add table of contents
**Code of Conduct**
- Contributor Covenant
> docs: improve documentation

- app/components/Contacts/SubmitChannelForm.scss
Fixes issue #446. 
- fixed form layout
- added input field border
> fix(submit-channel-layout): refactor form layout

- app/components/Onboarding/Onboarding.js
- app/reducers/transaction.js
Declare a specific linter where appropriate, remove when unneeded.
> lint: Minimize disabling of linters

- app/main.dev.js
Ensure that any lnd process started by us is killed when the app quits.
Fix #470
> fix: kill lnd process on quit

- app/components/Contacts/SubmitChannelForm.scss
A few simple CSS tweaks to design our submit channel form per it's design mocks
> style(submit-channel): improve submit channel design

- app/components/Contacts/SubmitChannelForm.scss
Was using master just to find small bugs and places to improve. Noticed our font size was too big. Screenshots below show the before and after:
> fix(submit-channel): reduce font size

- app/lnd/methods/index.js
- app/lnd/walletUnlockerMethods/index.js
Log all calls to lnd service methods so that we can get a better picture of our intraprocess communication.
> Add more logging for lnd service

- app/components/Onboarding/Syncing.js
- app/components/Wallet/ReceiveModal.js
- app/containers/Root.js
- app/lnd/methods/index.js
- app/reducers/address.js
- app/reducers/info.js
- app/reducers/lnd.js
- app/reducers/transaction.js
- app/routes/activity/containers/ActivityContainer.js
- app/routes/app/components/App.js
- app/routes/app/containers/AppContainer.js
- test/reducers/__snapshots__/info.spec.js.snap
Only generate a new wallet address after the last one has been used.
Fix #519
> Remember last unused wallet address

- app/components/Activity/TransactionModal.js
> fix(receive-tx): dont show sent for received tx

- app/components/Onboarding/Onboarding.js
> fix(wallet-type): ensure a user selects a wallet type

- app/components/Onboarding/Syncing.js
- app/components/Onboarding/Syncing.scss
Update our sync address style to be consistent within the app
> style(syncing): update syncing address style

- app/components/Activity/TransactionModal.js
- app/reducers/activity.js
- app/reducers/transaction.js
- app/routes/activity/components/components/Transaction/Transaction.js
For more intuitive testing of tx direction
> refactor: add received prop to transaction

- app/components/Onboarding/BtcPayServer.js
- app/components/Onboarding/BtcPayServer.scss
- app/components/Onboarding/ConnectionConfirm.js
- app/components/Onboarding/ConnectionConfirm.scss
- app/components/Onboarding/ConnectionType.js
- app/components/Onboarding/ConnectionType.scss
- app/components/Onboarding/Onboarding.js
- app/containers/Root.js
- app/lnd/config/index.js
- app/lnd/lib/lightning.js
- app/lnd/lib/util.js
- app/package.json
- app/reducers/onboarding.js
- app/yarn.lock
- app/zap.js
Allow connecting to an LND instance that is behind BTCPayServer.
> feat(btcpayserver): add support for BTCPayServer

- app/reducers/transaction.js
And make the test more robust against unexpected state.
> fix(transaction notification): fix that state access was off the mark

- package.json
- yarn.lock
Update electron-builder to latest version. Fixes multiple build issues.
Fix #418
> chore(deps): update electron-builder

- app/package.json
- package.json
> fix(version): bump version

- app/components/Onboarding/Login.js
Quicker and easier login with Enter key.
> feat(onboarding): allow login with Enter key press

- ADVANCED.md
Update documentation in the `ADVANCED.md`  to be inline with recent changes to how we run or connect to lnd.
> docs: update advanced documentation

- app/routes/activity/components/components/Invoice/Invoice.js
> fix(activity): show settled date for paid invoices

- app/routes/activity/components/components/Invoice/Invoice.js
> fix(activity): show icon for paid invoices

- package.json
- yarn.lock
> chore(deps): update eslint-plugin-json package

- app/lib/zap/controller.js
Fix issue from last commit. tut tut tut. lol
> fix(lnd): ensure neutrino is properly initialized

- package.json
- resources/rpc.proto
Quite a lot of improvements gone into lnd this last week, including some that help to improve the initial sync process that would benefit us:
See changelog here: https://github.com/LN-Zap/lnd/releases
> fix(lnd): update lnd to latest version

- app/components/Wallet/Wallet.js
- app/components/Wallet/Wallet.scss
Add a Testnet pill to the UI next to our logo when a user is on testnet. Helps address #676
> feat(testnet): add pill to UI on testnet

- app/lib/utils/btc.js
- app/lib/zap/controller.js
- app/reducers/invoice.js
- package.json
- resources/rpc.proto
Updates lnd to latest master from https://github.com/LN-Zap/lnd/releases/tag/v0.5-beta-rc1-52-gbaee07ef
Many bugfixes and improvements in lnd.
Quick once over of wallet to ensure it works normally.
Bug fix / New feature
> feat(lnd): update lnd to latest master build

- app/components/Onboarding/ConnectionType.js
- app/components/Onboarding/ConnectionType.scss
Add descriptions to each connection type to help users understand what each of the different options do.
Fix #676
Help users to understand what the different connection types do
Open up the app and review the first onboarding screen.
New feature
> feat(onboarding): add connection type descriptions

- app/components/AmountInput/AmountInput.js
- app/components/Contacts/AddChannel.js
- app/components/Contacts/SubmitChannelForm.js
- app/components/Form/Pay.js
- app/components/Form/Request.js
- test/unit/components/Form/Pay.spec.js
- test/unit/components/Form/Request.spec.js
When modal forms are opened, ensure that the most relevant form field is selected by default.
Usability concerns raised in #389
Open and close the following forms:
Before this PR the user had to click into a form field before they could start to fill out the form.
After the PR, the most appropriate field is brought to focus automatically for them.
Bug fix
> fix(ui): autofocus forms

- package.json
- yarn.lock
babel-preset-react-hmre is not used and produces warnings on installation.
> chore(deps): remove babel-preset-react-hmre

- .travis.yml
- appveyor.yml
Only build and publish the electron packages for the current build environment.
Speed up builds.
Delete all published artefacts from draft release and run a new build on the master branch.
CI Improvements
> ci(release): release per platform

- test/unit/components/LoadingBolt.spec.js
One of our unit tests is failing due to a recent addition of the required `theme` prop.
Failing test
Run tests
Test fix
> test(unit): fix failing test case

- internals/scripts/lnd-release/.goreleaser.yml
- internals/scripts/lnd-release/README.md
- internals/scripts/lnd-release/canary.sh
Add the scripts that we have been using to create lnd releases and document how to use them.
I created these scripts a while ago and have been using them to publish lnd binaries. I'm adding them to the repo so that they don't get lost and so that they are available for general use!
> feat(lnd): add lnd release scripts

- package.json
Lightning Labs have re-released v0.5-beta to include some critical fixes missing from the original  v0.5-beta release.
Update our lnd to the current official release.
Manually test app.
> feat(lnd): update lnd to v0.5-beta

- app/components/Form/Request/Request.js
Ensure that the FormattedNumber component gets passed a valid number. If we don't have a value, the the value to 0.
The first time that you open the Request form, there is an error in the console due to a non-number being passed to the `FormattedNumber` component.
Manually - open the request form and look at the console log.
Bug fix
> fix(wallet): fix console error in request form

- app/components/Onboarding/Login/Login.js
- app/components/Onboarding/Login/Login.scss
This makes the text on the login button a little more readable.
Login button text is hardly visible
Manual testing - go to the login screen.
**Before:**
**After:**
UI fix
> fix(ui): improve login button style

- package.json
Jest still has issues with hanging processes... add --forceExit again!
> ci(jest): use forceExit

- app/components/Contacts/SubmitChannelForm/SubmitChannelForm.js
Remove `clearTextInput` on `componentDidMount` in the `SubmitChannelForm` component. We aren't clearing it in the reducer so we shouldn't be in the UI
Fix for #818 
Manually
> fix(add-channel): dont remove input text

- app/yarn.lock
- yarn.lock
Regenerate our yarn.lock files so that they are fully updated to the latest file format.
Thew latest version of yarn includes a new `integrity` field for all package entries. 
Run `yarn` and verify the app installs correctly
Buildtools update
> build(yarn): regenerate yarn.lock files

- app/yarn.lock
- package.json
- yarn.lock
This electron update includes a number of minor fixes and improvements.
Keep dependencies up to date.
Verify app builds and runs.
> chore(deps): update electron to v3.0.4

- app/components/UI/Menu.js
- app/components/UI/MenuItem.js
- app/components/UI/MenuItemGroup.js
- package.json
- stories/components/menu.stories.js
- test/unit/components/UI/Menu.spec.js
- test/unit/components/UI/__snapshots__/Menu.spec.js.snap
- yarn.lock
Implement a menu component that will use in the new home screen.
We need a styled menu with basic menu-like functionality on the new home screen that will be used for selecting menus.
Added to storybook
Added unit tests
New feature
> feat(ui): add Menu components

- app/lib/zap/controller.js
Cleaning up comments
Improve readability
Grammar nazi
Reading
code no-op
> style: fix spelling errors

- app/lib/lnd/neutrino.js
- package.json
- resources/rpc.proto
Update lnd to v0.5-beta-247-g68d96488 and enable alternate btcd hosts as lnd now properly supports it.
Manually
> feat(lnd): update lnd to v0.5-beta-247-g68d96488

- app/empty.html
- app/main.dev.js
- internals/webpack/webpack.config.renderer.dev.js
- internals/webpack/webpack.config.renderer.prod.js
- package.json
- yarn.lock
When we start up the app we attempt to fetch the users store settings from IndexedDb by loading up a hidden browser window and execute code within it to connect to and fetch settings from the database.
This fix ensures that we properly close out this hidden window once we have fetched the user settings.
Resolves an issue that prevented the production build from starting up fully.
Verify that `yarn dev` and `yarn start` work, and that the package built from `yarn package` properly starts up.
Bug fix
> fix(boot): issue with fetching user settings

- package.json
- yarn.lock
Update electron and supporting packages to latest versions.
Keep upto date with upstream fixes and improvements.
Manually
Dependency updates
> chore(deps): update electron packages

- app/components/Wallet/ReceiveModal/ReceiveModal.js
- app/reducers/info.js
- app/reducers/ticker.js
- test/unit/reducers/__snapshots__/info.spec.js.snap
- test/unit/reducers/__snapshots__/ticker.spec.js.snap
Do not assume that we are connecting to the bitcoin chain.
Ensure that the state of the app is clean when it starts. 
Manually + run tests
This also fixes a related minor display issue in the node info screen:
**Before:**
**After:**
Bug fix.
> fix: do not assume chain on boot

- package.json
Incorporate latest updates from lnd.
> feat(lnd): update lnd to v0.5-beta-302-gb6009850

- app/reducers/invoice.js
Add invoices that are created/paid in the background to the activity list.
Previously, only invoices created without Zap would be visible within Zap without doing a manual refresh on the activity list.
Fix #912
Manually - follow steps in #912
Bug fix
> fix(wallet): add all new invoices to invoice list

- app/reducers/info.js
- test/unit/reducers/__snapshots__/info.spec.js.snap
Update block explorer links to use 
Fix #901
Manually
Improvement
> feat(wallet): use blockstream.info block explorer

- app/components/Activity/Activity.js
- app/components/Activity/Invoice/Invoice.js
- app/components/Activity/Payment/Payment.js
- app/components/Activity/Transaction/Transaction.js
- app/components/Contacts/Network/Network.js
- app/components/Pay/Pay.js
- app/components/Pay/PaySummaryLightning.js
- app/components/Pay/PaySummaryOnChain.js
- app/components/Request/Request.js
- app/components/Syncing/Syncing.js
- app/components/UI/FiatAmountInput.js
- app/components/UI/Value.js
- app/components/Wallet/Wallet.js
- app/containers/App.js
- app/containers/Syncing.js
- app/lib/utils/api.js
- app/reducers/contactsform.js
- app/reducers/ticker.js
- internals/webpack/webpack.config.renderer.dev.js
- internals/webpack/webpack.config.renderer.prod.js
- stories/containers/pay.stories.js
- stories/containers/request.stories.js
- test/unit/components/Pay/PaySummaryLightning.spec.js
- test/unit/components/Pay/PaySummaryOnchain.spec.js
This updates PR #815 to apply cleanly to the latest master branch so that it can be merged.
Manually
Enhancement / Fix
> fix(ticker): use Coinbase API to fetch fiat ticker

- app/components/Onboarding/Steps/SeedConfirm.js
- app/components/Onboarding/Steps/SeedView.js
- app/components/Onboarding/Steps/messages.js
- stories/containers/onboarding.stories.js
Only highlight seed reentry fields when the valid word has been entered.
Fix for #938 
Manually
Bug fix
> fix(seed): only highlight seed after success

- babel.config.js
This fixes an issue related to a recent update to our babel setup in which some of our plugins were not being loaded in the storybook environment.
Fix issue with storybook
Bug fix
> build(babel): ensure used env presets are enabled

- app/components/Home/WalletUnlocker.js
- app/components/Onboarding/Steps/Alias.js
- app/components/Onboarding/Steps/BtcPayServer.js
- app/components/Onboarding/Steps/ConnectionDetails.js
- app/components/Onboarding/Steps/Login.js
- app/components/Onboarding/Steps/Password.js
- app/components/Onboarding/Steps/Recover.js
- app/components/Onboarding/Steps/SeedConfirm.js
- app/components/UI/Input.js
- test/unit/components/UI/__snapshots__/Input.spec.js.snap
- test/unit/components/UI/__snapshots__/Select.spec.js.snap
- test/unit/components/UI/__snapshots__/TextArea.spec.js.snap
This is a rebase of #913 from the latest `next` branch with a couple of fixes for failing tests.
> feat(ux): auto focus on inputs in startup flow

- package.json
- resources/rpc.proto
> feat: update lnd to v0.5.1-beta

- app/components/Activity/Activity.scss
- app/components/Activity/Invoice/Invoice.js
- app/components/Activity/Payment/Payment.js
- app/components/Activity/Transaction/Transaction.js
- app/components/UI/GlobalStyle.js
Ensure that tooltips display correctly in the activity list.
Fix #966 
Manually
Bug fix
> fix(ui): improve tooltip styles

- app/package.json
- app/yarn.lock
Update grpc to v1.16.1
Fix build issues on Arm -  #760 
Manually
> chore(deps): update dependency grpc to v1.16.1

- internals/webpack/webpack.config.renderer.dev.dll.js
- package.json
- yarn.lock
Remove unused font-awesome dependency
It's adding bloat needlessly.
Manually
Dependency updates
> chore(deps): remove unused font-awesome dependency

- app/reducers/channels.js
Fetch an updated channel list if we receive a channel update to one of our active channels.
Previously, we would only update if the advertising_node or connecting_node was our own node. This fix expands the criteria so that we also trigger the channels list re-fetch if there is a match against one of our channels' remote_pubkey.
Fix #724
Manually - make a payment and verify that the channels balances get updated correctly once the payment has gone through successfully.
Bug fix
> fix(channels): refresh channel details on update

- .storybook/config.js
- app/components/Settings/Fiat/Fiat.scss
- app/components/Settings/Locale/Locale.scss
- app/components/UI/GlobalStyle.js
- app/components/UI/MainContent.js
- app/components/UI/Panel.js
- test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
- test/unit/components/UI/__snapshots__/Modal.spec.js.snap
- test/unit/components/UI/__snapshots__/Panel.spec.js.snap
Ensure consistent scrollbar styling
Scrollbars look messed up for some users.
Manually
Bug fix
> fix(ui): autohide scrollbars

- package.json
Increase node engine version to `>=8.11.2`.
This is the minimum version required by `@grpc/grpc-js`
> build(node): increase node engine version to >=8.11.2

- app/reducers/invoice.js
Ensure that we include route hints in invoices created for local nodes.
Ensure that we await on fetching wallet info from the database before determining wether to create invoice with route hints included.
Manually
Bug fix
> fix(invoice): include route hints for local nodes

- app/reducers/wallet.js
Initialise wallets from the database as soon as possible, and scan filesystem for wallets in the background.
App boot time is being slowed a little by some of the stuff we are doing in initWallets, specifically where we scan the filesystem for wallets.
Boot up app
Performance enhancement
> perf(init): initialise wallets from db early

- app/main.dev.js
fix url parsing issue with lightning links
test various 'lightning:' and 'lndconnect' links
Bug fix
> fix(main): fix url parsing issue with lightning links

- .eslintrc.js
- app/main.dev.js
- app/package.json
- app/yarn.lock
- internals/webpack/webpack.config.main.prod.js
- package.json
Ensure that preload.js is working properly in production builds
Fix #1107
run `yarn package` and then start the built app and verify that delete functionality works for local wallets.
Bug fix
>  fix(electron): include preload.js in production build

- app/components/Activity/InvoiceModal/InvoiceModal.js
- app/components/Activity/PaymentModal/PaymentModal.js
- app/components/Activity/TransactionModal/TransactionModal.js
- app/components/Wallet/ReceiveModal/ReceiveModal.js
- app/components/Wallet/ReceiveModal/ReceiveModal.scss
Fix various issues with the light theme - specifically in the payment, transaction, invoice, and receive modals.
payment, transaction, invoice, and receive modals display8ing a mix of dark and light colours when in the light theme.
Start the app, select the light theme, and view the payment, transaction, invoice, and receive modals.
Big fix
> style(theme): fix issues with light theme

- app/lib/zap/controller.js
- app/reducers/channels.js
- app/reducers/invoice.js
- app/reducers/lnd.js
- app/reducers/onboarding.js
Load wallet settings from redux rather than indexedb to ensure they are available instantly.
Fix #1108
Bug fix
> fix: load wallet settings from store

- app/lib/zap/controller.js
- app/lib/zap/menuBuilder.js
- app/main.dev.js
Ensure single instance of the app
Fix #229
Bug Fix
> fix(app): ensure single app instance

- app/reducers/payment.js
- app/reducers/ticker.js
- app/reducers/transaction.js
Decorate transactions prior to saving into the state to ensure that our supplemental metadata is always available.
Fix date issue from #1120
Manually - ensure dates appear correctly in date list.
Bug fix
> fix(activity): ensure activity dates are correct

- app/lib/utils/userFriendlyErrors.js
- app/reducers/payment.js
- app/reducers/transaction.js
Capitalize payment/transaction error strings
Manually - make failed payment / transaction.
Enhancement
> fix(wallet): ucfirst error strings

- app/main.dev.js
add missing `open-url` handler
lndconnect / lightning links are not working.
Test `lightning:` and `lndconnect` functionality.
Bug fix
> fix(wallet): fix lightning/lndconnect links

- app/components/Contacts/SuggestedNodes/SuggestedNodes.js
- app/components/Contacts/SuggestedNodes/messages.js
- app/components/Settings/Fiat/Fiat.scss
- app/components/Settings/Locale/Locale.scss
- app/components/Settings/Theme/Theme.scss
- app/translations/en.json
Addresses the weird gap between words in column issue from #636. See the last image and paragraph here: [https://github.com/LN-Zap/zap-desktop/issues/636#issuecomment-450604350](https://github.com/LN-Zap/zap-desktop/issues/636#issuecomment-450604350)
> fix(ui): left-align column text

- app/components/Syncing/messages.js
- app/translations/en.json
Fixes #1194.
Opening this PR instead of the closed #1199.
> fix(ui): reword blockchain syncing message

- app/components/Activity/Activity.js
> fix(ui): add autofocus to search input field

- app/containers/Request.js
- app/reducers/invoice.js
Update invoice status to "paid" once payment is received
Fix UI bug. Currently invoice status update is not implemented
Manually
**Before:**
Before the patch. Status is not updating though the invoice was paid already
**After:**
With this patch status updates automatically once invoice is paid
> fix(ui): implement invoice status update in request modal

- app/package.json
- package.json
Bump patch version for upcoming `v0.3.3-beta` maintenance release
> chore(version): bump version to v0.3.3-beta

- app/components/Activity/Activity.js
- app/components/Activity/ActivityListItem.js
Extract `ActivityListItem` to a separate file and make it `PureComponent`
Avoid redundant re-renders of activity list by using `PureComponent` for a list item
Manually
Refactoring\Perf improvement
> perf(activity): use purecomponent for activity list item and extract it

- app/components/Settings/Fiat/Fiat.js
- app/components/Settings/Locale/Locale.js
- app/components/Settings/Menu/Menu.js
- app/components/Settings/Settings.js
- app/components/Settings/Theme/Theme.js
- app/components/UI/Dropdown.js
- app/components/Wallet/Wallet.js
- app/containers/Activity.js
- app/containers/Settings.js
- app/reducers/settings.js
- test/unit/reducers/__snapshots__/settings.spec.js.snap
- test/unit/reducers/settings.spec.js
- vertically centre settings menu icons
- ensure settings menu closes properly
- don't show angle icon for logout link
Fix #1242 
Manually
Bug fixes
> Fix settings menu glitchs

- app/components/UI/MainContent.js
- test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
Fixes a bug to ensure the main content area is scrollable
Can't scroll main content area
Manually - ensure you can access content that is off screen (eg autopilot settings)
Bug fix
> fix(ui): ensure main content area is scrollable

- app/components/Pay/Pay.js
- app/components/Pay/PaySummaryLightning.js
- app/components/UI/Value.js
- app/containers/Pay.js
- app/lib/utils/btc.js
- app/reducers/payment.js
- stories/containers/pay.stories.js
- stories/helpers.js
Ensure that invoices with amounts that are specified in millisatoshis are properly handled.
Fix #1273 
- I've added some new knobs to the knobs tab in the storybook that allow you to easily test the request form with various different types of invoices.
- Ensure currency conversions continue to function properly in the app.
- Ensure `lightning:` links work correctly
- Try paying various different types of invoices
Bug fix
> fix(wallet): handle invoices with msat amounts

- app/components/Request/RequestSummary.js
Add missing curly brace
Fix #1259
Style fix
> style(jsx): add missing curly brace

- app/components/App/App.js
Remove redundant state variables
`this.state.nextFetchIn` and `this.state.timer` do not affect render and therefore can be safely moved to `this `to avoid unnecessary re-renders
Manually and via existing tests
Performance improvement\refactoring
> perf(app): remove irrelevant to render state vars

- package.json
Remove unused `chalk` dependency
Package isn't used, so remove it.
> chore(deps): remove unused dependency chalk

- app/components/UI/Select.js
- test/unit/components/UI/Countdown.spec.js
- test/unit/components/UI/LightningInvoiceInput.spec.js
Updated version of #1208 with corrected commit message
> test(unit): clean up some warning messages

- app/components/Home/Home.js
- app/components/UI/GlobalStyle.js
- app/components/UI/MainContent.js
- test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
Adjust overflow values to ensure that we only add scroll bars where they are needed, and do not set overflow on elements that should not have it set - specifically, remove the overflow from the MainContent component and move further down the hierarchy as adding overflow spec on the MainContent area prevents the menu from being able to break outside of its bounds.
Fix #1328
1. Check to ensure menu overflow bug is fixed
2. Check app to ensure scrollbars work as we want them to
Bug fix
> fix(ui): ensure menu can overflow main content

- app/lib/utils/btc.js
> fix(btc): remove unnecessary price parameters

- app/components/Onboarding/Steps/Alias.js
- app/components/Onboarding/Steps/Autopilot.js
- app/components/Onboarding/Steps/BtcPayServer.js
- app/components/Onboarding/Steps/ConnectionConfirm.js
- app/components/Onboarding/Steps/ConnectionDetails.js
- app/components/Onboarding/Steps/ConnectionType.js
- app/components/Onboarding/Steps/Login.js
- app/components/Onboarding/Steps/Name.js
- app/components/Onboarding/Steps/Password.js
- app/components/Onboarding/Steps/Recover.js
- app/components/Onboarding/Steps/SeedConfirm.js
- app/components/Onboarding/Steps/SeedView.js
- app/components/Onboarding/Steps/WalletCreate.js
- app/components/Onboarding/Steps/WalletRecover.js
- app/components/UI/Wizard.js
Remove references to undefined `preSubmit` hook in the `Wizard` component and throughout the onboarding process.
Fix #1331
Manually check onboarding process
Refactor
> refactor(onboarding): remove unused preSubmit hook

- app/components/Activity/Activity.js
Add intl support to activity group header
Currently activity headers, which are dates are shown in English and ignore language setting
Manually. Changes language setting back and forth
Bugfix
> fix(i18n): add intl support for activity header

- app/components/UI/Dialog.js
- stories/components/dialog.stories.js
- test/unit/components/UI/Dialog.spec.js
- test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
Add ability to customize dialog header/buttons/body
In order to create more complex dialogs, base component needs to be enhanced. Enhancement allows passing React components as header/body/buttons
Via storybook
Component enhancement
> refactor(ui): add customizability to dialog component

- app/components/Activity/Activity.js
- app/components/App/App.js
- app/lib/utils/delay.js
- app/lib/zap/controller.js
- app/lib/zap/updater.js
- app/reducers/error.js
- app/reducers/payment.js
- app/reducers/transaction.js
- stories/containers/home.stories.js
- stories/containers/onboarding.stories.js
- stories/containers/pay.stories.js
- stories/containers/request.stories.js
Extract `delay` method into reusable library method, and update places throughout the code where we apply a time delay to use this method.
Reduce code duplication and improve implementation  consistency.
Manually
Refactor
> refactor(libs): extract and reuse delay utility method

- app/lib/utils/btc.js
> fix(btc): correct conversion from msat and mlits to fiat

- app/lib/utils/btc.js
- test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
- test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
> fix(btc): make sure non-round fiat conversion results are handled well

- CONTRIBUTING.md
Add additional notes to the contributing guide:
- Branches
- Pull requests
Provide guidance for new contributors.
Documentation updates / improvements
> docs(contributing): branches and pull requests

- test/unit/utils/btc.spec.js
> test(btc): add unit tests for btc.js

- app/components/UI/Input.js
- app/components/UI/TextArea.js
- app/containers/Activity.js
- app/lib/lnd/methods/index.js
Address lint warnings
Fix nested promise(and improve it's readability along the way) and import warnings. Silence proptype warning.
Request invoice functionality, one of the parts this PR addresses, was tested manually
` 6 warnings`
`no warnings`
Refactor
> refactor(lint): fix lint warnings

- app/components/Contacts/Network/BrowseChannelButton.js
- app/components/Contacts/Network/ChannelDetails.js
- app/components/Contacts/Network/ChannelItem.js
- app/components/Contacts/Network/ChannelLimits.js
- app/components/Contacts/Network/ChannelPubkey.js
- app/components/Contacts/Network/CloseChannel.js
- app/components/Contacts/Network/ClosingChannel.js
- app/components/Contacts/Network/Header.js
- app/components/Contacts/Network/LoadingChannels.js
- app/components/Contacts/Network/Network.js
- app/components/Contacts/Network/NetworkActionBar.js
- app/components/Contacts/Network/NetworkBalance.js
- app/components/Contacts/Network/SearchBar.js
- app/components/Contacts/Network/Ticker.js
- app/components/Contacts/Network/index.js
Refactor `Network.js` jsx code
Decompose `Network.js` jsx code into manageable parts in order to be able to easily modify/improve/do bugfix in the future
Manually
Refactor
> refactor(ui): decompose network jsx into components

- package.json
Fix `extract-messages` command to work on Windows
Currently `extract-messages` is failing on windows. Proposed change works both on Windows and MacOS
Manually. Removed all translations and re-generated them
Bugfix
> chore(script):  fix extract messasges

- app/components/UI/Checkbox.js
- stories/forms/form.stories.js
- test/unit/components/UI/Checkbox.spec.js
- test/unit/components/UI/__snapshots__/Checkbox.spec.js.snap
Add description field to `Checkbox` component
Add description field to make look and feel consistent with an existing `Radio` component
Via Storybook
Component improvement
> refactor(cb): add description field to checkbox

- app/main.js
- package.json
This is a follow up to #1428 to add additional support for windows/linux
Fix #1428
Manually
Bug fix
> fix(wallet): handle protocol links when app closed (linux/windows)

- app/reducers/network.js
Fix duplicate nodes appearing after network update
Manually
Bugfix
> fix(ui): fix issue with node duplicates after update

- app/components/Channels/ChannelStatus.js
- app/components/Channels/index.js
- app/components/Channels/messages.js
- app/components/Contacts/Network/ChannelItem.js
- app/components/Contacts/Network/LoadingChannels.js
- app/components/Icon/Circle.js
- app/components/UI/Spinner.js
- app/components/UI/StatusIndicator.js
- stories/containers/channels/channel-capacity.stories.js
- stories/containers/channels/channel-status.stories.js
- test/unit/components/UI/__snapshots__/Spinner.spec.js.snap
- test/unit/components/UI/__snapshots__/StatusIndicator.spec.js.snap
Add a new ChannelStatus component that can be used to display channel status information. This supports all possible channel states.
Needed for new Channel UI - Re #1425
Storybook
New components
> refactor(ui): add new ChannelStatus component

- app/components/Channels/ChannelCapacity.js
- app/components/Channels/ChannelMoreButton.js
- app/components/Channels/ChannelStatus.js
- app/components/Channels/ChannelSummaryListItem.js
- app/components/Channels/index.js
- app/components/Channels/messages.js
- app/components/Contacts/Network/ChannelItem.js
- app/components/Contacts/Network/LoadingChannels.js
- app/components/Icon/Circle.js
- app/components/UI/Spinner.js
- app/components/UI/StatusIndicator.js
- app/components/withEllipsis/index.js
- app/components/withEllipsis/withEllipsis.js
- stories/containers/channels/channel-capacity.stories.js
- stories/containers/channels/channel-status.stories.js
- stories/containers/channels/channel-summary-list-item.stories.js
- test/unit/components/UI/__snapshots__/Spinner.spec.js.snap
- test/unit/components/UI/__snapshots__/StatusIndicator.spec.js.snap
Add a new ChannelSummaryListItem component that can be used to display a summary of channel data in a list view format.
Re #1425
Storybook
New components
>  refactor(ui): add new ChannelSummaryListItem component

- app/components/Activity/Activity.js
- app/components/Activity/ActivityListItem.js
- app/reducers/activity.js
- package.json
- yarn.lock
Optimize rendering of activity list
fix #1296 
Deploy [react-virtualized](https://github.com/bvaughn/react-virtualized) library to optimize rendering process and also optimize reselect selectors for flat structure and faster initial fetching
Manually
Created a remote node with 6000 txs and tested performance in production. It is important to test performance in production mode since react/redux devtools slow down rendering a lot and eventual results are distorted a lot.
Optimization
> perf(activity): optimize activity list rendering

- app/components/Channels/ChannelCapacity.js
- app/components/Channels/ChannelSummaryList.js
- app/components/Channels/ChannelSummaryListItem.js
- app/components/Channels/index.js
- app/components/UI/Heading.js
- app/components/UI/Text.js
- stories/containers/channels/channel-summary-list.stories.js
- test/unit/components/UI/__snapshots__/Checkbox.spec.js.snap
Add a new ChannelSummaryList component that can displays a list of channels in a summary view.
Needed for new Channel UI - Re #1425
Storybook
New components
> refactor(ui): add new ChannelSummaryList component

- .travis.yml
- package.json
Make a few adjustments to the linux test environment on travis
> ci(travis): adjustments for testcafe

- TROUBLESHOOTING.md
Create skeleton for troubleshooting guide and and add a cleaned up #1440
Ref #1440
Docs
> docs(help): start a troubleshooting guide

- app/lib/utils/getPackageDetails.js
- app/lib/utils/index.js
- app/lib/zap/about/index.js
- app/lib/zap/about/preload.js
- app/lib/zap/about/public/about.html
- app/lib/zap/about/public/renderer.js
- app/lib/zap/about/public/styles/ui.css
- app/lib/zap/menuBuilder.js
- internals/webpack/webpack.config.renderer.prod.js
- package.json
Add cross platform about menu
Fix #1365 and make about menu consistent across all platforms
Manually
New feature
>  feat(ui): add cross platform about menu

- app/package.json
- app/yarn.lock
Update lnd-grpc to v0.1.4
lnd-grpc to v0.1.4 adds support for versions of lnd back to 0.5.0-beta, and supports earlier versions of nodejs.
Manually
> chore(deps): update lnd-grpc to v0.1.4

- package.json
- yarn.lock
Update lnd to version v0.5.2-beta
Update lnd to latest stable release.
> fix(deps): update dependency lnd to v0.5.2-beta

- app/components/Contacts/Network/Network.js
- app/containers/App.js
- app/reducers/channels.js
- test/unit/reducers/__snapshots__/channels.spec.js.snap
- test/unit/reducers/channels.spec.js
Refactor the channels reducer so that we reuse selectors as much as possible, and augment channels with additional metadata used for display purposes.
Fix #1244
Fix #847
Manually - give the network pane a good run for its money.
Bug fixes.
> fix(ui): improve channel list search and filter

- app/components/UI/BackgroundPrimary.js
- test/unit/components/UI/__snapshots__/BackgroundDark.spec.js.snap
- test/unit/components/UI/__snapshots__/BackgroundPrimary.spec.js.snap
- test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
> fix(ui): fix missing show expired requests button

- app/components/Contacts/Network/Network.js
Fix minor typo in network search bar layout code
Correctness
Manually (no visual changes to network search bar)
refactor
> refactor(typo): fix network search bar layout typo

- app/components/Home/WalletLauncher.js
Fix layout glitch in the wallet launcher
Issue was introduced by #1526 
Underlying of a primary container (`MainContent`) was changed to `Flex` but wallet launcher hierarchy was still using `React.Fragment` as a wrapper and as a result a glitch has occured
fix #1531 
Fix visual glitch
Manually
Bugfix
> fix: delete button layout glitch

- app/components/Home/WalletUnlocker.js
Fix handling of disabled state of wallet unlocker "Enter" button 
Fix typo in JSX code and make button `disabled` flag work properly
Manually
Bugfix
> fix(ui): wallet unlocker button disabled state

- app/reducers/lnd.js
Ensure that lnd errors get displayed properly.
LND startup errors are not displaying correctly
From the wallet launcher, try connecting to a node that is offline
Bug fix
>  fix(lnd): ensure lnd start errors are displayed

- app/components/Home/WalletLauncher.js
Fix incorrect save wallet settings action bar visibility in some cases
Under certain conditions save wallet settings action bar is visible when no changes were made to wallet settings. 
Manually
Bugfix
> fix(ui): incorrect save wallet action bar visibility

- app/lib/zap/controller.js
Clean `onBeforeStartRemoteLnd` code and add additional comments
Manually. Tested remote node in online and offline (node is unreachable or trying to connect with an invalid credentials) modes
Refactor
> refactor(lnd): clean remote node before start code

- app/containers/Initializer.js
- app/containers/Root.js
- app/containers/WalletStarter.js
- app/lib/lnd/lightning.js
- app/lib/utils/index.js
- app/lib/utils/promisifiedCall.js
- app/reducers/app.js
- app/reducers/ipc.js
- app/reducers/lnd.js
- app/reducers/onboarding.js
- app/reducers/utils.js
- app/reducers/wallet.js
When trying to connect to a remote node that you previously had successfully connected to and that is currently offline, there is a blank screen for a long period of time (~18 secs) until you see a timeout error. This is caused by bolt loading screen being prematurely unmounted and creates an impression that app is stuck.
This is also a prerequisite for #1178
This PR also does an overhaul of initial route determination mechanism to make it more declarative and straightforward.
Manually
Tested:
1. Remote node that is unlocked
2. Remote node that is locked
3. Remote node that was successfully connected to and now is offline
4. Local node
5. Lndconnect link
Bugfix/refactor
> fix(ui): remote node loading screen

- app/components/withNumberInputMask/withNumberInputMask.js
Adds missing prop types.
Missing prop types were causing lint to fail the build.
`yarn lint`
Refactor
> refactor: add missing proptypes

- app/components/Icon/LightningChannel.js
- app/icons/lightning-channel.svg
- stories/icons/icon.stories.js
Add new Lightning Channel icon
Needed for #1448
`yarn storybook`
New component
> refactor: add LightningChannel icon

- .eslintrc.js
- package.json
- yarn.lock
Add `rule of hooks` lint rule
React hooks have some limitations that can cause issues. It's recommended to have lint rule for automatic checks. More info [here](https://reactjs.org/docs/hooks-overview.html)
Manually. Created a hook that violates rule of hooks
Lint rule update
> chore(lint): add react hooks rule of hooks

- app/reducers/ticker.js
Ensure selected currency unit is saved and restored properly.
This fixes a bug in which the selected currency unit is lost when you logout of a wallet or restart the app.
Manually - change currency unit, log out, log back in, or restart the app and ensure that currency unit preference is restored.
Bug fix
> fix(wallet): ensure currency unit is saved on change

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .storybook/config.js
- TROUBLESHOOTING.md
- internals/scripts/lnd-release/README.md
- package.json
- stories/_general/_welcome.stories.js
Change product name from ZapDesktop to Zap.
This updates everything except for the IndexedDb database name, which would be relatively complex and potentially problematic to rename and not worth the hassle IMO.
Fix #1554
Manually
> build: change product name from ZapDesktop to Zap

- app/package.json
- package.json
Bump version to v0.3.5-beta
Prep for next maintenance release
> chore(version): bump version to v0.3.5-beta

- app/components/Channels/ChannelFooter.js
Remove unused code introduced in #1576 
Manually
Refactor
> refactor: remove unused code

- app/components/Channels/ChannelCardListItem.js
- app/components/Channels/ChannelSummaryListItem.js
Slightly improve channel lists rendering perf by using pure components
Do no re-render entire lists on the unrelated actions like opening a modal
Manually
> perf(ui): improve channel list rendering

- app/components/Activity/ActivityModal/ActivityModal.js
- app/components/App/App.js
- app/components/Wallet/ReceiveModal/ReceiveModal.js
- app/containers/App.js
- app/containers/ModalStack.js
- app/containers/Wallet/ReceiveModal.js
- app/reducers/activity.js
- app/reducers/address.js
Bring node details and activity modals under the common modal system (modal stack)
Currently node and activity modals are standalone and thus are not benefiting from the existing modal system (transition animation, proper escape button handling etc), as well as causing rendering issues.
Modals are now part of the common stack and are also bound closer to a redux state source resulting in a minor perf improvements.
This PR also does some cleanup and refactoring of the top level `App` container
Fix #1614 
Manually
Bugfix and refactoring
> fix(ui): node and activity modals overhaul

- app/components/Channels/ChannelCapacity.js
- app/components/Channels/ChannelCardList.js
- app/components/Channels/ChannelSummaryList.js
- app/components/Channels/Channels.js
- app/components/TabControl/PersistentTabControl.js
Resolves #1537 
It's recommended to test in `production` mode
Manually
Perf improvement
>  perf(ui): use react virtualized in channels management screen

- app/components/Channels/ChannelStatus.js
> fix(ui): prevent breaking channel status text in 2 lines

- resources/lnd.conf
> refactor(lnd.conf): comment out litecoin.node

- app/lib/lnd/neutrino.js
minor spelling fixes. nothing major
> style(neutrino.js): spelling fixes

- app/components/Channels/ChannelNodeSearch.js
> fix(ui): prevent long name break in channel search

- app/reducers/contactsform.js
Make node search case insensitive
Manually
Enhancement
> fix(ui): make node search case insensitive

- app/reducers/contactsform.js
Include suggested nodes in search results in create channel node search view
Currently we don't include suggested nodes in the search results
Manually
Enhancement
> fix(ui): include suggested nodes in search results

- app/components/Channels/ChannelSummaryList.js
> fix(ui): fix last item dropshadow glitch in channel summary list

- app/containers/Initializer.js
- app/containers/Root.js
- app/reducers/channels.js
- app/reducers/locale.js
- app/reducers/onboarding.js
- app/reducers/settings.js
- app/reducers/theme.js
- app/reducers/ticker.js
- app/reducers/utils.js
- app/reducers/wallet.js
Refactor settings handling to consolidate and standardize. Save and restore additional settings for channel view mode.
Fix #1688
Manually - verify that all persistent user settings work as intended.
Enhancement
> feat(channels): remember use selected channel view mode

- app/containers/Root.js
- app/reducers/info.js
- app/store/configureStore.dev.js
- internals/webpack/webpack.config.renderer.dev.js
- package.json
- yarn.lock
Update hot reload implementation to get reload working again.
Hot reloading isn't triggering instant rerender.
Manually
Bug fix
> refactor(react): update hot reload implementation

- app/components/App/App.js
- app/components/Util/hooks/useInterval.js
- app/containers/App.js
- app/hooks/index.js
- app/hooks/useInterval.js
Resolves #1683 
This PR fixes confirmation updates naively until streaming API is available by fetching tx history from time to time on schedule.
Manually
Bugfix
>  fix(ui): implement tx confirmation count update

- app/lib/lnd/methods/invoicesController.js
I've extended the default invoice request expiry time from `10min` to `24hours`
I've done this in response to Issue #1710 
I've created an invoice and then checked expiry time.
Simple change of amount of seconds from `600` seconds to `86400`
- [x ] All new and existing tests passed.
> feat(inc-expiry-time): extend default invoice expiry time to 24hrs

- app/reducers/wallet.js
> fix(ui): repair delete wallet action

- app/components/App/App.js
- app/components/Pay/Pay.js
- app/components/UI/CurrencyFieldGroup.js
- app/components/Wallet/Wallet.js
- app/containers/App.js
- app/containers/Initializer.js
- app/lib/utils/sanitize.js
- app/main.js
- app/reducers/app.js
- app/reducers/info.js
- app/reducers/ipc.js
- app/reducers/modal.js
- app/reducers/pay.js
- app/reducers/utils.js
- package.json
- test/unit/reducers/__snapshots__/info.spec.js.snap
- yarn.lock
Open the payform prefilled when a user uses a bip-21 payment link.
Fix #1692
Manually
New feature
> feat(wallet): support bitcoin payment uris (bip-21)

- app/components/UI/Bar.js
- app/components/UI/Tabs.js
Fix onboarding connection details tab control display glitch
Manually
UI glitch fix
> fix(ui): fix connection details tabcontrol

- app/package.json
- package.json
Bump version to v0.4.0-beta in preparation for release.
> chore(version): bump version to v0.4.0-beta

- app/lib/lnd/methods/channelController.js
Use unconfirmed outputs in funding transaction
Fix #1495
Manually
Enhancement
> feat(channels): use unconfirmed outputs in funding transaction

- app/components/Channels/ChannelCardList.js
- app/components/Channels/ChannelCreateSummary.js
- app/components/Channels/ChannelStatus.js
- app/components/Pay/PaySummaryLightning.js
- app/components/Pay/PaySummaryOnChain.js
- app/components/UI/Header.js
- app/components/UI/Heading.js
- app/components/UI/Message.js
- app/components/UI/Notification.js
- app/components/Wallet/Wallet.js
- test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
- test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
- test/unit/components/UI/__snapshots__/Header.spec.js.snap
- test/unit/components/UI/__snapshots__/Message.spec.js.snap
- test/unit/components/UI/__snapshots__/Notification.spec.js.snap
Always use preset font sizes from the base theme.
Fix #1786
Manually
Bug fix
> fix(ui): always use preset font sizes

- app/reducers/balance.js
- app/reducers/channels.js
Include limbo balance in wallet total
Fix #1792
Manually
Bug fix
> fix(wallet): include limbo balance in wallet total

- package.json
Update lnd to most recent head build.
Includes improvements for neutrino
Manually
Dependency upgrade
> fix(deps): update lnd to v0.5.1-beta-869-g131959ef

- app/components/Channels/ChannelCardListItem.js
- app/components/Channels/ChannelData.js
- app/components/Channels/ChannelSummaryListItem.js
- app/lib/lnd/methods/channelController.js
- app/lib/lnd/methods/index.js
- app/lib/lnd/push/openchannel.js
- app/reducers/channels.js
- app/reducers/ipc.js
- app/reducers/lnd.js
- app/reducers/ticker.js
- app/reducers/transaction.js
- stories/containers/channels/channel-card-list-item.stories.js
- stories/containers/channels/channel-card-list.stories.js
- stories/containers/channels/channel-summary-list.stories.js
- test/unit/reducers/__snapshots__/channels.spec.js.snap
- test/unit/reducers/channels.spec.js
Include loading channels in listings
Provide feedback to the user when opening channels
Manually
Enhancement
> feat(channels): include loading channels in listings

- app/components/Channels/ChannelCreateForm.js
- app/containers/Channels/ChannelCreateForm.js
Disable open channel button while channel open is in progress to prevent multiple clicks
Bugfix
> fix(ui): disable open channel button on submit

- package.json
- yarn.lock
Update lnd to latest master build
> fix(deps): update lnd to v0.5.1-beta-926-g764d8525

- app/reducers/invoice.js
- app/reducers/payment.js
Refresh channels after incoming and outgoing LN payments.
Fix #1825
Manually
Enhancement
> fix(channels): refresh channels after LN payments

- app/components/Channels/ChannelCreateForm.js
- app/components/GlobalNotification/GlobalNotification.js
- app/containers/Channels/ChannelCreateForm.js
- app/reducers/channels.js
- app/reducers/notification.js
- package.json
- yarn.lock
- Add support for updating existing notifications
- Use processing variant for channel create initiated message
- Update existing message on channel success or error
Improve notifications surrounding the channel creation process.
- Successfully create a channel 
- Fail to create a channel (eg, set opening amount below min_chan_size of remove node)
Enhancement
> fix(channels): improve channel create messages

- app/containers/Wallet/ReceiveModal.js
- app/reducers/ticker.js
> fix(ui): incorrect currency address name

- app/components/Icon/PlusOnboarding.js
- app/icons/plus-onboarding.svg
> fix(icon): fix onboarding plus icon color prop

- package.json
- yarn.lock
Update lnd to v0.5.1-beta-982-gf9ba6759
Runtime panic with current lnd version
> feat(lnd): update lnd to v0.5.1-beta-982-gf9ba6759

- scripts/lnd-release/.goreleaser.yml
enable lnd tags signrpc, walletrpc, chainrpc, autopilotrpc
remove arm from lnd build script
Incorporate recent updates to lnd build process
> refactor: update lnd build script

- utils/localWallets.js
Fix #1862 
Filter non-wallet directories when importing wallets
Manually
Bugfix
> fix(wallet): filter non wallet dirs and files

- renderer/components/Channels/ChannelCreateForm.js
- renderer/containers/Channels/ChannelCreateForm.js
fix #1912
Manually.
Opened one channel. Then immediately opened another one.
Bugfix
> fix(ui): fix incorrect next button disabled state

- renderer/components/Channels/NodeCardList.js
Resolves #1918
Manually
Enhancement
> fix(ui): hide suggested nodes channel when empty

- renderer/reducers/channels.js
- test/unit/reducers/__snapshots__/channels.spec.js.snap
- test/unit/reducers/channels.spec.js
When working on #1914 some unused code was discovered (which was partly used before 1914)
This PR builds on top of #1914 so should be merged after that
Manually
Refactor
> refactor: remove unused code in channels reducer

- renderer/store/db.js
Fix issue with wallet config format conversion when upgrading from 3.x to 4.x.
fix #1901
```
rm -rf /Users/tom/Library/Application\ Support/Electron
git checkout v0.3.4-beta
yarn clean && yarn && yarn dev
NODE_TLS_REJECT_UNAUTHORIZED=0 yarn dev
```
Create a new wallet, select btcpayserver option, and craft a connection config that looks like btcpay server (you c an use your own node details)
```
{
"configurations": [
{
"type": "grpc",
"cryptoCode": "BTC",
"host": "YOUR_LND_HOST",
"port": "YOUR_LND_PORT",
"macaroon": "YOUR_MACAROON_IN_HEX_FORMAT"
}
]
}
```
```
git checkout fix/delete-invalid-btcpayserver-configs
yarn clean && yarn && yarn dev
```
Bug fix
> fix(migrate): properly migrate btcpayserver configs

- config/default.js
- renderer/components/Pay/Pay.js
- renderer/reducers/payment.js
Fix #1884
To address route failures this PR introduces 2 enhancements:
1. Query routes each time the user goes from invoice to summary page in Pay form
2. Add retries for failed payments
Manually
Enhancement/bugfix
>  fix: retry paying invoice after failure

- README.md
Update README screenshot of app
> fix(readme): update screenshot of app

- renderer/store/configureStore.dev.js
Add redux actions perf measurement
Add user timing hooks to simplify redux actions profiling
Manually with dev tools
Before
After
Devops change
> refactor(devops): add redux actions user timing

- package.json
- test/unit/reducers/__snapshots__/info.spec.js.snap
- yarn.lock
fix #1983
3rd party package we are relying on (`coininfo`) lacks bech32 metadata in networks info. This has resulted in buggy validation in our forms. Coininfo was forked and patched with PR coming soon. For now the package in `package.json` is pointed to our own fork
Manually
Bugfix/Enhancement
> fix(wallet): fix bech32 address validation

- renderer/components/Onboarding/Steps/messages.js
- translations/en.json
Typo in wallet unlocker
fix #1995
Manually
Bug fix
> fix(onboarding): typo in wallet unlocker

- renderer/components/Home/WalletLauncher.js
> fix(settings): edit wallet connection details

- .eslintrc.js
Add exhaustive-deps hooks lint rule. This is a very useful rule, which prevents a lot of non-trivial issues with `useEffect`
More info here [https://github.com/facebook/react/issues/14920](https://github.com/facebook/react/issues/14920)
Manually
Lint rule change
> chore(hooks): add exhaustive deps check rule

- renderer/components/App/App.js
- renderer/components/Pay/Pay.js
- renderer/components/UI/ActionButton.js
- renderer/containers/Logout.js
- renderer/hooks/useCloseOnUnmount.js
- renderer/hooks/useScrollDrag.js
Fixes potential issues with hooks because of incorrect dependency list (exhaustive deps) and some other context issues. This PR is based on #2033 
Manually
Refactor/bugfix
> refactor(hooks): fix potential issues with hooks

- renderer/components/UI/Input.js
- renderer/components/UI/TextArea.js
resovles #1987
Manually
Bugfix
> fix(ui): fix input and textarea focus issue

- package.json
- renderer/components/LoadingBolt/LoadingBolt.js
- renderer/reducers/balance.js
- webpack/dev/common/plugins.js
- yarn.lock
Install CircularDependencyPlugin to detect and report circular dependency issues, and resolve circular dependencies in our codebase.
- refactor(webpack): add CircularDependencyPlugin
- refactor: resolve circular dependencies
Circular dependencies can cause strange, hard to detect issues.
Refactor / fix
> refactor: resolve circular dependencies

- renderer/components/Onboarding/Onboarding.js
- renderer/components/Onboarding/Steps/WalletRecover.js
Resolve #2041
Manually. Recovered a seed as a mainnet wallet and checked that autopilot is turned off
Bugfix
> fix(wallet): mainnet autopilot when recovering a wallet

- renderer/components/Activity/Invoice/Invoice.js
Show invoice final amount in activity list
fix #2047
Follow steps in #2047 (see thread comments)
Bug fix
> fix(wallet): show invoice final amount in activity list

- renderer/components/Channels/ChannelCreateForm.js
- renderer/components/UI/CurrencyFieldGroup.js
- renderer/containers/Channels/ChannelCreateForm.js
Autofocus amount fields
Fix #2046
Ensure amount field autofocuses on channel form.
Bug fix
> fix(ui): autofocus amount fields

- package.json
- yarn.lock
> fix(deps): update lnd to v0.6-beta

- electron/controller.js
- renderer/components/Dialog/DialogLndCrashed.js
- renderer/reducers/address.js
- renderer/reducers/app.js
- renderer/reducers/neutrino.js
- services/neutrino/neutrino.js
- test/unit/lnd/neutrino.spec.js
- utils/validateHost.js
Fix some issues that are causing problems with the e2e test suite
- handle failures generating new addresses
- force kill lnd after failed graceful shutdown
- add more detail in to grpc host error message
e2e test failures
Manually
Bug fix
> fix(wallet): fix issues with failing tests

- webpack/dev/common/devserver.js
- webpack/dev/main.config.js
- webpack/dev/preload.config.js
- webpack/dev/renderer.config.js
- webpack/dev/workers.config.js
- webpack/prod/workers.config.js
- fix broken source map links
- use prod mode for workers in prod build
Fix some issues with source maps and ensure production builds use production settings.
Manually
Enhancement
> build(webpack): fix broken source map links

- docs/ADVANCED.md
- docs/DEBUGGING.md
Add notes on debugging tools
Improve documentation
Manually
Docs improvements
> docs: add notes on debugging tools

- services/neutrino/neutrino.js
Refactor neutrino class into smaller methods
Before working on some improvements to the sync process to better handle the wallet recovery process (See https://github.com/LN-Zap/zap-desktop/issues/2080)
Manually - create new lo al wallet, verify sync works as expected
Refactor
> refactor: refactor neutrino class into smaller methods

- config/default.js
- renderer/components/Home/WalletLauncher.js
- renderer/components/Wallet/WalletMenu.js
- renderer/reducers/autopay.js
- utils/featureFlag.js
Resolves #2096 
Currently, we don't have actual autopay core merged (#1890) so this PR hides `autopay` menu item and disables initialization of autopay 
Manually. Set the flag to true/false in the config
Refactor
> refactor: disable autopay functionality

- config/default.js
- package.json
- renderer/components/Pay/Pay.js
- renderer/components/Pay/PaySummaryOnChain.js
- renderer/reducers/pay.js
- services/grpc/lightning/lightning.methods.js
- test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
- utils/fee.js
- yarn.lock
> feat(wallet): improve fee estimation

- package.json
- renderer/reducers/lnd.js
- services/grpc/grpcService.js
- services/grpc/lightning/lightning.js
- test/unit/reducers/__snapshots__/lnd.spec.js.snap
- update lnd to v0.6.0-beta-31-g43f1290e
- clean up disconnected streams
- prevent duplicate lnd stop actions
- add 2 second delay before connecting to grpc streams
Get latest neutrino updates.
Manually
> fix(deps): update lnd to v0.6.0-beta-31-g43f1290e

- renderer/reducers/lnd.js
- services/grpc/grpcService.js
Fix incorrect subscription to Lightning grpc stream events
Manually
Bugfix
> fix(lnd): subscriptions to Lightning service

- config/default.js
- renderer/components/Onboarding/Onboarding.js
- renderer/components/Onboarding/Steps/Network.js
- test/e2e/onboarding-create.spec.js
- test/e2e/onboarding-import.spec.js
- utils/featureFlag.js
Resolve #2093 
Resolve #2091 
Manually
UI refactoring/enhancement
> feat(ui): allow to set default network and toggle autopilot for mainnet

- renderer/reducers/lnd.js
- services/grpc/grpc.js
Fixes comlink callback error
```
comlink.js?bb96:118 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'MessagePort': [object Function] could not be cloned.
at MessagePort.eval (webpack-internal:///./node_modules/comlinkjs/comlink.js:124:25)
(anonymous) @ comlink.js?bb96:118
async function (async)
(anonymous) @ comlink.js?bb96:85
debug.js?774b:114 zap:grpc 
```
Manually
Bugfix
> fix(grpc): comlink callback error

- webpack/dev/renderer.config.js
- webpack/prod/renderer.config.js
Update CSP policy to allow http calls to `https://api.smartbit.com.au`
Mainnet wallets use `https://api.smartbit.com.au` to fetch block height white it's missing in a whitelist.
Manually
Bugfix
> fix(security): update csp settings

- config/default.js
- services/neutrino/neutrino.js
- utils/lndConfig.js
- clean up neutrino args
- get assumechanvalid setting from global config
Preparation for implementing new autopilot settings
Manually
Refactor
> refactor: clean up neutrino args

- config/default.js
- renderer/components/Syncing/Syncing.js
- renderer/containers/Syncing.js
- renderer/containers/Wallet/ReceiveModal.js
- renderer/reducers/address.js
- renderer/reducers/info.js
- renderer/reducers/transaction.js
- test/unit/reducers/__snapshots__/address.spec.js.snap
- test/unit/reducers/address.spec.js
Adds bech32 address support to the wallet, configurable via the global config file (we need to build a UI for this at some point)
Allow users to receive to bech32 addresses.
Manually
Feature
> feat(wallet): bech32 address support

- config/default.js
- renderer/components/App/App.js
- renderer/containers/App.js
- renderer/containers/Root.js
- renderer/reducers/autopilot.js
- renderer/reducers/index.js
- services/neutrino/neutrino.js
- utils/api.js
- webpack/dev/renderer.config.js
- webpack/prod/renderer.config.js
Apply BOS node scores and to lnd autopilot.
Note: Builds on #2143
Fix #2143
Manually
Feature
> feat(wallet): apply BOS node scores to lnd autopilot

- electron/preload.js
- renderer/components/Home/WalletLauncher.js
- renderer/components/Home/WalletSettingsFormLocal.js
- renderer/components/Home/WalletSettingsFormRemote.js
- renderer/reducers/wallet.js
- renderer/store/db.js
- improve handling of empty form values
- strip unknown properties in db.wallet
Fix #2146 
Additionally, be more strict about which wallet properties we save into the db. Do not save things that are supposed to be dynamically generated at runtime. Instead, generate them after fetching the wallets from the database. This ensures that if we change our underlaying setup at a later date users do not end up with stale wallet configs in their database.
**before:**
**after:**
Manually
Bug fix / enhancement
> fix(onboarding): improve handling of empty form values

- package.json
- scripts/lnd-release/.goreleaser.yml
Update lnd to v0.6.1-beta-rc1-1-g83adaaa0
Update lnd
Manually
Deps update
> fix(deps): update lnd to v0.6.1-beta-rc1-1-g83adaaa0

- renderer/components/App/App.js
Reduce listPeers polling frequency.
There is no need to poll for this data as frequently as we are.
Manualyl
Perf refactor
> refactor: reduce listPeers polling frequency

- renderer/reducers/activity.js
Enhance activity search to support searching on destination addresses, node pubkey, alias, and preimage.
Fix #2174
Manually
Enhancement
> feat(wallet): additional activity search criteria

- renderer/reducers/lnd.js
Disable login button until success
Fix #2229
Manually
Bug fix
> fix(onboarding): disable login button until success

- services/neutrino/neutrino.js
Improve sync progress bar reporting
Fix #2228
Ensure sync bar works properly when:
- do new sync
- do recovery
- stop and start sync in progress
Bug fix
> fix(sync): improve sync progress bar reporting

- renderer/components/Syncing/Progress.js
Use ProgressBar component in sync screen
Consistent look and feel
Manually
Refactor / style update
> refactor: use ProgressBar component in sync screen

- .travis.yml
- appveyor.yml
- package.json
- utils/crypto.js
- yarn.lock
Update deps to allow running on Node 12.
> Node v12 support

- .travis.yml
Enable artifacts addon
Debug build issues
> ci(travis): enable artifacts addon

- package.json
Update lnd to v0.6.1-beta-1-g487677ec
> fix(deps): update lnd to v0.6.1-beta-1-g487677ec

- package.json
- yarn.lock
Updates bitcoinjs-lib to v5.0.4. This just pushes it forward a couple fo commits and gets us off the pinned commit.
> fix(deps): update bitcoinjs-lib to v5.0.4

- .github/config.yml
fix #2257
Hasn't been tested
Github welcome bot fix
> docs: fix links in welcome bot messages

- renderer/components/Onboarding/Steps/ConnectionTypeItem.js
> fix(ui): connection type radio with light theme

- renderer/components/UI/Dropmenu.js
Allow scrolling dropdown menus by clicking on arrow buttons
Current dropdown menus implementation makes it impossible to scroll them without a mouse wheel and/or touchpad gestures
Manually
Enhancement
> feat(ui): add ability to scroll dropdown menus with arrow buttons

- renderer/components/Home/WalletUnlocker.js
- renderer/components/Onboarding/Onboarding.js
Minor adjustments to resolve several prop warnings.
- verify no prop warnings in the logs when on the wallet unlock screen
- verify no prop warnings in the logs when accessing the Onboarding screen
Bug fix
> refactor: fix prop warnings

- renderer/components/Home/Home.js
- renderer/components/Settings/SettingsPage.js
Add padding to bottom of maincontent area
fix #2340
Manually
UI fix
> fix(ui): add padding to bottom of maincontent area

- renderer/components/App/App.js
Currently, activity container is too big and scroll track bar has to move far beyond window bounds to actually bring activity to its very bottom
Manually
Before
After
Bugfix
> fix(ui): activity scrollbar

- renderer/components/Channels/ChannelCreateForm.js
Fix unknown dom prop warning for the create channel form
Manually
Refactor
> fix: unknown dom prop warning

- renderer/reducers/channels.js
- renderer/reducers/network.js
- renderer/store/configureStore.dev.js
- renderer/store/configureStore.prod.js
- renderer/store/middleware/debounceMiddleware.js
- test/unit/utils/debouncedFuncQueue.spec.js
- utils/debouncedFuncQueue.js
Resolve #2225
This PR also introduces easily reusable `debounceMiddleware`.  See code comments for usage example
Manually
Perf optimization
>  perf: debounce updateNodeData

- renderer/components/Request/RequestSummary.js
Currently, LN invoice details page displays paid date in a short format. Not only it's inconsistent with on-chain payment details but also can cause some inconveniences when browsing through past invoices.
Manually
Before
After
Enhancement
> fix(activity): LN invoice paid date

- renderer/components/Activity/ActivityActions/ActivityActions.js
- renderer/components/Channels/ChannelFilter.js
- renderer/components/Channels/ChannelSort.js
- renderer/components/Channels/ChannelsActions.js
- renderer/components/UI/Dropdown.js
- test/unit/components/UI/__snapshots__/Dropdown.spec.js.snap
- test/unit/utils/debouncedFuncQueue.spec.js
Fix incorrect activity search clear button placement
Manually
Before
After
Bugfix
> fix(ui): activity and channels search clear button placement

- electron/migrations/delete-tmp-wallets.js
- electron/migrations/purge-local-wallets.js
- electron/migrator.js
- electron/preload.js
- package.json
- services/neutrino/neutrino.js
- utils/localWallets.js
This PR updates lnd to a recent build from master (0.6.1-beta-255). I reviewed the `rpc.proto` and the only changes vs the version of the proto files that we are currently using from 0.6.1-beta are very minor and not anything that would affect us, so I have not updated them as part of this.
In my limited testing, everything appears to be working normally.
https://github.com/LN-Zap/zap-desktop/issues/2377
Manually
Lnd update
> fix(deps): update lnd to v0.6.1-beta-255-gb3fd7cc8

- package.json
- yarn.lock
Code signing in latest version of electron-builder has issues.
Build broken.
See https://github.com/electron-userland/electron-builder/issues/3948
`yarn package --mac`
Build fix
> chore(deps): pin electron-builder to v20.41.0

- utils/fee.js
Ensure minimum transaction fee of 1 sat per byte
A fee rate of zero does not makes sense, so ensue that all fee rates are at least one.
Manually - Set a very high number of target confs (eg above 100) and then try to make a make an onchain transaction or open a channel and verify that the estimated fee is a minimum of 1 sat per byte.
Bug fix
> fix(wallet): ensure minimum transaction fee of 1 sat per byte

- config/default.js
Adjust default target confs from 1/3/6 to 1/6/60
Provide more variance between the three options (fast, medium, slow)
Manually
Enhancement
> fix(wallet): adjust default target confs to 1/6/60

- renderer/components/UI/ProgressBar.js
- renderer/reducers/neutrino.js
- test/unit/reducers/__snapshots__/neutrino.spec.js.snap
- test/unit/reducers/neutrino.spec.js
Debounce sync progress updates
Reduce excessive renders in the sync process
Manually
Performance enhancement
> perf: debounce sync progress updates

- package.json
Update lnd to v0.7.0-beta-rc1-1-g17986e83
Bundle with latest release candidate rather than build from a week prior.
Manually
lnd update
> fix(deps): update lnd to v0.7.0-beta-rc1-1-g17986e83

- renderer/components/Wallet/Wallet.js
Ensure logo remains in constant position
This prevents it from moving around when you switch between the wallet and preferences pages.
1. Log into a wallet
2. Open the preferences page
... verify that logo remains in static position.
UI fix
> fix(ui): ensure logo remains in constant position

- renderer/reducers/invoice.js
- renderer/reducers/payment.js
- renderer/reducers/transaction.js
Don't mutate objects when decorating
Mutation is nasty and can lead to hard to debug problems
Manually
Refactor
> refactor: don't mutate objects when decorating

- utils/api.js
- utils/error.js
- utils/fee.js
Improve cryptic error messages in the log when estimating fees.
If you connect to an older version of lnd and try to make an onchain payment there are several rather cryptic warnings in the log.
Connect to testnet1 node and try to make an onchain payment
**Before:**
**After:**
refactor
> refactor: improve fee estimation error handling

- package.json
Update lnd to v0.7.0-beta-rc2-1
Incorporate recent improvements in lnd.
Manually
Lnd upgrade
> fix(deps): update lnd to v0.7.0-beta-rc2-1-g360a7fe6

- renderer/reducers/activity.js
don't apply date grouping to raw activity list
Prevents app crash when using date filter caused by unexpected data produced by the activity selectors.
Test activity list filters
Bug fix
> fix(ui): don't apply date grouping to raw activity list

- package.json
- renderer/components/Home/WalletLauncher.js
- renderer/reducers/lnd.js
- services/grpc/grpc.js
- yarn.lock
When connecting to remote nodes some errors during wallet unlock are swallowed resulting in UI becoming stuck. This PR revamps unlock flow and also adds 1 minute for unlock procedure
Resolves #2430 
Manually
Bugfix
> fix(grpc): deadlock when connecting to remote nodes in some cases

- package.json
Update lnd to v0.7.0-beta-rc3-1-gf366eed4
Manually
Deps update
> fix(deps): update lnd to v0.7.0-beta-rc3-1-gf366eed4

- renderer/reducers/channels.js
- renderer/reducers/invoice.js
- renderer/reducers/neutrino.js
- renderer/reducers/onboarding.js
- renderer/reducers/peers.js
- test/unit/reducers/__snapshots__/channels.spec.js.snap
- test/unit/reducers/__snapshots__/invoice.spec.js.snap
- test/unit/reducers/__snapshots__/peers.spec.js.snap
- test/unit/reducers/invoice.spec.js
This PR removes unused redux state entries
Manually
Refactor
> refactor: remove unused state entries

- package.json
Mark i18n/locale.js as having side-effects to ensure that webpack does not tree-shake it.
Fix #2539
Run a production build and verify that language switching works.
Bug fix
> fix(i18n): ensure translation files are available

- package.json
- renderer/reducers/network.js
- renderer/reducers/payment.js
- renderer/reducers/utils/createReducer.js
- yarn.lock
Currently, we are using vanilla JS in our reducers which makes code boilerplatty, harder to write, read and prone to immutability errors. One option is to use `immutableJS` lib, but it requires a full rewrite of our reducers and a lot of changes to our components. It's also not compatible with libraries like `lodash` which we currently use a lot. This PR proposes to start using `immer` as a solution for the immutability. Benefits of immer:
1. No need to use additional container libs
2. Can be used with vanilla js or with `lodash`
3. No need to change our components
4. Migration can be done iteratively - state produced by immer is fully compatible with the old one
5. State auto-freeze
More info:
https://github.com/immerjs/immer
https://www.netlify.com/blog/2018/09/12/the-rise-of-immer-in-re …
> refactor: use immer in network and payment reducers

- package.json
- services/grpc/lightning.methods.js
- utils/promisifiedCall.js
- yarn.lock
Needed in conjunction with https://github.com/LN-Zap/node-lnd-grpc/pull/45
Connection attempt not timing out if call to getInfo fails during the connection attempt.
Manually
Bug fix
> fix(grpc): forward grpc options to getInfo

- package.json
- yarn.lock
Remove unused concurrently dependency
Keep codebase as lean as possible
Manually
Deps update
> chore(deps): remove unused concurrently dependency

- renderer/components/Request/RequestSummary.js
Recheck invoice expire on a regular schedule to ensure that it works consistently for large expire times (setInterval has a max value which is less than the max possible expire time for an invoice).
fix #2547
Manually
Bug fix
> fix(ui): display correct invoice expire time

- renderer/reducers/backup.js
Do not throw skip backup error
This fixes an issue when creating a new wallet with the skip backup
option selected caused by trying to dispatch an action that has no
type.
fix #2571
Try to create a wallet with skip backup option
Bug fix
> fix(backups): do not throw skip backup error

- renderer/reducers/activity.js
- renderer/reducers/address.js
- renderer/reducers/app.js
- renderer/reducers/balance.js
- renderer/reducers/info.js
- renderer/reducers/notification.js
- renderer/reducers/pay.js
- test/unit/reducers/__snapshots__/address.spec.js.snap
- test/unit/reducers/address.spec.js
Continue migration to `immer` 
Manually
Refactor
> refactor: use immer in a number of reducers

- renderer/reducers/autopilot.js
- renderer/reducers/backup.js
- renderer/reducers/channels.js
- renderer/reducers/contactsform.js
- renderer/reducers/invoice.js
- renderer/reducers/lnd.js
- renderer/reducers/utils/createReducer.js
This PR migrates a number of reducers (some that have an app-wide scope) to immer.
Continue step-by-step migration to immer
Manually
Refactor
> refactor: continue immer migration

- renderer/reducers/modal.js
- renderer/reducers/neutrino.js
- renderer/reducers/onboarding.js
- renderer/reducers/peers.js
- renderer/reducers/settings.js
- renderer/reducers/settingsmenu.js
- renderer/reducers/theme.js
- renderer/reducers/ticker.js
- renderer/reducers/transaction.js
- renderer/reducers/utils/createReducer.js
- renderer/reducers/wallet.js
This PR concludes migration to immer. This PR builds on top of #2579 so ideally should be tested after that ones is merged
Manually
> refactor: finish immer migration

- package.json
- scripts/lnd-release/.goreleaser.yml
- services/neutrino/neutrino.js
- yarn.lock
- update lnd to 0.7.1-beta-rc2-3-g3d84693a
- set neutrino user agent name and version
- update lnd-grpc to v0.3.0-beta.2
Fix #2612
Manually
Dep Updates
> fix(lnd): update lnd to 0.7.1-beta-rc2-3-g3d84693a

- renderer/reducers/payment.js
> fix(ui): unknown recipient when sending ln payment

- renderer/components/UI/CurrencyFieldGroup.js
> fix(ui): ensure fiat and crypto inputs in agroup are always updated

- .travis.yml
- package.json
- test/unit/__mocks__/keytar.js
- test/unit/utils/secureStorage.spec.js
- utils/secureStorage.js
- webpack/dev/main.config.js
- webpack/prod/main.config.js
- webpack/webpack.config.dll.js
- yarn.lock
Add the ability to store sensitive data in OS secure storage (macOS keychain, windows credentials manager, gnome keyring)
This will allow to store sensitive data such as lndconnect strings or access tokens in a more secure way
via tests
Refactor
> refactor(utils): implement secureStorage util

- appveyor.yml
- package.json
There are actually no changes in lnd since rc2 so this just gets us a version number bump.
> fix(deps): update lnd to v0.7.1-beta-3-g26af2265

- README.md
Add documentation index into main README
Make it easier for people to find what they need in our documentation.
Manually
Docs update
> docs: add documentation index into main README

- electron/about/index.js
- electron/about/public/renderer.js
- electron/menuBuilder.js
- i18n/locale.js
- renderer/components/TabControl/PersistentTabControl.js
- renderer/components/UI/Wizard.js
- renderer/containers/Onboarding/Onboarding.js
- renderer/hooks/usePrevious.js
- test/unit/__helpers__/intl-enzyme-test-helper.js
Fix lint issues
Ensure code style consistency
`yarn lint`
Lint
> style(lint): fix lint issues

- renderer/reducers/address.js
- renderer/store/db.js
- renderer/store/dbVersions.js
- renderer/store/schema/node.js
- renderer/store/schema/setting.js
- renderer/store/schema/wallet.js
Clean up dexie code
Clean up `db.js` a little.
Manually
Refactor
> refactor: clean up dexie code

- renderer/reducers/address.js
- renderer/reducers/autopilot.js
- renderer/reducers/backup.js
- renderer/reducers/balance.js
- renderer/reducers/channels.js
- renderer/reducers/info.js
- renderer/reducers/invoice.js
- renderer/reducers/lnd.js
- renderer/reducers/network.js
- renderer/reducers/neutrino.js
- renderer/reducers/pay.js
- renderer/reducers/payment.js
- renderer/reducers/peers.js
- renderer/reducers/transaction.js
- renderer/workers/index.js
- renderer/workers/proxymise.js
- test/unit/__helpers__/setup.js
- utils/fee.js
Simplify interaction with grpc comlink proxy. 
Instead of
```
import { grpcService } from 'workers'
const grpc = await grpcService
const result = await grpc.service.Lightning.someStuff()
```
We can now just do
```
import { grpc } from 'workers'
const result = await grpc.service.Lightning.someStuff()
```
Reduce boilerplate and improve code readability
Manually
Refactor
> refactor: proxymise grpc calls

- renderer/components/UI/CryptoAmountInput.js
Increment satoshi amount using up arrow
fix #2679
Manually
Fix
> fix(ui): increment satoshi amount using up arrow

- renderer/components/UI/Card.js
- renderer/components/UI/Dialog.js
- renderer/components/UI/Dropdown.js
- renderer/components/UI/GlobalStyle.js
- renderer/components/UI/Notification.js
- renderer/components/UI/Page.js
- renderer/components/UI/Select.js
- renderer/components/UI/Sidebar.js
- renderer/components/UI/Toggle.js
- renderer/components/UI/Tooltip.js
- renderer/themes/base.js
- renderer/themes/dark/index.js
- renderer/themes/light/index.js
- renderer/themes/light/shadows.js
- renderer/themes/util.js
- stories/_general/color.stories.js
- test/unit/components/UI/__snapshots__/Card.spec.js.snap
- test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
- test/unit/components/UI/__snapshots__/Modal.spec.js.snap
- test/unit/components/UI/__snapshots__/Notification.spec.js.snap
- test/unit/components/UI/__snapshots__/Page.spec.js.snap
- test/unit/components/UI/__snapshots__/Sidebar.spec.js.snap
- test/unit/components/UI/__snapshots__/Toggle.spec.js.snap
Lighten shadows in light theme
fix #2680
Manually
Theme fixes
> fix(ui): lighten shadows in light theme

- docs/ADVANCED.md
Document build commands
Improve docs
Manually
Docs improvement
> docs: document build commands

- renderer/components/Activity/PaymentModal/PaymentModal.js
- utils/crypto.js
Display memo in the outgoing payment modal if it is available/supported by the LND
Resolves #2715 
Manually. Pay LN request that has a memo and open details modal afterwards
Enhancement
>  feat(ui): show memo in outgoing LN payment summary 

- services/grpc/lightning.subscriptions.js
- utils/streamify.js
Make `streamify` more general-purpose and fix some long-standing issues it had
Manually
Refactor/bugfix
> refactor: simplify streamify util

- README.md
- docs/RELEASING.md
- docs/SIGNATURES.md
- scripts/signedchecksum.sh
- Add checksum signing script
- Add docs/RELEASING.md
- Add docs/SIGNATURES.md
Document release and signing processes.
Manually
Docs
> build: add checksum signing script and docs

- renderer/components/Form/CurrencyFieldGroup.js
- renderer/components/Form/Input.js
- renderer/components/Form/TextArea.js
- renderer/components/Request/Request.js
- renderer/containers/ModalStack.js
- renderer/hooks/index.js
- renderer/hooks/useAutoFocus.js
- stories/forms/form.stories.js
- test/unit/components/Form/__snapshots__/Input.spec.js.snap
- test/unit/components/Form/__snapshots__/NodePubkeyInput.spec.js.snap
- test/unit/components/Form/__snapshots__/Select.spec.js.snap
- test/unit/components/Form/__snapshots__/TextArea.spec.js.snap
Set missing input props
Ensure autofocus works
Add autofocus examples in storybook
We set TextArea `name` based on field but fail to do so in the `Input` component.
Manually
Refactor
> fix(ui): form input name and autofocus

- docs/CONTRIBUTING.md
- icons/download.svg
- renderer/components/Activity/TransactionModal/TransactionModal.js
- renderer/components/Icon/Download.js
- scripts/genIcons.js
- scripts/genIconsStory.js
- stories/icons/icon.stories.js
Use the appropriate download icon in TransactionModal for `Download` button
This PR also introduces an automatic update of the storybook `icons` section so it's always in sync with `components/Icon` contents
Manually
Devops enhancement, bugfix
> fix: update download icon in TransactionModal

- scripts/genIcons.js
- scripts/genIconsStory.js
- stories/AllIcons/AllIcons.stories.js
Generate `All Icons` storybook section after running `yarn generate-icon` command
yarn generate-icon som_icon
Build/Storybook update
> build: add all icons list update when generating new icons

- renderer/components/Profile/ProfilePaneVerifyMessage/ProfilePaneVerifyMessage.js
- renderer/components/UI/Dropmenu.js
Fix layout issue in profile/verify message
Fix layout issue with Settings dropmenu
Manually
Bugfix
> fix: layout issues

- renderer/components/Onboarding/Steps/SeedConfirm.js
> fix(ui): center seed confirm inputs

- renderer/components/ModalStack.js
- renderer/containers/Root.js
Resolves #2823 
Manually
Bugfix
>  fix: crash in some cases when opening multiple modals 

- test/unit/utils/scheduler.spec.js
- utils/scheduler.js
In some condition `scheduler` tasks weren't cleared or replaced correctly, causing old and new tasks to run in parallel.
Manually and new test
Bugfix
> fix(scheduler): buggy task replacement and removeAll behavior

- renderer/components/Form/Select.js
- stories/forms/form.stories.js
- test/unit/components/Form/__snapshots__/Select.spec.js.snap
Ensure select value from items list
Fixes an issue in which it's possible to type an invalid value into a select input,.
eg, prevent this:
Storybook
Fix
> fix(ui): ensure select value from items list

- renderer/components/Form/Checkbox.js
- test/unit/components/Form/__snapshots__/Checkbox.spec.js.snap
> fix(checkbox): react uncontrolled component warning

- renderer/reducers/address.js
Fixes an issue with address generation.
Address missing from on-chain deposit screen
1. Delete the entry for your node in `nodes` database table
2. Reload the app
3. Go to deposit screen - note missing address
**Before:**
**After:**
Bug fix
> fix(wallet): ensure address generation works

- electron/menuBuilder.js
- package.json
- yarn.lock
Revert https://github.com/LN-Zap/zap-desktop/pull/2836/commits/d40be7070b307c7fb936b4658ced325d8b211882
as it is not needed after electron update to `v6.0.10`
Manually on win10 x64 and Ubuntu 18.04 x64
Refactor/deps update
> chore(deps): update dependency electron to v6.0.10

- config/default.js
- renderer/components/Activity/Activity.js
- renderer/components/App/App.js
- renderer/containers/Activity/Activity.js
- renderer/reducers/activity.js
- renderer/reducers/app.js
- renderer/reducers/invoice.js
- renderer/reducers/payment.js
- renderer/reducers/transaction.js
- test/unit/reducers/__snapshots__/activity.spec.js.snap
- test/unit/reducers/__snapshots__/invoice.spec.js.snap
- test/unit/reducers/__snapshots__/payment.spec.js.snap
- test/unit/reducers/activity.spec.js
- test/unit/reducers/invoice.spec.js
- test/unit/reducers/payment.spec.js
- test/unit/utils/pagination.test.js
- utils/pagination.js
Resolves #2404 
Unit tests/manually
Perf improvement/bugfix
> perf(activity): implement activity list pagination

- renderer/components/Home/WalletLauncher.js
- renderer/components/Home/WalletSettingsFormLocal.js
Fix crash when trying to update remote wallet settings in the launchpad
Manually
Bugfix
> fix(ui): crash when trying to save remote node settings

- test/e2e/onboarding-import.spec.js
- test/e2e/pages/onboarding.js
Rebased version of https://github.com/LN-Zap/zap-desktop/pull/2829 with minor fix as per unaddressed comments in that PR
> test(onboarding): test encrypted seed import

- renderer/components/Channels/ChannelCreateForm.js
- renderer/components/Home/Home.js
- renderer/components/Home/WalletLauncher.js
- renderer/components/Onboarding/Steps/ConnectionDetails.js
- renderer/components/Onboarding/Steps/ConnectionDetailsManual.js
- renderer/components/Onboarding/Steps/ConnectionDetailsString.js
- renderer/components/Onboarding/Steps/ConnectionType.js
- renderer/components/Onboarding/Steps/SeedConfirm.js
- renderer/components/Onboarding/Steps/SeedView.js
- renderer/components/Onboarding/Steps/WalletCreate.js
- renderer/components/Onboarding/Steps/WalletRecover.js
- renderer/components/Pay/Pay.js
- renderer/components/Pay/PaySummaryOnChain.js
- renderer/components/UI/Countdown.js
- renderer/containers/Wallet/WalletStarter.js
Reverts the change from https://github.com/LN-Zap/zap-desktop/commit/b47416eebb852e031d4eeaf77b15540d5f19d9ad
That change was unneeded and incorrect.
- Fix #2944
- Fix #2945
Manually
Fix
> revert: b47416e as mistake

- renderer/components/Onboarding/Steps/Recover.js
- renderer/components/Onboarding/Steps/components/SeedWordInput.js
- renderer/components/Onboarding/Steps/components/SeedWordList.js
- renderer/containers/Onboarding/Onboarding.js
- renderer/containers/Onboarding/Steps/Recover.js
- test/e2e/onboarding-import.spec.js
- test/e2e/pages/onboarding.js
Updated version of https://github.com/LN-Zap/zap-desktop/pull/2896 that ensues that the seed word inputs don't switch from controlled to uncontrolled inputs.
> feat(ui): add autosuggest for seed recovery

- renderer/components/Activity/Activity.js
- renderer/components/Activity/List.js
- renderer/components/Activity/Row.js
- renderer/reducers/activity.js
This PR extracts some of the activity list parts to make them reusable for similar kinds of lists
Builds on top of #2911 
Manually
Refactor
> refactor: activity list components

- renderer/components/Channels/ChannelCreateForm.js
> fix(ui): make sure channel create button doesn't overflow

- config/default.js
Resolves #2967 
This PR takes the simplest approach which seems to be inline with how we override domain for the db
```
db: {
namespace: 'ZapDesktop',
domain: IS_STABLE_VERSION ? null : 'next',
},
```
Manually
Devops
> refactor: add secure storage namespacing based on environment

- config/default.js
- package.json
Update lnd to 0.8.0-beta-2-gb95a0a0f
Update default neutrino testnet backends 
Update lnd / btcd backends
Manually
Infrastructure
> fix(deps): update lnd to 0.8.0-beta-2-gb95a0a0f

- renderer/containers/Channels.js
- renderer/containers/Channels/ChannelsHeader.js
- renderer/reducers/channels.js
- test/unit/reducers/__snapshots__/channels.spec.js.snap
> fix(ui): retain channel view mode on logout

- renderer/store/schema/wallet.js
Fix a bug in db update hook which prevents correct `wallet` object sanitization. Presumably issue was introduced during 3.0 dexie migration.
Manually
Bugfix/refactor
> fix(db): wallet table sanitize routine

- renderer/components/Activity/ActivityActions/ActivityFilter.js
- renderer/components/Channels/ChannelCloseDialog.js
- renderer/components/Dialog/DialogLndCrashed.js
- renderer/components/Home/DeleteWalletDialog.js
- renderer/components/Home/WalletSettingsFormLocal.js
- renderer/components/Home/WalletSettingsFormRemote.js
- renderer/components/Onboarding/Steps/components/ErrorDialog.js
- renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
- renderer/components/Profile/ProfilePaneNodeInfo/ProfilePaneNodeInfo.js
- renderer/components/UI/RadioCard.js
Address issues in #3046 
Manually
Visual adjustments.
> fix(ui): minor display issues on macOS

- config/default.js
- renderer/components/Settings/SettingsPage.js
Disable app password feature on windows
Manually
Security adjustment
> fix(ui): disable app password on windows platform

- renderer/components/Channels/ChannelsMenu/ChannelsMenu.js
- test/e2e/basic-ui.spec.js
> fix(ui): don't open channel management modal when not needed

- electron/main.js
Under some conditions protocol links (`lightning, bitcoin, lndconnect`) aren't working when zap is already launched. This is caused by extra arguments passed to `argv` while the app expects link to be the second parameter. 
`yarn package --win` + some links
Bugfix
> fix(wallet): correctly handle protocol links on windows

- electron/walletBackup/dropbox/db.js
- electron/walletBackup/dropbox/dbApi.js
- electron/walletBackup/dropbox/index.js
- electron/walletBackup/gdrive/gdrive.js
- electron/walletBackup/gdrive/index.js
- renderer/components/Channels/ChannelCreateForm.js
- renderer/components/Form/IntegerInput.js
- renderer/components/Form/LightningInvoiceInput.js
- renderer/components/Form/LndConnectionStringInput.js
- renderer/components/Form/NodePubkeyInput.js
- renderer/components/Home/WalletLauncher.js
- renderer/components/Onboarding/Steps/ConnectionDetailsManual.js
- renderer/components/Pay/Pay.js
- renderer/hocs/withInputValidation.js
- renderer/hocs/withNumberValidation.js
- renderer/hooks/useTimeout.js
- renderer/reducers/autopay.js
- renderer/reducers/backup.js
- renderer/reducers/info.js
- renderer/reducers/onboarding.js
- renderer/store/dbVersions.js
- services/grpc/grpc.js
- stories/components/dialog.stories.js
- test/e2e/pages/wallet.js
- utils/lndConfig.js
Rebased and fixed version of https://github.com/LN-Zap/zap-desktop/pull/3002
Get #3002 merged
Manually
Refactor
> Fix more eslint6 warnings

- renderer/components/Form/LightningInvoiceInput.js
- test/unit/components/Form/__snapshots__/LightningInvoiceInput.spec.js.snap
Fix validation of LN PRs / on-chain addresses in Pay view.
Manually
Bugfix
> Fix LN/Onchain invoice validation

- renderer/components/Pay/Pay.js
- renderer/containers/Pay.js
- renderer/reducers/activity.js
- test/unit/reducers/__snapshots__/activity.spec.js.snap
- test/unit/reducers/activity.spec.js
Fix a bug that resulted in "Sent" filter being removed after sending a payment. This PR also removes sending activity from "Sent" filter to avoid duplicated when it's used together with "Pending" activity
Manually
Bugfix
> Fix activity filters

- renderer/components/Activity/Transaction/Transaction.js
- renderer/components/Activity/Transaction/messages.js
- renderer/reducers/activity.js
- renderer/reducers/transaction.js
- translations/en.json
Inject a fake transaction id into a sending transaction so that we can properly track it throughout the sending process.
- Ensure sending transaction failures are handled correctly.
- Fix date issue with sending transactions 
Manually
Fix
> fix(wallet): ensure transaction sending error handled

- renderer/components/Form/LightningInvoiceInput.js
- renderer/components/Pay/Pay.js
- renderer/components/Pay/PayAmountFields.js
- renderer/components/Pay/PayPanelFooter.js
Fix number of issues in Pay form:
- resolves #3175 
- resolves #3176 
- Adds trimming to pay form address/PR input
Manually
Bugfixes/Minor perf improvements
> Fix number of issues in pay form

- renderer/components/UI/Wizard.js
- renderer/hooks/useOnKeydown.js
Resolves #3172 
Manually
Bugfix/enhancement
> Allow submitting any onboarding step with "return" key

- renderer/reducers/address.js
Ensure that newly generated wallet addresses are retained in state and available to the ui after generation.
Fix #3182
Manually
Fix
> fix(onboarding): retain wallet addresses in state

- renderer/reducers/transaction.js
Rename `transactionId` which serves as tx sending indentifier to `internalId` to reduce ambiguity. 
Manually.
Refactor
> refactor: rename transactionId to internalId

- renderer/reducers/channels.js
Factor sent and received in channel capacity
Current calculation does not correctly factor in both sent and receive.
Manually
Fix
> fix(wallet): factor sent and received in channel capacity

- renderer/components/Activity/TransactionModal/TransactionModal.js
> fix(ui): show correct heading for received payment in modal

- package.json
- renderer/reducers/lnd.js
- renderer/reducers/neutrino.js
- renderer/workers/grpc.worker.js
- renderer/workers/index.js
- renderer/workers/neutrino.worker.js
- services/grpc/grpc.js
- yarn.lock
Update from comlinkjs v3.2.0 to comlink v4.2.0
We're stuck on a very of version of comlink that is no longer maintained. Bring us upto date.
Manually
> fix(deps): update from comlinkjs v3.2.0 to comlink v4.2.0

- renderer/components/Pay/Pay.js
- renderer/components/Pay/PayAddressField.js
- renderer/components/Pay/PayPanelBody.js
- renderer/components/Pay/PayPanelFooter.js
- renderer/components/Pay/PayPanelHeader.js
- renderer/components/Pay/PaySummary.js
- renderer/components/Pay/constants.js
- test/unit/components/Pay/PayAddressField.spec.js
- test/unit/components/Pay/PayPanelBody.spec.js
- test/unit/components/Pay/PayPanelHeader.spec.js
- test/unit/components/Pay/__snapshots__/PayAddressField.spec.js.snap
- test/unit/components/Pay/__snapshots__/PayPanelBody.spec.js.snap
Combine `isBolt11`, `isOnchain` and `isPubkey` flags into one enum.
Address #3417
Manually
Refactor
> refactor(ui): simplify pay form components

- renderer/reducers/channels/reducer.js
- renderer/reducers/payment/reducer.js
- renderer/reducers/transaction.js
Prevent excessive data fetching.
Channel data and balance is fetched multiple times when updating activity history.
Manually
> Prevent excessive data fetching

- package.json
- services/neutrino/neutrino.js
- yarn.lock
> Update lnd to 0.11.0-beta

- renderer/reducers/channels/utils.js
Use numerical sorting for channel capacity sort order.
fix #3633
Manually
Fix
> Fix channel capacity sort

- renderer/components/App/App.js
- renderer/containers/App/App.js
- renderer/reducers/activity/reducer.js
- renderer/reducers/info/selectors.js
- renderer/reducers/peers.js
Speeds up perceived node data load times by:
- fetching node info from peers early
- loading channel data before activity history
- limiting refetch of network graph to initial graph sync
Improve performance connecting to large nodes
Manually
> App loading performance improvements

- package.json
- yarn.lock
Update to testcafe-browser-provider-electron v0.0.15
> chore(deps-dev): update to testcafe-browser-provider-electron v0.0.15

- package.json
- renderer/reducers/transaction/reducer.js
- yarn.lock
- Update to lnd 0.11.1
- Enable spending unconfirmed outputs.
Update lnd
Manually
Enhancements
> Update to lnd 0.11.1

- renderer/components/Channels/ChannelCloseDialog.js
- renderer/components/Channels/ChannelCreateForm.js
- renderer/components/Form/TransactionFeeInput.js
- renderer/containers/Channels/ChannelCloseDialog.js
- renderer/reducers/channels/reducer.js
- services/grpc/lightning.methods.js
WIP: Ability to set transaction fee during channel close
Fix #2526
Manually
Enhancement
> Ability to set transaction fee during channel close

- renderer/components/Activity/ActivityActions/ActivityActions.js
- renderer/components/Activity/ActivityActions/ActivityRefresh.js
- renderer/components/App/App.js
- renderer/components/Home/Home.js
- renderer/components/Home/WalletLauncher.js
- renderer/components/UI/ActionButton.js
- renderer/containers/Activity/ActivityActions.js
- renderer/containers/Home/Home.js
- renderer/reducers/activity/reducer.js
- renderer/reducers/activity/selectors.js
- renderer/reducers/activity/utils.js
- renderer/reducers/transaction/reducer.js
Adds a number of improvements for activity list
Activity list unresponsive for nodes with lots of data
Manually
Enhancements
> Improvements for activity list

- package.json
- yarn.lock
Security update for electron
Manual and by running tests
> chore(deps): update dependency electron to v9.3.4

- config/default.js
- package.json
- services/neutrino/neutrino.js
- utils/lndConfig.js
- yarn.lock
Update to lnd 0.13.0 beta
Closes: #3730
Update lnd
Enhancement
> Update lnd to v0.13.1-beta

- package.json
- yarn.lock
> Add support for lnd 0.14
